// Code generated by protoc-gen-go.
// source: data_player.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

type ContactSettings struct {
	SendMarketingEmails   bool `protobuf:"varint,1,opt,name=send_marketing_emails" json:"send_marketing_emails,omitempty"`
	SendPushNotifications bool `protobuf:"varint,2,opt,name=send_push_notifications" json:"send_push_notifications,omitempty"`
}

func (m *ContactSettings) Reset()         { *m = ContactSettings{} }
func (m *ContactSettings) String() string { return proto.CompactTextString(m) }
func (*ContactSettings) ProtoMessage()    {}

type PlayerAvatar struct {
	Skin     int32  `protobuf:"varint,2,opt,name=skin" json:"skin,omitempty"`
	Hair     int32  `protobuf:"varint,3,opt,name=hair" json:"hair,omitempty"`
	Shirt    int32  `protobuf:"varint,4,opt,name=shirt" json:"shirt,omitempty"`
	Pants    int32  `protobuf:"varint,5,opt,name=pants" json:"pants,omitempty"`
	Hat      int32  `protobuf:"varint,6,opt,name=hat" json:"hat,omitempty"`
	Shoes    int32  `protobuf:"varint,7,opt,name=shoes" json:"shoes,omitempty"`
	Gender   Gender `protobuf:"varint,8,opt,name=gender,enum=POGOProtos.Enums.Gender" json:"gender,omitempty"`
	Eyes     int32  `protobuf:"varint,9,opt,name=eyes" json:"eyes,omitempty"`
	Backpack int32  `protobuf:"varint,10,opt,name=backpack" json:"backpack,omitempty"`
}

func (m *PlayerAvatar) Reset()         { *m = PlayerAvatar{} }
func (m *PlayerAvatar) String() string { return proto.CompactTextString(m) }
func (*PlayerAvatar) ProtoMessage()    {}

type Currency struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Amount int32  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}

type EquippedBadge struct {
	BadgeType                         BadgeType `protobuf:"varint,1,opt,name=badge_type,enum=POGOProtos.Enums.BadgeType" json:"badge_type,omitempty"`
	Level                             int32     `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	NextEquipChangeAllowedTimestampMs int64     `protobuf:"varint,3,opt,name=next_equip_change_allowed_timestamp_ms" json:"next_equip_change_allowed_timestamp_ms,omitempty"`
}

func (m *EquippedBadge) Reset()         { *m = EquippedBadge{} }
func (m *EquippedBadge) String() string { return proto.CompactTextString(m) }
func (*EquippedBadge) ProtoMessage()    {}

type PlayerStats struct {
	Level                int32   `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Experience           int64   `protobuf:"varint,2,opt,name=experience" json:"experience,omitempty"`
	PrevLevelXp          int64   `protobuf:"varint,3,opt,name=prev_level_xp" json:"prev_level_xp,omitempty"`
	NextLevelXp          int64   `protobuf:"varint,4,opt,name=next_level_xp" json:"next_level_xp,omitempty"`
	KmWalked             float32 `protobuf:"fixed32,5,opt,name=km_walked" json:"km_walked,omitempty"`
	PokemonsEncountered  int32   `protobuf:"varint,6,opt,name=pokemons_encountered" json:"pokemons_encountered,omitempty"`
	UniquePokedexEntries int32   `protobuf:"varint,7,opt,name=unique_pokedex_entries" json:"unique_pokedex_entries,omitempty"`
	PokemonsCaptured     int32   `protobuf:"varint,8,opt,name=pokemons_captured" json:"pokemons_captured,omitempty"`
	Evolutions           int32   `protobuf:"varint,9,opt,name=evolutions" json:"evolutions,omitempty"`
	PokeStopVisits       int32   `protobuf:"varint,10,opt,name=poke_stop_visits" json:"poke_stop_visits,omitempty"`
	PokeballsThrown      int32   `protobuf:"varint,11,opt,name=pokeballs_thrown" json:"pokeballs_thrown,omitempty"`
	EggsHatched          int32   `protobuf:"varint,12,opt,name=eggs_hatched" json:"eggs_hatched,omitempty"`
	BigMagikarpCaught    int32   `protobuf:"varint,13,opt,name=big_magikarp_caught" json:"big_magikarp_caught,omitempty"`
	BattleAttackWon      int32   `protobuf:"varint,14,opt,name=battle_attack_won" json:"battle_attack_won,omitempty"`
	BattleAttackTotal    int32   `protobuf:"varint,15,opt,name=battle_attack_total" json:"battle_attack_total,omitempty"`
	BattleDefendedWon    int32   `protobuf:"varint,16,opt,name=battle_defended_won" json:"battle_defended_won,omitempty"`
	BattleTrainingWon    int32   `protobuf:"varint,17,opt,name=battle_training_won" json:"battle_training_won,omitempty"`
	BattleTrainingTotal  int32   `protobuf:"varint,18,opt,name=battle_training_total" json:"battle_training_total,omitempty"`
	PrestigeRaisedTotal  int32   `protobuf:"varint,19,opt,name=prestige_raised_total" json:"prestige_raised_total,omitempty"`
	PrestigeDroppedTotal int32   `protobuf:"varint,20,opt,name=prestige_dropped_total" json:"prestige_dropped_total,omitempty"`
	PokemonDeployed      int32   `protobuf:"varint,21,opt,name=pokemon_deployed" json:"pokemon_deployed,omitempty"`
	PokemonCaughtByType  []int32 `protobuf:"varint,22,rep,name=pokemon_caught_by_type" json:"pokemon_caught_by_type,omitempty"`
	SmallRattataCaught   int32   `protobuf:"varint,23,opt,name=small_rattata_caught" json:"small_rattata_caught,omitempty"`
}

func (m *PlayerStats) Reset()         { *m = PlayerStats{} }
func (m *PlayerStats) String() string { return proto.CompactTextString(m) }
func (*PlayerStats) ProtoMessage()    {}

type PlayerCamera struct {
	IsDefaultCamera bool `protobuf:"varint,1,opt,name=is_default_camera" json:"is_default_camera,omitempty"`
}

func (m *PlayerCamera) Reset()         { *m = PlayerCamera{} }
func (m *PlayerCamera) String() string { return proto.CompactTextString(m) }
func (*PlayerCamera) ProtoMessage()    {}

type PlayerCurrency struct {
	Gems int32 `protobuf:"varint,1,opt,name=gems" json:"gems,omitempty"`
}

func (m *PlayerCurrency) Reset()         { *m = PlayerCurrency{} }
func (m *PlayerCurrency) String() string { return proto.CompactTextString(m) }
func (*PlayerCurrency) ProtoMessage()    {}

type PlayerPublicProfile struct {
	Name   string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Level  int32         `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Avatar *PlayerAvatar `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
}

func (m *PlayerPublicProfile) Reset()         { *m = PlayerPublicProfile{} }
func (m *PlayerPublicProfile) String() string { return proto.CompactTextString(m) }
func (*PlayerPublicProfile) ProtoMessage()    {}

func (m *PlayerPublicProfile) GetAvatar() *PlayerAvatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type DailyBonus struct {
	NextCollectedTimestampMs            int64 `protobuf:"varint,1,opt,name=next_collected_timestamp_ms" json:"next_collected_timestamp_ms,omitempty"`
	NextDefenderBonusCollectTimestampMs int64 `protobuf:"varint,2,opt,name=next_defender_bonus_collect_timestamp_ms" json:"next_defender_bonus_collect_timestamp_ms,omitempty"`
}

func (m *DailyBonus) Reset()         { *m = DailyBonus{} }
func (m *DailyBonus) String() string { return proto.CompactTextString(m) }
func (*DailyBonus) ProtoMessage()    {}

func init() {
}
