// Code generated by protoc-gen-go.
// source: networking_envelopes.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of Request from networking_requests.proto

// Ignoring public import of RequestType from networking_requests.proto

type Unknown6 struct {
	Unknown1 int32              `protobuf:"varint,1,opt,name=unknown1" json:"unknown1,omitempty"`
	Unknown2 *Unknown6_Unknown2 `protobuf:"bytes,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *Unknown6) Reset()                    { *m = Unknown6{} }
func (m *Unknown6) String() string            { return proto.CompactTextString(m) }
func (*Unknown6) ProtoMessage()               {}
func (*Unknown6) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Unknown6) GetUnknown2() *Unknown6_Unknown2 {
	if m != nil {
		return m.Unknown2
	}
	return nil
}

type Unknown6_Unknown2 struct {
	Unknown1 []byte `protobuf:"bytes,1,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
}

func (m *Unknown6_Unknown2) Reset()                    { *m = Unknown6_Unknown2{} }
func (m *Unknown6_Unknown2) String() string            { return proto.CompactTextString(m) }
func (*Unknown6_Unknown2) ProtoMessage()               {}
func (*Unknown6_Unknown2) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type AuthTicket struct {
	Start             []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	ExpireTimestampMs uint64 `protobuf:"varint,2,opt,name=expire_timestamp_ms,json=expireTimestampMs" json:"expire_timestamp_ms,omitempty"`
	End               []byte `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *AuthTicket) Reset()                    { *m = AuthTicket{} }
func (m *AuthTicket) String() string            { return proto.CompactTextString(m) }
func (*AuthTicket) ProtoMessage()               {}
func (*AuthTicket) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ResponseEnvelope struct {
	StatusCode int32             `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	RequestId  uint64            `protobuf:"varint,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ApiUrl     string            `protobuf:"bytes,3,opt,name=api_url,json=apiUrl" json:"api_url,omitempty"`
	Unknown6   *Unknown6Response `protobuf:"bytes,6,opt,name=unknown6" json:"unknown6,omitempty"`
	AuthTicket *AuthTicket       `protobuf:"bytes,7,opt,name=auth_ticket,json=authTicket" json:"auth_ticket,omitempty"`
	Returns    [][]byte          `protobuf:"bytes,100,rep,name=returns,proto3" json:"returns,omitempty"`
	Error      string            `protobuf:"bytes,101,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseEnvelope) Reset()                    { *m = ResponseEnvelope{} }
func (m *ResponseEnvelope) String() string            { return proto.CompactTextString(m) }
func (*ResponseEnvelope) ProtoMessage()               {}
func (*ResponseEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ResponseEnvelope) GetUnknown6() *Unknown6Response {
	if m != nil {
		return m.Unknown6
	}
	return nil
}

func (m *ResponseEnvelope) GetAuthTicket() *AuthTicket {
	if m != nil {
		return m.AuthTicket
	}
	return nil
}

type ResponseEnvelope_Unknown7 struct {
	Unknown71 []byte `protobuf:"bytes,1,opt,name=unknown71,proto3" json:"unknown71,omitempty"`
	Unknown72 int64  `protobuf:"varint,2,opt,name=unknown72" json:"unknown72,omitempty"`
	Unknown73 []byte `protobuf:"bytes,3,opt,name=unknown73,proto3" json:"unknown73,omitempty"`
}

func (m *ResponseEnvelope_Unknown7) Reset()                    { *m = ResponseEnvelope_Unknown7{} }
func (m *ResponseEnvelope_Unknown7) String() string            { return proto.CompactTextString(m) }
func (*ResponseEnvelope_Unknown7) ProtoMessage()               {}
func (*ResponseEnvelope_Unknown7) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type RequestEnvelope struct {
	StatusCode int32                     `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	RequestId  uint64                    `protobuf:"varint,3,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Requests   []*Request                `protobuf:"bytes,4,rep,name=requests" json:"requests,omitempty"`
	Unknown6   *Unknown6                 `protobuf:"bytes,6,opt,name=unknown6" json:"unknown6,omitempty"`
	Latitude   float64                   `protobuf:"fixed64,7,opt,name=latitude" json:"latitude,omitempty"`
	Longitude  float64                   `protobuf:"fixed64,8,opt,name=longitude" json:"longitude,omitempty"`
	Altitude   float64                   `protobuf:"fixed64,9,opt,name=altitude" json:"altitude,omitempty"`
	AuthInfo   *RequestEnvelope_AuthInfo `protobuf:"bytes,10,opt,name=auth_info,json=authInfo" json:"auth_info,omitempty"`
	AuthTicket *AuthTicket               `protobuf:"bytes,11,opt,name=auth_ticket,json=authTicket" json:"auth_ticket,omitempty"`
	Unknown12  int64                     `protobuf:"varint,12,opt,name=unknown12" json:"unknown12,omitempty"`
}

func (m *RequestEnvelope) Reset()                    { *m = RequestEnvelope{} }
func (m *RequestEnvelope) String() string            { return proto.CompactTextString(m) }
func (*RequestEnvelope) ProtoMessage()               {}
func (*RequestEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RequestEnvelope) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *RequestEnvelope) GetUnknown6() *Unknown6 {
	if m != nil {
		return m.Unknown6
	}
	return nil
}

func (m *RequestEnvelope) GetAuthInfo() *RequestEnvelope_AuthInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

func (m *RequestEnvelope) GetAuthTicket() *AuthTicket {
	if m != nil {
		return m.AuthTicket
	}
	return nil
}

type RequestEnvelope_AuthInfo struct {
	Provider string                        `protobuf:"bytes,1,opt,name=provider" json:"provider,omitempty"`
	Token    *RequestEnvelope_AuthInfo_JWT `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *RequestEnvelope_AuthInfo) Reset()                    { *m = RequestEnvelope_AuthInfo{} }
func (m *RequestEnvelope_AuthInfo) String() string            { return proto.CompactTextString(m) }
func (*RequestEnvelope_AuthInfo) ProtoMessage()               {}
func (*RequestEnvelope_AuthInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

func (m *RequestEnvelope_AuthInfo) GetToken() *RequestEnvelope_AuthInfo_JWT {
	if m != nil {
		return m.Token
	}
	return nil
}

type RequestEnvelope_AuthInfo_JWT struct {
	Contents string `protobuf:"bytes,1,opt,name=contents" json:"contents,omitempty"`
	Unknown2 int32  `protobuf:"varint,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *RequestEnvelope_AuthInfo_JWT) Reset()         { *m = RequestEnvelope_AuthInfo_JWT{} }
func (m *RequestEnvelope_AuthInfo_JWT) String() string { return proto.CompactTextString(m) }
func (*RequestEnvelope_AuthInfo_JWT) ProtoMessage()    {}
func (*RequestEnvelope_AuthInfo_JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3, 0, 0}
}

type Unknown6Response struct {
	Unknown1 int32                      `protobuf:"varint,1,opt,name=unknown1" json:"unknown1,omitempty"`
	Unknown2 *Unknown6Response_Unknown2 `protobuf:"bytes,2,opt,name=unknown2" json:"unknown2,omitempty"`
}

func (m *Unknown6Response) Reset()                    { *m = Unknown6Response{} }
func (m *Unknown6Response) String() string            { return proto.CompactTextString(m) }
func (*Unknown6Response) ProtoMessage()               {}
func (*Unknown6Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Unknown6Response) GetUnknown2() *Unknown6Response_Unknown2 {
	if m != nil {
		return m.Unknown2
	}
	return nil
}

type Unknown6Response_Unknown2 struct {
	Unknown1 uint64 `protobuf:"varint,1,opt,name=unknown1" json:"unknown1,omitempty"`
}

func (m *Unknown6Response_Unknown2) Reset()                    { *m = Unknown6Response_Unknown2{} }
func (m *Unknown6Response_Unknown2) String() string            { return proto.CompactTextString(m) }
func (*Unknown6Response_Unknown2) ProtoMessage()               {}
func (*Unknown6Response_Unknown2) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4, 0} }

func init() {
	proto.RegisterType((*Unknown6)(nil), "POGOProtos.Networking.Envelopes.Unknown6")
	proto.RegisterType((*Unknown6_Unknown2)(nil), "POGOProtos.Networking.Envelopes.Unknown6.Unknown2")
	proto.RegisterType((*AuthTicket)(nil), "POGOProtos.Networking.Envelopes.AuthTicket")
	proto.RegisterType((*ResponseEnvelope)(nil), "POGOProtos.Networking.Envelopes.ResponseEnvelope")
	proto.RegisterType((*ResponseEnvelope_Unknown7)(nil), "POGOProtos.Networking.Envelopes.ResponseEnvelope.Unknown7")
	proto.RegisterType((*RequestEnvelope)(nil), "POGOProtos.Networking.Envelopes.RequestEnvelope")
	proto.RegisterType((*RequestEnvelope_AuthInfo)(nil), "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo")
	proto.RegisterType((*RequestEnvelope_AuthInfo_JWT)(nil), "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT")
	proto.RegisterType((*Unknown6Response)(nil), "POGOProtos.Networking.Envelopes.Unknown6Response")
	proto.RegisterType((*Unknown6Response_Unknown2)(nil), "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2")
}

func init() { proto.RegisterFile("networking_envelopes.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xfe, 0xf3, 0x3b, 0x37, 0x9f, 0x54, 0x22, 0x0c, 0x48, 0x18, 0xab, 0xd0, 0x2a, 0x0b, 0x2e,
	0x42, 0xb8, 0x8a, 0x2b, 0xa5, 0x02, 0xa9, 0x0b, 0xa8, 0x2a, 0x54, 0x44, 0xdb, 0xc8, 0xa4, 0x45,
	0x62, 0x63, 0xb9, 0xf1, 0x90, 0x5a, 0x71, 0x66, 0xcc, 0x78, 0xdc, 0xf2, 0x34, 0x7d, 0x04, 0x56,
	0xac, 0x78, 0x3a, 0xc6, 0xe3, 0x19, 0x3b, 0x24, 0x82, 0xb4, 0x65, 0x77, 0x2e, 0x3e, 0xb7, 0xef,
	0x3b, 0x73, 0x0c, 0x36, 0xc1, 0xfc, 0x92, 0xb2, 0x69, 0x44, 0x26, 0x3e, 0x26, 0x17, 0x38, 0xa6,
	0x09, 0x4e, 0x9d, 0x84, 0x51, 0x4e, 0xd1, 0xc6, 0xf0, 0xf8, 0xdd, 0xf1, 0x30, 0x17, 0x53, 0xe7,
	0xa8, 0xfc, 0xcc, 0xd9, 0xd7, 0x9f, 0xd9, 0x0f, 0xe7, 0x82, 0x19, 0xfe, 0x9a, 0xe1, 0x94, 0xab,
	0xd8, 0xde, 0x55, 0x0d, 0xda, 0x27, 0x64, 0x4a, 0xe8, 0x25, 0x19, 0x20, 0x1b, 0xda, 0x59, 0x21,
	0xf7, 0xad, 0xda, 0x66, 0xed, 0x59, 0xc3, 0x2b, 0x75, 0x74, 0x54, 0xfa, 0x5c, 0xeb, 0x7f, 0xe1,
	0xeb, 0xb8, 0xae, 0xb3, 0xa2, 0xae, 0xa3, 0x13, 0x6b, 0xc1, 0x2d, 0xf3, 0xb9, 0xf6, 0x93, 0xb2,
	0xae, 0xbb, 0x54, 0x77, 0xad, 0xaa, 0xdb, 0x0b, 0x01, 0xde, 0x64, 0xfc, 0x7c, 0x14, 0x8d, 0xa7,
	0x98, 0xa3, 0xfb, 0xd0, 0x48, 0x79, 0xc0, 0xb8, 0xfa, 0xac, 0x50, 0x90, 0x03, 0xf7, 0xf0, 0xb7,
	0x24, 0x62, 0xd8, 0xe7, 0xd1, 0x4c, 0x0c, 0x17, 0xcc, 0x12, 0x7f, 0x96, 0xca, 0x36, 0xeb, 0xde,
	0xdd, 0xc2, 0x35, 0xd2, 0x9e, 0xc3, 0x14, 0x75, 0xc1, 0xc0, 0x24, 0xb4, 0x0c, 0x99, 0x23, 0x17,
	0x7b, 0x57, 0x06, 0x74, 0x3d, 0x9c, 0x26, 0x94, 0xa4, 0x58, 0xf7, 0x8f, 0x36, 0xa0, 0x23, 0x22,
	0x78, 0x96, 0xfa, 0x63, 0x1a, 0x62, 0x85, 0x08, 0x14, 0xa6, 0x3d, 0x61, 0x41, 0x8f, 0x00, 0x14,
	0x9c, 0x7e, 0x14, 0xaa, 0x72, 0xa6, 0xb2, 0x1c, 0x84, 0xe8, 0x01, 0xb4, 0x82, 0x24, 0xf2, 0x33,
	0x16, 0xcb, 0x52, 0xa6, 0xd7, 0x14, 0xea, 0x09, 0x8b, 0xd1, 0x61, 0x39, 0xef, 0xc0, 0x6a, 0x4a,
	0x2c, 0xfb, 0xd7, 0xc6, 0x52, 0x77, 0x59, 0x42, 0x34, 0x40, 0x1f, 0xa0, 0x13, 0x08, 0x88, 0xc4,
	0xf0, 0x39, 0x46, 0x56, 0x4b, 0x66, 0x7c, 0xb1, 0x32, 0x63, 0x05, 0xab, 0x07, 0x41, 0x05, 0xb1,
	0x05, 0x2d, 0x86, 0x79, 0xc6, 0x48, 0x6a, 0x85, 0x9b, 0x86, 0x00, 0x48, 0xab, 0x39, 0xf8, 0x98,
	0x31, 0xca, 0x2c, 0x2c, 0xa7, 0x29, 0x14, 0x3b, 0x2c, 0x89, 0xdc, 0x41, 0xeb, 0x60, 0xaa, 0xae,
	0x76, 0x34, 0x93, 0x95, 0x61, 0xde, 0x5b, 0xec, 0x90, 0x51, 0x79, 0xdd, 0x79, 0xef, 0xb6, 0xa2,
	0xa6, 0x32, 0xf4, 0x7e, 0x34, 0xe0, 0x8e, 0x57, 0x20, 0x7b, 0x5b, 0x7e, 0x8c, 0x45, 0x7e, 0xf6,
	0xa0, 0xad, 0x5f, 0x83, 0x55, 0x17, 0xa3, 0x76, 0xdc, 0xa7, 0x7f, 0x00, 0xcd, 0xd3, 0x8f, 0x46,
	0x09, 0x5e, 0x19, 0x88, 0xf6, 0x97, 0xb8, 0x7c, 0x7e, 0x7d, 0x2e, 0x2b, 0x0e, 0xc5, 0x13, 0x88,
	0x03, 0x1e, 0xf1, 0x4c, 0x0c, 0x92, 0x13, 0x58, 0xf3, 0x4a, 0x3d, 0x47, 0x26, 0xa6, 0x64, 0x52,
	0x38, 0xdb, 0xd2, 0x59, 0x19, 0xf2, 0xc8, 0x20, 0x56, 0x91, 0x66, 0x11, 0xa9, 0x75, 0x74, 0x0a,
	0xa6, 0xdc, 0x8c, 0x88, 0x7c, 0xa1, 0x16, 0xc8, 0xee, 0x5e, 0xad, 0xec, 0x6e, 0x01, 0x66, 0xb9,
	0x27, 0x07, 0x22, 0x81, 0xc8, 0xab, 0xa4, 0xc5, 0x8d, 0xeb, 0xfc, 0xdb, 0xc6, 0x55, 0xcc, 0xf7,
	0x5d, 0x6b, 0xed, 0xb7, 0xbd, 0xe8, 0xbb, 0xf6, 0x4f, 0x71, 0xa1, 0x74, 0x0b, 0xf9, 0xb0, 0xe2,
	0x6e, 0x5d, 0x44, 0x21, 0x66, 0x92, 0x6f, 0xd3, 0x2b, 0x75, 0xf4, 0x11, 0x1a, 0x9c, 0x4e, 0x31,
	0x51, 0xe7, 0x69, 0xf7, 0xd6, 0x83, 0x3a, 0xef, 0x3f, 0x8d, 0xbc, 0x22, 0x97, 0xbd, 0x0b, 0x86,
	0xd0, 0xf2, 0xba, 0x63, 0x4a, 0x38, 0x26, 0x62, 0x55, 0x54, 0x5d, 0xad, 0xcf, 0x5d, 0xaf, 0x62,
	0xab, 0xab, 0xab, 0xe9, 0xf6, 0xbe, 0xd7, 0xa0, 0xbb, 0xf8, 0x72, 0xff, 0x7a, 0x66, 0x4f, 0x97,
	0xce, 0xec, 0xeb, 0x1b, 0x9f, 0x86, 0x9b, 0x9e, 0xdb, 0x7a, 0x55, 0xff, 0xed, 0xe3, 0xcf, 0xeb,
	0x62, 0xaf, 0xce, 0xb3, 0x33, 0x67, 0x4c, 0x67, 0x5b, 0xc9, 0x74, 0x46, 0x26, 0xf4, 0x25, 0x0d,
	0xa3, 0x2d, 0xf9, 0xbb, 0x48, 0x87, 0xff, 0x9d, 0x35, 0xa5, 0xb4, 0xfd, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0x91, 0x86, 0x15, 0x92, 0x06, 0x00, 0x00,
}
