// Code generated by protoc-gen-go.
// source: networking_requests_messages.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of BattleAction from data_battle.proto

// Ignoring public import of BattleLog from data_battle.proto

// Ignoring public import of BattleParticipant from data_battle.proto

// Ignoring public import of BattlePokemonInfo from data_battle.proto

// Ignoring public import of BattleResults from data_battle.proto

// Ignoring public import of BattleActionType from data_battle.proto

// Ignoring public import of BattleState from data_battle.proto

// Ignoring public import of BattleType from data_battle.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of Gender from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

type AddFortModifierMessage struct {
	ModifierType    ItemId  `protobuf:"varint,1,opt,name=modifier_type,json=modifierType,enum=POGOProtos.Inventory.Item.ItemId" json:"modifier_type,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *AddFortModifierMessage) Reset()                    { *m = AddFortModifierMessage{} }
func (m *AddFortModifierMessage) String() string            { return proto.CompactTextString(m) }
func (*AddFortModifierMessage) ProtoMessage()               {}
func (*AddFortModifierMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{0} }

type AttackGymMessage struct {
	GymId                string          `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	BattleId             string          `protobuf:"bytes,2,opt,name=battle_id,json=battleId" json:"battle_id,omitempty"`
	AttackActions        []*BattleAction `protobuf:"bytes,3,rep,name=attack_actions,json=attackActions" json:"attack_actions,omitempty"`
	LastRetrievedActions *BattleAction   `protobuf:"bytes,4,opt,name=last_retrieved_actions,json=lastRetrievedActions" json:"last_retrieved_actions,omitempty"`
	PlayerLatitude       float64         `protobuf:"fixed64,5,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude      float64         `protobuf:"fixed64,6,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *AttackGymMessage) Reset()                    { *m = AttackGymMessage{} }
func (m *AttackGymMessage) String() string            { return proto.CompactTextString(m) }
func (*AttackGymMessage) ProtoMessage()               {}
func (*AttackGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{1} }

func (m *AttackGymMessage) GetAttackActions() []*BattleAction {
	if m != nil {
		return m.AttackActions
	}
	return nil
}

func (m *AttackGymMessage) GetLastRetrievedActions() *BattleAction {
	if m != nil {
		return m.LastRetrievedActions
	}
	return nil
}

type CatchPokemonMessage struct {
	EncounterId           uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	Pokeball              ItemId  `protobuf:"varint,2,opt,name=pokeball,enum=POGOProtos.Inventory.Item.ItemId" json:"pokeball,omitempty"`
	NormalizedReticleSize float64 `protobuf:"fixed64,3,opt,name=normalized_reticle_size,json=normalizedReticleSize" json:"normalized_reticle_size,omitempty"`
	SpawnPointId          string  `protobuf:"bytes,4,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
	HitPokemon            bool    `protobuf:"varint,5,opt,name=hit_pokemon,json=hitPokemon" json:"hit_pokemon,omitempty"`
	SpinModifier          float64 `protobuf:"fixed64,6,opt,name=spin_modifier,json=spinModifier" json:"spin_modifier,omitempty"`
	NormalizedHitPosition float64 `protobuf:"fixed64,7,opt,name=normalized_hit_position,json=normalizedHitPosition" json:"normalized_hit_position,omitempty"`
}

func (m *CatchPokemonMessage) Reset()                    { *m = CatchPokemonMessage{} }
func (m *CatchPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*CatchPokemonMessage) ProtoMessage()               {}
func (*CatchPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{2} }

type CheckAwardedBadgesMessage struct {
}

func (m *CheckAwardedBadgesMessage) Reset()                    { *m = CheckAwardedBadgesMessage{} }
func (m *CheckAwardedBadgesMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckAwardedBadgesMessage) ProtoMessage()               {}
func (*CheckAwardedBadgesMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{3} }

type CheckCodenameAvailableMessage struct {
	Codename string `protobuf:"bytes,1,opt,name=codename" json:"codename,omitempty"`
}

func (m *CheckCodenameAvailableMessage) Reset()                    { *m = CheckCodenameAvailableMessage{} }
func (m *CheckCodenameAvailableMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckCodenameAvailableMessage) ProtoMessage()               {}
func (*CheckCodenameAvailableMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{4} }

type ClaimCodenameMessage struct {
	Codename string `protobuf:"bytes,1,opt,name=codename" json:"codename,omitempty"`
}

func (m *ClaimCodenameMessage) Reset()                    { *m = ClaimCodenameMessage{} }
func (m *ClaimCodenameMessage) String() string            { return proto.CompactTextString(m) }
func (*ClaimCodenameMessage) ProtoMessage()               {}
func (*ClaimCodenameMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{5} }

type CollectDailyBonusMessage struct {
}

func (m *CollectDailyBonusMessage) Reset()                    { *m = CollectDailyBonusMessage{} }
func (m *CollectDailyBonusMessage) String() string            { return proto.CompactTextString(m) }
func (*CollectDailyBonusMessage) ProtoMessage()               {}
func (*CollectDailyBonusMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{6} }

type CollectDailyDefenderBonusMessage struct {
}

func (m *CollectDailyDefenderBonusMessage) Reset()         { *m = CollectDailyDefenderBonusMessage{} }
func (m *CollectDailyDefenderBonusMessage) String() string { return proto.CompactTextString(m) }
func (*CollectDailyDefenderBonusMessage) ProtoMessage()    {}
func (*CollectDailyDefenderBonusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor14, []int{7}
}

type DiskEncounterMessage struct {
	EncounterId     uint64  `protobuf:"varint,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *DiskEncounterMessage) Reset()                    { *m = DiskEncounterMessage{} }
func (m *DiskEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*DiskEncounterMessage) ProtoMessage()               {}
func (*DiskEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{8} }

type DownloadItemTemplatesMessage struct {
}

func (m *DownloadItemTemplatesMessage) Reset()                    { *m = DownloadItemTemplatesMessage{} }
func (m *DownloadItemTemplatesMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadItemTemplatesMessage) ProtoMessage()               {}
func (*DownloadItemTemplatesMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{9} }

type DownloadRemoteConfigVersionMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=POGOProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer,json=deviceManufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
}

func (m *DownloadRemoteConfigVersionMessage) Reset()         { *m = DownloadRemoteConfigVersionMessage{} }
func (m *DownloadRemoteConfigVersionMessage) String() string { return proto.CompactTextString(m) }
func (*DownloadRemoteConfigVersionMessage) ProtoMessage()    {}
func (*DownloadRemoteConfigVersionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor14, []int{10}
}

type DownloadSettingsMessage struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *DownloadSettingsMessage) Reset()                    { *m = DownloadSettingsMessage{} }
func (m *DownloadSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadSettingsMessage) ProtoMessage()               {}
func (*DownloadSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{11} }

type EchoMessage struct {
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{12} }

type EncounterMessage struct {
	EncounterId     uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointId    string  `protobuf:"bytes,2,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *EncounterMessage) Reset()                    { *m = EncounterMessage{} }
func (m *EncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*EncounterMessage) ProtoMessage()               {}
func (*EncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{13} }

type EncounterTutorialCompleteMessage struct {
	PokemonId PokemonId `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
}

func (m *EncounterTutorialCompleteMessage) Reset()         { *m = EncounterTutorialCompleteMessage{} }
func (m *EncounterTutorialCompleteMessage) String() string { return proto.CompactTextString(m) }
func (*EncounterTutorialCompleteMessage) ProtoMessage()    {}
func (*EncounterTutorialCompleteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor14, []int{14}
}

type EquipBadgeMessage struct {
	BadgeType BadgeType `protobuf:"varint,1,opt,name=badge_type,json=badgeType,enum=POGOProtos.Enums.BadgeType" json:"badge_type,omitempty"`
}

func (m *EquipBadgeMessage) Reset()                    { *m = EquipBadgeMessage{} }
func (m *EquipBadgeMessage) String() string            { return proto.CompactTextString(m) }
func (*EquipBadgeMessage) ProtoMessage()               {}
func (*EquipBadgeMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{15} }

type EvolvePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *EvolvePokemonMessage) Reset()                    { *m = EvolvePokemonMessage{} }
func (m *EvolvePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*EvolvePokemonMessage) ProtoMessage()               {}
func (*EvolvePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{16} }

type FortDeployPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *FortDeployPokemonMessage) Reset()                    { *m = FortDeployPokemonMessage{} }
func (m *FortDeployPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDeployPokemonMessage) ProtoMessage()               {}
func (*FortDeployPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{17} }

type FortDetailsMessage struct {
	FortId    string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *FortDetailsMessage) Reset()                    { *m = FortDetailsMessage{} }
func (m *FortDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDetailsMessage) ProtoMessage()               {}
func (*FortDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{18} }

type FortRecallPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *FortRecallPokemonMessage) Reset()                    { *m = FortRecallPokemonMessage{} }
func (m *FortRecallPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortRecallPokemonMessage) ProtoMessage()               {}
func (*FortRecallPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{19} }

type FortSearchMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
	FortLatitude    float64 `protobuf:"fixed64,4,opt,name=fort_latitude,json=fortLatitude" json:"fort_latitude,omitempty"`
	FortLongitude   float64 `protobuf:"fixed64,5,opt,name=fort_longitude,json=fortLongitude" json:"fort_longitude,omitempty"`
}

func (m *FortSearchMessage) Reset()                    { *m = FortSearchMessage{} }
func (m *FortSearchMessage) String() string            { return proto.CompactTextString(m) }
func (*FortSearchMessage) ProtoMessage()               {}
func (*FortSearchMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{20} }

type GetAssetDigestMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=POGOProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer,json=deviceManufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
}

func (m *GetAssetDigestMessage) Reset()                    { *m = GetAssetDigestMessage{} }
func (m *GetAssetDigestMessage) String() string            { return proto.CompactTextString(m) }
func (*GetAssetDigestMessage) ProtoMessage()               {}
func (*GetAssetDigestMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{21} }

type GetDownloadUrlsMessage struct {
	AssetId []string `protobuf:"bytes,1,rep,name=asset_id,json=assetId" json:"asset_id,omitempty"`
}

func (m *GetDownloadUrlsMessage) Reset()                    { *m = GetDownloadUrlsMessage{} }
func (m *GetDownloadUrlsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetDownloadUrlsMessage) ProtoMessage()               {}
func (*GetDownloadUrlsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{22} }

type GetGymDetailsMessage struct {
	GymId           string  `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
	GymLatitude     float64 `protobuf:"fixed64,4,opt,name=gym_latitude,json=gymLatitude" json:"gym_latitude,omitempty"`
	GymLongitude    float64 `protobuf:"fixed64,5,opt,name=gym_longitude,json=gymLongitude" json:"gym_longitude,omitempty"`
}

func (m *GetGymDetailsMessage) Reset()                    { *m = GetGymDetailsMessage{} }
func (m *GetGymDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetGymDetailsMessage) ProtoMessage()               {}
func (*GetGymDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{23} }

type GetHatchedEggsMessage struct {
}

func (m *GetHatchedEggsMessage) Reset()                    { *m = GetHatchedEggsMessage{} }
func (m *GetHatchedEggsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetHatchedEggsMessage) ProtoMessage()               {}
func (*GetHatchedEggsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{24} }

type GetIncensePokemonMessage struct {
	PlayerLatitude  float64 `protobuf:"fixed64,1,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,2,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *GetIncensePokemonMessage) Reset()                    { *m = GetIncensePokemonMessage{} }
func (m *GetIncensePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*GetIncensePokemonMessage) ProtoMessage()               {}
func (*GetIncensePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{25} }

type GetInventoryMessage struct {
	LastTimestampMs int64 `protobuf:"varint,1,opt,name=last_timestamp_ms,json=lastTimestampMs" json:"last_timestamp_ms,omitempty"`
	ItemBeenSeen    int32 `protobuf:"varint,2,opt,name=item_been_seen,json=itemBeenSeen" json:"item_been_seen,omitempty"`
}

func (m *GetInventoryMessage) Reset()                    { *m = GetInventoryMessage{} }
func (m *GetInventoryMessage) String() string            { return proto.CompactTextString(m) }
func (*GetInventoryMessage) ProtoMessage()               {}
func (*GetInventoryMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{26} }

type GetMapObjectsMessage struct {
	CellId           []uint64 `protobuf:"varint,1,rep,packed,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	SinceTimestampMs []int64  `protobuf:"varint,2,rep,packed,name=since_timestamp_ms,json=sinceTimestampMs" json:"since_timestamp_ms,omitempty"`
	Latitude         float64  `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        float64  `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *GetMapObjectsMessage) Reset()                    { *m = GetMapObjectsMessage{} }
func (m *GetMapObjectsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetMapObjectsMessage) ProtoMessage()               {}
func (*GetMapObjectsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{27} }

type GetPlayerMessage struct {
}

func (m *GetPlayerMessage) Reset()                    { *m = GetPlayerMessage{} }
func (m *GetPlayerMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerMessage) ProtoMessage()               {}
func (*GetPlayerMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{28} }

type GetPlayerProfileMessage struct {
	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *GetPlayerProfileMessage) Reset()                    { *m = GetPlayerProfileMessage{} }
func (m *GetPlayerProfileMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerProfileMessage) ProtoMessage()               {}
func (*GetPlayerProfileMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{29} }

type GetSuggestedCodenamesMessage struct {
}

func (m *GetSuggestedCodenamesMessage) Reset()                    { *m = GetSuggestedCodenamesMessage{} }
func (m *GetSuggestedCodenamesMessage) String() string            { return proto.CompactTextString(m) }
func (*GetSuggestedCodenamesMessage) ProtoMessage()               {}
func (*GetSuggestedCodenamesMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{30} }

type IncenseEncounterMessage struct {
	EncounterId       int64  `protobuf:"varint,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	EncounterLocation string `protobuf:"bytes,2,opt,name=encounter_location,json=encounterLocation" json:"encounter_location,omitempty"`
}

func (m *IncenseEncounterMessage) Reset()                    { *m = IncenseEncounterMessage{} }
func (m *IncenseEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*IncenseEncounterMessage) ProtoMessage()               {}
func (*IncenseEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{31} }

type LevelUpRewardsMessage struct {
	Level int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
}

func (m *LevelUpRewardsMessage) Reset()                    { *m = LevelUpRewardsMessage{} }
func (m *LevelUpRewardsMessage) String() string            { return proto.CompactTextString(m) }
func (*LevelUpRewardsMessage) ProtoMessage()               {}
func (*LevelUpRewardsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{32} }

type MarkTutorialCompleteMessage struct {
	TutorialsCompleted    []TutorialState `protobuf:"varint,1,rep,name=tutorials_completed,json=tutorialsCompleted,enum=POGOProtos.Enums.TutorialState" json:"tutorials_completed,omitempty"`
	SendMarketingEmails   bool            `protobuf:"varint,2,opt,name=send_marketing_emails,json=sendMarketingEmails" json:"send_marketing_emails,omitempty"`
	SendPushNotifications bool            `protobuf:"varint,3,opt,name=send_push_notifications,json=sendPushNotifications" json:"send_push_notifications,omitempty"`
}

func (m *MarkTutorialCompleteMessage) Reset()                    { *m = MarkTutorialCompleteMessage{} }
func (m *MarkTutorialCompleteMessage) String() string            { return proto.CompactTextString(m) }
func (*MarkTutorialCompleteMessage) ProtoMessage()               {}
func (*MarkTutorialCompleteMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{33} }

type NicknamePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *NicknamePokemonMessage) Reset()                    { *m = NicknamePokemonMessage{} }
func (m *NicknamePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*NicknamePokemonMessage) ProtoMessage()               {}
func (*NicknamePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{34} }

type PlayerUpdateMessage struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *PlayerUpdateMessage) Reset()                    { *m = PlayerUpdateMessage{} }
func (m *PlayerUpdateMessage) String() string            { return proto.CompactTextString(m) }
func (*PlayerUpdateMessage) ProtoMessage()               {}
func (*PlayerUpdateMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{35} }

type RecycleInventoryItemMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *RecycleInventoryItemMessage) Reset()                    { *m = RecycleInventoryItemMessage{} }
func (m *RecycleInventoryItemMessage) String() string            { return proto.CompactTextString(m) }
func (*RecycleInventoryItemMessage) ProtoMessage()               {}
func (*RecycleInventoryItemMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{36} }

type ReleasePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *ReleasePokemonMessage) Reset()                    { *m = ReleasePokemonMessage{} }
func (m *ReleasePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*ReleasePokemonMessage) ProtoMessage()               {}
func (*ReleasePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{37} }

type SetAvatarMessage struct {
	PlayerAvatar *PlayerAvatar `protobuf:"bytes,2,opt,name=player_avatar,json=playerAvatar" json:"player_avatar,omitempty"`
}

func (m *SetAvatarMessage) Reset()                    { *m = SetAvatarMessage{} }
func (m *SetAvatarMessage) String() string            { return proto.CompactTextString(m) }
func (*SetAvatarMessage) ProtoMessage()               {}
func (*SetAvatarMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{38} }

func (m *SetAvatarMessage) GetPlayerAvatar() *PlayerAvatar {
	if m != nil {
		return m.PlayerAvatar
	}
	return nil
}

type SetContactSettingsMessage struct {
	ContactSettings *ContactSettings `protobuf:"bytes,1,opt,name=contact_settings,json=contactSettings" json:"contact_settings,omitempty"`
}

func (m *SetContactSettingsMessage) Reset()                    { *m = SetContactSettingsMessage{} }
func (m *SetContactSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*SetContactSettingsMessage) ProtoMessage()               {}
func (*SetContactSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{39} }

func (m *SetContactSettingsMessage) GetContactSettings() *ContactSettings {
	if m != nil {
		return m.ContactSettings
	}
	return nil
}

type SetFavoritePokemonMessage struct {
	PokemonId  uint64 `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	IsFavorite bool   `protobuf:"varint,2,opt,name=is_favorite,json=isFavorite" json:"is_favorite,omitempty"`
}

func (m *SetFavoritePokemonMessage) Reset()                    { *m = SetFavoritePokemonMessage{} }
func (m *SetFavoritePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*SetFavoritePokemonMessage) ProtoMessage()               {}
func (*SetFavoritePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{40} }

type SetPlayerTeamMessage struct {
	Team TeamColor `protobuf:"varint,1,opt,name=team,enum=POGOProtos.Enums.TeamColor" json:"team,omitempty"`
}

func (m *SetPlayerTeamMessage) Reset()                    { *m = SetPlayerTeamMessage{} }
func (m *SetPlayerTeamMessage) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerTeamMessage) ProtoMessage()               {}
func (*SetPlayerTeamMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{41} }

type SfidaActionLogMessage struct {
}

func (m *SfidaActionLogMessage) Reset()                    { *m = SfidaActionLogMessage{} }
func (m *SfidaActionLogMessage) String() string            { return proto.CompactTextString(m) }
func (*SfidaActionLogMessage) ProtoMessage()               {}
func (*SfidaActionLogMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{42} }

type StartGymBattleMessage struct {
	GymId               string   `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	AttackingPokemonIds []uint64 `protobuf:"fixed64,2,rep,name=attacking_pokemon_ids,json=attackingPokemonIds" json:"attacking_pokemon_ids,omitempty"`
	DefendingPokemonId  uint64   `protobuf:"varint,3,opt,name=defending_pokemon_id,json=defendingPokemonId" json:"defending_pokemon_id,omitempty"`
	PlayerLatitude      float64  `protobuf:"fixed64,4,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude     float64  `protobuf:"fixed64,5,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *StartGymBattleMessage) Reset()                    { *m = StartGymBattleMessage{} }
func (m *StartGymBattleMessage) String() string            { return proto.CompactTextString(m) }
func (*StartGymBattleMessage) ProtoMessage()               {}
func (*StartGymBattleMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{43} }

type UpgradePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UpgradePokemonMessage) Reset()                    { *m = UpgradePokemonMessage{} }
func (m *UpgradePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*UpgradePokemonMessage) ProtoMessage()               {}
func (*UpgradePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{44} }

type UseIncenseMessage struct {
	IncenseType ItemId `protobuf:"varint,1,opt,name=incense_type,json=incenseType,enum=POGOProtos.Inventory.Item.ItemId" json:"incense_type,omitempty"`
}

func (m *UseIncenseMessage) Reset()                    { *m = UseIncenseMessage{} }
func (m *UseIncenseMessage) String() string            { return proto.CompactTextString(m) }
func (*UseIncenseMessage) ProtoMessage()               {}
func (*UseIncenseMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{45} }

type UseItemCaptureMessage struct {
	ItemId       ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	EncounterId  uint64 `protobuf:"fixed64,2,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointId string `protobuf:"bytes,3,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
}

func (m *UseItemCaptureMessage) Reset()                    { *m = UseItemCaptureMessage{} }
func (m *UseItemCaptureMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemCaptureMessage) ProtoMessage()               {}
func (*UseItemCaptureMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{46} }

type UseItemEggIncubatorMessage struct {
	ItemId    string `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemEggIncubatorMessage) Reset()                    { *m = UseItemEggIncubatorMessage{} }
func (m *UseItemEggIncubatorMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemEggIncubatorMessage) ProtoMessage()               {}
func (*UseItemEggIncubatorMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{47} }

type UseItemGymMessage struct {
	ItemId          ItemId  `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	GymId           string  `protobuf:"bytes,2,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *UseItemGymMessage) Reset()                    { *m = UseItemGymMessage{} }
func (m *UseItemGymMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemGymMessage) ProtoMessage()               {}
func (*UseItemGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{48} }

type UseItemPotionMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemPotionMessage) Reset()                    { *m = UseItemPotionMessage{} }
func (m *UseItemPotionMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemPotionMessage) ProtoMessage()               {}
func (*UseItemPotionMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{49} }

type UseItemReviveMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemReviveMessage) Reset()                    { *m = UseItemReviveMessage{} }
func (m *UseItemReviveMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemReviveMessage) ProtoMessage()               {}
func (*UseItemReviveMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{50} }

type UseItemXpBoostMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
}

func (m *UseItemXpBoostMessage) Reset()                    { *m = UseItemXpBoostMessage{} }
func (m *UseItemXpBoostMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemXpBoostMessage) ProtoMessage()               {}
func (*UseItemXpBoostMessage) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{51} }

func init() {
	proto.RegisterType((*AddFortModifierMessage)(nil), "POGOProtos.Networking.Requests.Messages.AddFortModifierMessage")
	proto.RegisterType((*AttackGymMessage)(nil), "POGOProtos.Networking.Requests.Messages.AttackGymMessage")
	proto.RegisterType((*CatchPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.CatchPokemonMessage")
	proto.RegisterType((*CheckAwardedBadgesMessage)(nil), "POGOProtos.Networking.Requests.Messages.CheckAwardedBadgesMessage")
	proto.RegisterType((*CheckCodenameAvailableMessage)(nil), "POGOProtos.Networking.Requests.Messages.CheckCodenameAvailableMessage")
	proto.RegisterType((*ClaimCodenameMessage)(nil), "POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage")
	proto.RegisterType((*CollectDailyBonusMessage)(nil), "POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage")
	proto.RegisterType((*CollectDailyDefenderBonusMessage)(nil), "POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage")
	proto.RegisterType((*DiskEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.DiskEncounterMessage")
	proto.RegisterType((*DownloadItemTemplatesMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessage")
	proto.RegisterType((*DownloadRemoteConfigVersionMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadRemoteConfigVersionMessage")
	proto.RegisterType((*DownloadSettingsMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadSettingsMessage")
	proto.RegisterType((*EchoMessage)(nil), "POGOProtos.Networking.Requests.Messages.EchoMessage")
	proto.RegisterType((*EncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.EncounterMessage")
	proto.RegisterType((*EncounterTutorialCompleteMessage)(nil), "POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage")
	proto.RegisterType((*EquipBadgeMessage)(nil), "POGOProtos.Networking.Requests.Messages.EquipBadgeMessage")
	proto.RegisterType((*EvolvePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.EvolvePokemonMessage")
	proto.RegisterType((*FortDeployPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortDeployPokemonMessage")
	proto.RegisterType((*FortDetailsMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortDetailsMessage")
	proto.RegisterType((*FortRecallPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortRecallPokemonMessage")
	proto.RegisterType((*FortSearchMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortSearchMessage")
	proto.RegisterType((*GetAssetDigestMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetAssetDigestMessage")
	proto.RegisterType((*GetDownloadUrlsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetDownloadUrlsMessage")
	proto.RegisterType((*GetGymDetailsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetGymDetailsMessage")
	proto.RegisterType((*GetHatchedEggsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetHatchedEggsMessage")
	proto.RegisterType((*GetIncensePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetIncensePokemonMessage")
	proto.RegisterType((*GetInventoryMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetInventoryMessage")
	proto.RegisterType((*GetMapObjectsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage")
	proto.RegisterType((*GetPlayerMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerMessage")
	proto.RegisterType((*GetPlayerProfileMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerProfileMessage")
	proto.RegisterType((*GetSuggestedCodenamesMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetSuggestedCodenamesMessage")
	proto.RegisterType((*IncenseEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.IncenseEncounterMessage")
	proto.RegisterType((*LevelUpRewardsMessage)(nil), "POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessage")
	proto.RegisterType((*MarkTutorialCompleteMessage)(nil), "POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessage")
	proto.RegisterType((*NicknamePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.NicknamePokemonMessage")
	proto.RegisterType((*PlayerUpdateMessage)(nil), "POGOProtos.Networking.Requests.Messages.PlayerUpdateMessage")
	proto.RegisterType((*RecycleInventoryItemMessage)(nil), "POGOProtos.Networking.Requests.Messages.RecycleInventoryItemMessage")
	proto.RegisterType((*ReleasePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.ReleasePokemonMessage")
	proto.RegisterType((*SetAvatarMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetAvatarMessage")
	proto.RegisterType((*SetContactSettingsMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage")
	proto.RegisterType((*SetFavoritePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetFavoritePokemonMessage")
	proto.RegisterType((*SetPlayerTeamMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage")
	proto.RegisterType((*SfidaActionLogMessage)(nil), "POGOProtos.Networking.Requests.Messages.SfidaActionLogMessage")
	proto.RegisterType((*StartGymBattleMessage)(nil), "POGOProtos.Networking.Requests.Messages.StartGymBattleMessage")
	proto.RegisterType((*UpgradePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.UpgradePokemonMessage")
	proto.RegisterType((*UseIncenseMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseIncenseMessage")
	proto.RegisterType((*UseItemCaptureMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemCaptureMessage")
	proto.RegisterType((*UseItemEggIncubatorMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemEggIncubatorMessage")
	proto.RegisterType((*UseItemGymMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemGymMessage")
	proto.RegisterType((*UseItemPotionMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemPotionMessage")
	proto.RegisterType((*UseItemReviveMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemReviveMessage")
	proto.RegisterType((*UseItemXpBoostMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemXpBoostMessage")
}

func init() { proto.RegisterFile("networking_requests_messages.proto", fileDescriptor14) }

var fileDescriptor14 = []byte{
	// 1892 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x58, 0xcb, 0x6f, 0x1c, 0x49,
	0x19, 0x67, 0x1e, 0x1e, 0xdb, 0xdf, 0xd8, 0x8e, 0xdd, 0x1e, 0x3f, 0x62, 0xef, 0xb2, 0xd9, 0x66,
	0x51, 0x16, 0xa4, 0xf5, 0x22, 0xaf, 0xc8, 0x61, 0x11, 0x07, 0xbf, 0x92, 0xb5, 0xb0, 0x93, 0x51,
	0x8f, 0x8d, 0x60, 0x11, 0xb4, 0x6a, 0xba, 0xcb, 0xe3, 0xc2, 0xfd, 0x4a, 0x57, 0xcd, 0x44, 0xe6,
	0x6f, 0x41, 0xe2, 0xc6, 0x95, 0x3b, 0x57, 0x4e, 0x48, 0x70, 0xe2, 0x08, 0x7f, 0x00, 0xfc, 0x17,
	0x7c, 0xf5, 0xea, 0xee, 0x99, 0x8c, 0xe3, 0x89, 0x42, 0x56, 0x68, 0x0f, 0x89, 0xa7, 0xbe, 0x57,
	0x7d, 0xf5, 0xbd, 0xea, 0x57, 0x0d, 0x6e, 0x42, 0xc5, 0xab, 0x34, 0xbf, 0x61, 0xc9, 0xc0, 0xcf,
	0xe9, 0xcb, 0x21, 0xe5, 0x82, 0xfb, 0x31, 0xe5, 0x9c, 0x0c, 0x28, 0xdf, 0xcb, 0xf2, 0x54, 0xa4,
	0xce, 0xe3, 0xee, 0x8b, 0x67, 0x2f, 0xba, 0xf2, 0x27, 0xdf, 0x7b, 0x5e, 0x88, 0xef, 0x79, 0x46,
	0x7c, 0xef, 0xdc, 0x88, 0xef, 0x74, 0x58, 0x32, 0xa2, 0x89, 0x48, 0xf3, 0x5b, 0x9f, 0x09, 0x1a,
	0x6b, 0xf5, 0x9d, 0xb5, 0x90, 0x08, 0xe2, 0xf7, 0x89, 0x10, 0x11, 0x35, 0xa4, 0x36, 0x4d, 0x86,
	0x31, 0x1f, 0xe3, 0x67, 0x11, 0xb9, 0xa5, 0xb9, 0x26, 0xb9, 0x7f, 0xaf, 0xc1, 0xe6, 0x41, 0x18,
	0x3e, 0x4d, 0x73, 0x71, 0x9e, 0x86, 0xec, 0x8a, 0xd1, 0xdc, 0x6c, 0xe2, 0x3c, 0x85, 0xe5, 0xd8,
	0x90, 0x7c, 0x71, 0x9b, 0xd1, 0xed, 0xda, 0xa3, 0xda, 0xa7, 0x2b, 0xfb, 0x1f, 0xef, 0x55, 0x9c,
	0x3c, 0xb5, 0x6e, 0xec, 0x9d, 0x4a, 0x37, 0xe4, 0x7f, 0xa7, 0xa1, 0xb7, 0x64, 0xf5, 0x2e, 0x50,
	0xcd, 0xd9, 0x82, 0xf9, 0x2b, 0x34, 0xef, 0xb3, 0x70, 0xbb, 0x8e, 0x16, 0x16, 0xbd, 0x96, 0x5c,
	0x9e, 0x86, 0xce, 0x63, 0x78, 0xa0, 0x7d, 0xf1, 0x23, 0x22, 0x98, 0x18, 0x86, 0x74, 0xbb, 0x81,
	0x02, 0x35, 0x6f, 0x45, 0x93, 0xcf, 0x0c, 0xd5, 0xf9, 0x01, 0xac, 0x5a, 0xc1, 0x34, 0x19, 0x68,
	0xc9, 0xa6, 0x92, 0x34, 0x06, 0xce, 0x2c, 0xd9, 0xfd, 0x4b, 0x1d, 0x56, 0x0f, 0x84, 0x20, 0xc1,
	0xcd, 0xb3, 0xdb, 0xd8, 0x9e, 0x64, 0x03, 0x5a, 0x83, 0xdb, 0x58, 0x3a, 0x50, 0x53, 0x0e, 0xcc,
	0xe1, 0x0a, 0xf7, 0xdf, 0x85, 0x45, 0x1d, 0xab, 0xd2, 0xb5, 0x05, 0x4d, 0x40, 0xe6, 0xcf, 0x60,
	0x85, 0x28, 0x3b, 0x3e, 0x09, 0x04, 0x4b, 0x13, 0x8e, 0xbe, 0x35, 0x3e, 0x6d, 0xef, 0x7f, 0x52,
	0x3d, 0xfe, 0x31, 0xc6, 0x73, 0xef, 0x50, 0xc7, 0x5b, 0xff, 0x39, 0x50, 0xc2, 0xde, 0xb2, 0xd6,
	0xd5, 0x2b, 0xee, 0x7c, 0x0d, 0x9b, 0x11, 0xe1, 0x02, 0xf3, 0x2e, 0x72, 0x46, 0x47, 0x34, 0x2c,
	0x8c, 0xca, 0x63, 0xcc, 0x6a, 0xb4, 0x23, 0x6d, 0x78, 0xd6, 0x84, 0xb5, 0x3d, 0x25, 0x8a, 0x73,
	0x33, 0x47, 0xb1, 0x35, 0x3d, 0x8a, 0xff, 0xa8, 0xc3, 0xfa, 0x11, 0x11, 0xc1, 0x75, 0x37, 0xbd,
	0xa1, 0x71, 0x9a, 0xd8, 0x40, 0x7e, 0x0c, 0x4b, 0x34, 0x09, 0xd2, 0x61, 0x22, 0xd0, 0x8a, 0x09,
	0x67, 0xcb, 0x6b, 0x17, 0x34, 0x8c, 0xdb, 0x4f, 0x61, 0x21, 0x43, 0xa5, 0x3e, 0x89, 0x22, 0x15,
	0xd3, 0x99, 0x0a, 0xa6, 0x50, 0x71, 0x9e, 0xc0, 0x56, 0x92, 0xe6, 0x31, 0x89, 0xd8, 0xef, 0x30,
	0x4a, 0x18, 0x2f, 0x16, 0x60, 0x7e, 0x38, 0xae, 0x4c, 0x6d, 0x6c, 0x94, 0x6c, 0x4f, 0x73, 0x7b,
	0xf8, 0xdb, 0xf9, 0x04, 0x56, 0x78, 0x46, 0x5e, 0x25, 0x7e, 0x96, 0xb2, 0x44, 0xd5, 0x5a, 0x53,
	0x25, 0x74, 0x49, 0x51, 0xbb, 0x92, 0x88, 0xce, 0x7d, 0x04, 0xed, 0x6b, 0x26, 0xfc, 0x4c, 0x9f,
	0x4a, 0xc5, 0x69, 0xc1, 0x03, 0x24, 0x99, 0x73, 0x3a, 0xdf, 0x83, 0x65, 0x9e, 0xb1, 0xc4, 0xb7,
	0x05, 0x6c, 0x02, 0xb4, 0x24, 0x89, 0xb6, 0x3f, 0x26, 0x7c, 0xd4, 0x06, 0x39, 0x93, 0xd9, 0xd8,
	0x9e, 0x9f, 0xf4, 0xf1, 0x2b, 0x69, 0x5b, 0x33, 0xdd, 0x5d, 0x78, 0x78, 0x74, 0x4d, 0xb1, 0x2a,
	0x5e, 0x91, 0x3c, 0xa4, 0xe1, 0x21, 0x09, 0xb1, 0x95, 0x4d, 0x68, 0xdd, 0x9f, 0xc0, 0x87, 0x8a,
	0x79, 0x94, 0x86, 0x34, 0x21, 0x31, 0x3d, 0x18, 0x11, 0x16, 0x91, 0x7e, 0x44, 0x6d, 0xec, 0x77,
	0x60, 0x21, 0x30, 0x3c, 0x53, 0xc6, 0xc5, 0xda, 0xdd, 0x87, 0xce, 0x51, 0x44, 0x58, 0x6c, 0x95,
	0x67, 0xd1, 0xd9, 0x81, 0xed, 0xa3, 0x34, 0x8a, 0x68, 0x20, 0x8e, 0x71, 0xa7, 0xdb, 0xc3, 0x34,
	0x19, 0x16, 0xce, 0xb8, 0xf0, 0xa8, 0xca, 0x3b, 0xa6, 0x57, 0x34, 0x09, 0x69, 0x3e, 0x26, 0xf3,
	0xc7, 0x1a, 0x74, 0x8e, 0x19, 0xbf, 0x39, 0xb1, 0xc9, 0x7f, 0x53, 0x91, 0x34, 0xc7, 0x8b, 0xe4,
	0x1b, 0x1d, 0x09, 0xdf, 0x85, 0x0f, 0x8e, 0xd3, 0x57, 0x49, 0x94, 0x92, 0x50, 0x96, 0xdb, 0x05,
	0x8d, 0x51, 0x42, 0x94, 0x91, 0xff, 0x4f, 0x0d, 0x5c, 0x2b, 0xe0, 0x61, 0x15, 0x08, 0x7a, 0x94,
	0x26, 0x57, 0x6c, 0xf0, 0x73, 0x9a, 0x73, 0x56, 0xd6, 0xfe, 0x13, 0x2c, 0x6c, 0xd4, 0x43, 0x47,
	0x63, 0x33, 0x09, 0x77, 0xaa, 0x85, 0x7d, 0xa2, 0xe6, 0x6c, 0xd7, 0x48, 0x78, 0x85, 0xac, 0xf3,
	0x39, 0xac, 0x87, 0x74, 0xc4, 0x02, 0xea, 0xc7, 0x24, 0x19, 0x5e, 0x61, 0xe3, 0x0f, 0x73, 0x2c,
	0x2c, 0x7d, 0x6e, 0x47, 0xb3, 0xce, 0x2b, 0x1c, 0x19, 0x3f, 0xab, 0x80, 0xb9, 0x8a, 0x54, 0x00,
	0x16, 0xbd, 0xb6, 0x91, 0x94, 0x24, 0x67, 0x13, 0x5a, 0x51, 0x1a, 0x90, 0x88, 0x9a, 0x2a, 0x37,
	0x2b, 0x59, 0xdf, 0x24, 0xcb, 0xfc, 0x91, 0xf6, 0x5c, 0xd5, 0xf7, 0xb2, 0x07, 0x48, 0x32, 0x67,
	0x71, 0x3f, 0x83, 0x2d, 0x7b, 0xd4, 0x1e, 0x15, 0x02, 0x2f, 0x17, 0x1b, 0x06, 0xc7, 0x81, 0xe6,
	0x35, 0xe1, 0xd7, 0xa6, 0x4e, 0xd4, 0x6f, 0x77, 0x19, 0xda, 0x27, 0xc1, 0x75, 0x6a, 0x23, 0xf5,
	0xa7, 0x1a, 0xac, 0xce, 0x94, 0xee, 0x89, 0x99, 0xf0, 0x7a, 0x73, 0xd6, 0xa7, 0x34, 0xe7, 0xfb,
	0xc8, 0xfd, 0x6f, 0xe0, 0x51, 0xe1, 0xf0, 0xc5, 0x10, 0xe7, 0x0e, 0x23, 0xd1, 0x51, 0x8a, 0x05,
	0x40, 0x45, 0xd1, 0x24, 0x5f, 0x02, 0x98, 0x81, 0x60, 0xdd, 0x5f, 0xd9, 0xdf, 0x9d, 0x92, 0x5a,
	0x2d, 0x83, 0xd3, 0x6a, 0x31, 0xb3, 0x3f, 0xdd, 0x17, 0xb0, 0x76, 0xf2, 0x72, 0xc8, 0x32, 0xd5,
	0xcb, 0x15, 0x83, 0x7d, 0xb9, 0xae, 0xde, 0x9a, 0x53, 0x0c, 0x2a, 0x1d, 0x79, 0x43, 0x7a, 0x8b,
	0x7d, 0xfb, 0xd3, 0xfd, 0x31, 0x74, 0x4e, 0x46, 0x69, 0x34, 0xa2, 0x13, 0x93, 0xf7, 0xc3, 0xd7,
	0x9c, 0x6c, 0x55, 0xfd, 0xc0, 0x66, 0xdc, 0x96, 0x77, 0xf8, 0x31, 0xcd, 0xa2, 0xf4, 0x76, 0x42,
	0xb7, 0xd2, 0x6d, 0xb5, 0xb1, 0x6e, 0x1b, 0x37, 0x5a, 0x57, 0x7d, 0x5a, 0x1a, 0x7d, 0x2f, 0x09,
	0x19, 0x80, 0xa3, 0xfd, 0x14, 0x38, 0x58, 0xf8, 0xbd, 0x1e, 0xe2, 0x00, 0x2b, 0xf6, 0xae, 0x2b,
	0x8b, 0xc5, 0xda, 0xf9, 0x00, 0x16, 0xcb, 0xed, 0xb4, 0x63, 0x25, 0xa1, 0x88, 0x88, 0x47, 0xb1,
	0x33, 0xa2, 0xff, 0xe3, 0x88, 0xfc, 0xad, 0x06, 0x6b, 0xd2, 0xd1, 0x1e, 0x25, 0x79, 0x70, 0x7d,
	0xaf, 0x87, 0x53, 0x5c, 0xa8, 0xcf, 0xec, 0x42, 0x63, 0xaa, 0x0b, 0xf2, 0xd6, 0x53, 0x9b, 0x15,
	0x16, 0xb5, 0xab, 0x4b, 0x92, 0x58, 0xd8, 0xfb, 0x3e, 0xac, 0x68, 0xa1, 0xc2, 0x9a, 0x86, 0x19,
	0x4a, 0xb5, 0x3c, 0xce, 0xbf, 0x6a, 0xb0, 0xf1, 0x8c, 0x8a, 0x03, 0xce, 0xa9, 0x38, 0x66, 0x78,
	0xc1, 0x89, 0x6f, 0xd5, 0x00, 0xfd, 0x02, 0x36, 0xf1, 0x74, 0x76, 0x86, 0x5e, 0xe6, 0x65, 0x0d,
	0x3f, 0x84, 0x05, 0x22, 0x0f, 0xad, 0x53, 0xd6, 0x40, 0xa3, 0xf3, 0x6a, 0x8d, 0xdd, 0xf9, 0x57,
	0xbc, 0x2a, 0x51, 0x0b, 0x11, 0xe9, 0x44, 0xdd, 0xdf, 0x01, 0x4c, 0xdf, 0x47, 0x8e, 0x31, 0x28,
	0x72, 0xab, 0x89, 0x14, 0xb7, 0x91, 0x56, 0x58, 0xc3, 0x32, 0x50, 0x22, 0x13, 0x09, 0x96, 0x7a,
	0x65, 0x7e, 0xb7, 0x54, 0x7a, 0xbf, 0x92, 0xe0, 0x90, 0x86, 0x27, 0x83, 0xe2, 0xfe, 0x70, 0x13,
	0xd8, 0x46, 0xc6, 0x69, 0x12, 0xd0, 0x84, 0x4f, 0x4e, 0xaf, 0x29, 0x07, 0xaa, 0xcd, 0x7c, 0xa0,
	0xfa, 0x5d, 0x93, 0x64, 0x5d, 0xed, 0x67, 0xf0, 0xa4, 0xdd, 0xea, 0x87, 0xb0, 0xa6, 0xa0, 0xb6,
	0x60, 0xf8, 0xb6, 0x12, 0x24, 0xce, 0xfc, 0x98, 0xab, 0xcd, 0x1a, 0xde, 0x03, 0xc9, 0xb8, 0xb0,
	0xf4, 0x73, 0x2e, 0xef, 0x25, 0xf9, 0x7a, 0xf2, 0xfb, 0x94, 0x26, 0x3e, 0xc7, 0xff, 0xd4, 0x5e,
	0x73, 0xde, 0x92, 0xa4, 0x1e, 0xe2, 0xba, 0x87, 0xff, 0xdc, 0x3f, 0xe8, 0xec, 0x9d, 0x93, 0xec,
	0x45, 0xff, 0xb7, 0x08, 0x89, 0x8a, 0xec, 0xed, 0xc2, 0x7c, 0x40, 0xa3, 0xc8, 0x26, 0xbc, 0x79,
	0x58, 0x5f, 0xad, 0x79, 0x2d, 0x49, 0xc2, 0x1c, 0xfe, 0x08, 0x1c, 0xce, 0x30, 0x18, 0xe3, 0x8e,
	0xd4, 0x51, 0xae, 0xa1, 0xe4, 0x56, 0x15, 0xb7, 0xea, 0x4d, 0x75, 0xd6, 0x35, 0xde, 0x34, 0xeb,
	0x9a, 0x93, 0xb3, 0xce, 0x81, 0x55, 0x74, 0xb0, 0xab, 0x02, 0x64, 0xd3, 0xf1, 0x25, 0x6c, 0x15,
	0x34, 0xec, 0xb0, 0x2b, 0x56, 0x22, 0x49, 0x2c, 0x72, 0x13, 0xe4, 0x0a, 0x30, 0x04, 0x4d, 0x7a,
	0x2e, 0xa1, 0x21, 0x22, 0x26, 0xd4, 0xed, 0x0d, 0x07, 0xb2, 0x7d, 0x69, 0x68, 0x51, 0x65, 0x91,
	0xea, 0x1b, 0xd8, 0x32, 0x79, 0x9e, 0x09, 0x0d, 0x34, 0xc6, 0xd1, 0xc0, 0x67, 0xe0, 0x94, 0x22,
	0xb2, 0xef, 0x14, 0x72, 0xd6, 0xed, 0xbc, 0x56, 0x70, 0xce, 0x0c, 0x03, 0x21, 0xcb, 0xc6, 0x19,
	0xbe, 0x77, 0xa2, 0xcb, 0xcc, 0xa3, 0x12, 0x38, 0x17, 0xe1, 0xef, 0xc0, 0x5c, 0x24, 0x19, 0x6a,
	0x8f, 0x39, 0x4f, 0x2f, 0xdc, 0x7f, 0xd6, 0x60, 0xf7, 0x9c, 0xe4, 0x37, 0x77, 0xdd, 0xf6, 0x5d,
	0x58, 0x17, 0x86, 0xc5, 0xfd, 0xc0, 0x30, 0x75, 0x02, 0x57, 0xf6, 0x3f, 0x7a, 0x7d, 0x20, 0x59,
	0x3b, 0x3d, 0x81, 0x98, 0xd1, 0x73, 0x0a, 0x5d, 0x6b, 0x37, 0x74, 0xf6, 0x61, 0x83, 0x23, 0x3c,
	0xc6, 0xe9, 0x94, 0xdf, 0x50, 0x09, 0xa9, 0x7c, 0x1a, 0xcb, 0x26, 0x57, 0x47, 0x5a, 0xf0, 0xd6,
	0x25, 0xf3, 0xdc, 0xf2, 0x4e, 0x14, 0x4b, 0x3e, 0x21, 0x94, 0x4e, 0x36, 0xe4, 0xd7, 0x7e, 0x92,
	0x0a, 0x7c, 0x58, 0xe8, 0xe3, 0x72, 0x95, 0xfa, 0x05, 0x4f, 0x99, 0xec, 0x22, 0xf7, 0x79, 0x95,
	0xe9, 0xf6, 0x60, 0xf3, 0x39, 0x0b, 0x6e, 0x64, 0x36, 0xde, 0x0a, 0x20, 0xc8, 0xe2, 0x4a, 0x8c,
	0xa2, 0x7d, 0xea, 0xda, 0x35, 0x82, 0x98, 0x75, 0x5d, 0x27, 0x97, 0x59, 0x48, 0x44, 0xf5, 0xf1,
	0x30, 0xd1, 0xad, 0x77, 0xd4, 0x63, 0x7d, 0xb2, 0x1e, 0x53, 0xd8, 0xc5, 0x6b, 0xf7, 0x16, 0xdf,
	0x66, 0x45, 0x7b, 0x4a, 0xe4, 0x5d, 0xe2, 0xa3, 0x79, 0xd5, 0x76, 0x05, 0xda, 0x9a, 0xe1, 0x85,
	0xd8, 0x62, 0xea, 0xaf, 0x4c, 0xba, 0x2a, 0x10, 0xd3, 0xa9, 0x7a, 0xe1, 0x3e, 0x81, 0x0d, 0x8f,
	0x46, 0x94, 0xf0, 0xb7, 0x84, 0x4d, 0xbf, 0x86, 0x55, 0x84, 0xc1, 0xf8, 0xd4, 0x12, 0xa4, 0xa8,
	0xe0, 0x53, 0x58, 0x36, 0xdd, 0x41, 0x14, 0x5d, 0xed, 0x34, 0xed, 0x89, 0xae, 0x63, 0x66, 0xfe,
	0x68, 0x1b, 0xde, 0x52, 0x56, 0x59, 0x61, 0x1c, 0x1e, 0xa2, 0x79, 0x7c, 0x4d, 0x08, 0xbc, 0x9a,
	0x26, 0xf1, 0xb6, 0x07, 0xab, 0x81, 0xe6, 0xe0, 0xe8, 0xd1, 0x2c, 0xe5, 0x60, 0x7b, 0xff, 0xf1,
	0x5d, 0x5b, 0x4d, 0x58, 0xf2, 0x1e, 0x04, 0xe3, 0x04, 0xf7, 0x57, 0x6a, 0xc3, 0xa7, 0x64, 0x84,
	0x35, 0x2a, 0xee, 0x8f, 0xc5, 0x18, 0xb6, 0xc1, 0xa9, 0xc0, 0xb8, 0x7f, 0x65, 0x74, 0x4d, 0xf1,
	0x02, 0xe3, 0xd6, 0x9a, 0xfb, 0x0c, 0x3a, 0x3d, 0x3b, 0x51, 0x2e, 0x28, 0x29, 0xd2, 0xf9, 0x39,
	0x34, 0x05, 0x2e, 0xef, 0x06, 0xba, 0x52, 0x18, 0x9f, 0x93, 0x69, 0xee, 0x29, 0x41, 0x79, 0x85,
	0xf4, 0xae, 0x58, 0x48, 0xf4, 0x17, 0x8c, 0xb3, 0x74, 0x60, 0xe7, 0xca, 0xbf, 0x11, 0x3b, 0x60,
	0x9f, 0xe5, 0xf2, 0xa6, 0xd4, 0x5f, 0x3e, 0xee, 0xb9, 0x28, 0xb1, 0xf5, 0xf4, 0x87, 0x16, 0xd9,
	0x75, 0xe5, 0xe1, 0xf4, 0x9c, 0x6d, 0x79, 0xeb, 0x05, 0xb3, 0x00, 0xef, 0x1c, 0x07, 0x73, 0x27,
	0x54, 0xef, 0xd9, 0x71, 0x1d, 0xd5, 0x77, 0x4d, 0x89, 0x27, 0x0c, 0xaf, 0xfb, 0x26, 0xd4, 0xd7,
	0x9c, 0xf9, 0xf6, 0x9a, 0x9b, 0x7e, 0x7b, 0x61, 0xc5, 0x5e, 0x66, 0x83, 0x9c, 0x84, 0x6f, 0x59,
	0xb1, 0xbf, 0x84, 0xb5, 0x4b, 0x4e, 0xcd, 0xf4, 0xb5, 0x3a, 0xc7, 0xb0, 0xc4, 0x34, 0xe5, 0x2d,
	0x3f, 0xd4, 0xb5, 0x8d, 0x9a, 0x7a, 0x7a, 0xfc, 0x1e, 0xa3, 0x2f, 0x6d, 0x23, 0xeb, 0x88, 0x64,
	0x12, 0x4a, 0xfd, 0x2f, 0x1a, 0x76, 0xf2, 0x42, 0xa8, 0xcf, 0xf2, 0x3c, 0x6c, 0xbc, 0xfe, 0x3c,
	0x74, 0x2f, 0x60, 0xc7, 0x78, 0x87, 0xa8, 0x03, 0x03, 0x30, 0xec, 0x13, 0xdc, 0xb4, 0x82, 0x97,
	0xab, 0x2e, 0x2e, 0x16, 0xfb, 0xbf, 0x19, 0xd1, 0xbb, 0x7f, 0xae, 0xe9, 0x80, 0xa2, 0x70, 0xe5,
	0x83, 0xe1, 0xbb, 0x1c, 0xb8, 0x2c, 0xd5, 0xfa, 0x3d, 0x98, 0xee, 0x9d, 0x9f, 0x0e, 0x2f, 0xa1,
	0x63, 0x7c, 0xef, 0xa6, 0xa2, 0xf2, 0xa9, 0xe2, 0x5d, 0xdc, 0xbf, 0x27, 0x5e, 0xe5, 0x96, 0x1e,
	0xc2, 0xe9, 0x11, 0xfd, 0x06, 0xb6, 0xec, 0x15, 0x65, 0xf9, 0x8b, 0xec, 0x30, 0x4d, 0xcb, 0x07,
	0xc5, 0x3b, 0xec, 0x79, 0xb8, 0xf0, 0x75, 0x4b, 0x7d, 0x00, 0xe7, 0xdd, 0xef, 0x74, 0x6b, 0xdd,
	0x7a, 0xb7, 0xd1, 0xd7, 0xeb, 0x2f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x7e, 0x26, 0x96,
	0xa8, 0x17, 0x00, 0x00,
}
