// Code generated by protoc-gen-go.
// source: networking_requests_messages.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Ignoring public import of BattlePokemonInfo from data_battle.proto

// Ignoring public import of BattleAction from data_battle.proto

// Ignoring public import of BattleLog from data_battle.proto

// Ignoring public import of BattleParticipant from data_battle.proto

// Ignoring public import of BattleResults from data_battle.proto

// Ignoring public import of BattleActionType from data_battle.proto

// Ignoring public import of BattleType from data_battle.proto

// Ignoring public import of BattleState from data_battle.proto

// Ignoring public import of EquippedBadge from data_player.proto

// Ignoring public import of ContactSettings from data_player.proto

// Ignoring public import of PlayerAvatar from data_player.proto

// Ignoring public import of PlayerStats from data_player.proto

// Ignoring public import of Currency from data_player.proto

// Ignoring public import of PlayerCurrency from data_player.proto

// Ignoring public import of PlayerCamera from data_player.proto

// Ignoring public import of PlayerPublicProfile from data_player.proto

// Ignoring public import of DailyBonus from data_player.proto

// Ignoring public import of ItemAward from inventory_item.proto

// Ignoring public import of ItemData from inventory_item.proto

// Ignoring public import of ItemType from inventory_item.proto

// Ignoring public import of ItemId from inventory_item.proto

// Ignoring public import of TutorialState from enums.proto

// Ignoring public import of CameraTarget from enums.proto

// Ignoring public import of PokemonType from enums.proto

// Ignoring public import of PokemonMove from enums.proto

// Ignoring public import of TeamColor from enums.proto

// Ignoring public import of CameraInterpolation from enums.proto

// Ignoring public import of Platform from enums.proto

// Ignoring public import of PokemonRarity from enums.proto

// Ignoring public import of PokemonMovementType from enums.proto

// Ignoring public import of BadgeType from enums.proto

// Ignoring public import of PokemonFamilyId from enums.proto

// Ignoring public import of ActivityType from enums.proto

// Ignoring public import of PokemonId from enums.proto

// Ignoring public import of ItemEffect from enums.proto

// Ignoring public import of HoloIapItemCategory from enums.proto

// Ignoring public import of ItemCategory from enums.proto

// Ignoring public import of Gender from enums.proto

type DownloadSettingsMessage struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *DownloadSettingsMessage) Reset()                    { *m = DownloadSettingsMessage{} }
func (m *DownloadSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadSettingsMessage) ProtoMessage()               {}
func (*DownloadSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

type UseItemEggIncubatorMessage struct {
	ItemId    string `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemEggIncubatorMessage) Reset()                    { *m = UseItemEggIncubatorMessage{} }
func (m *UseItemEggIncubatorMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemEggIncubatorMessage) ProtoMessage()               {}
func (*UseItemEggIncubatorMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

type AttackGymMessage struct {
	GymId                string          `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	BattleId             string          `protobuf:"bytes,2,opt,name=battle_id,json=battleId" json:"battle_id,omitempty"`
	AttackActions        []*BattleAction `protobuf:"bytes,3,rep,name=attack_actions,json=attackActions" json:"attack_actions,omitempty"`
	LastRetrievedActions *BattleAction   `protobuf:"bytes,4,opt,name=last_retrieved_actions,json=lastRetrievedActions" json:"last_retrieved_actions,omitempty"`
	PlayerLatitude       float64         `protobuf:"fixed64,5,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude      float64         `protobuf:"fixed64,6,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *AttackGymMessage) Reset()                    { *m = AttackGymMessage{} }
func (m *AttackGymMessage) String() string            { return proto.CompactTextString(m) }
func (*AttackGymMessage) ProtoMessage()               {}
func (*AttackGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{2} }

func (m *AttackGymMessage) GetAttackActions() []*BattleAction {
	if m != nil {
		return m.AttackActions
	}
	return nil
}

func (m *AttackGymMessage) GetLastRetrievedActions() *BattleAction {
	if m != nil {
		return m.LastRetrievedActions
	}
	return nil
}

type SetAvatarMessage struct {
	PlayerAvatar *PlayerAvatar `protobuf:"bytes,2,opt,name=player_avatar,json=playerAvatar" json:"player_avatar,omitempty"`
}

func (m *SetAvatarMessage) Reset()                    { *m = SetAvatarMessage{} }
func (m *SetAvatarMessage) String() string            { return proto.CompactTextString(m) }
func (*SetAvatarMessage) ProtoMessage()               {}
func (*SetAvatarMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{3} }

func (m *SetAvatarMessage) GetPlayerAvatar() *PlayerAvatar {
	if m != nil {
		return m.PlayerAvatar
	}
	return nil
}

type LevelUpRewardsMessage struct {
	Level int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
}

func (m *LevelUpRewardsMessage) Reset()                    { *m = LevelUpRewardsMessage{} }
func (m *LevelUpRewardsMessage) String() string            { return proto.CompactTextString(m) }
func (*LevelUpRewardsMessage) ProtoMessage()               {}
func (*LevelUpRewardsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{4} }

type EchoMessage struct {
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{5} }

type ClaimCodenameMessage struct {
	Codename string `protobuf:"bytes,1,opt,name=codename" json:"codename,omitempty"`
}

func (m *ClaimCodenameMessage) Reset()                    { *m = ClaimCodenameMessage{} }
func (m *ClaimCodenameMessage) String() string            { return proto.CompactTextString(m) }
func (*ClaimCodenameMessage) ProtoMessage()               {}
func (*ClaimCodenameMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{6} }

type UseItemPotionMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemPotionMessage) Reset()                    { *m = UseItemPotionMessage{} }
func (m *UseItemPotionMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemPotionMessage) ProtoMessage()               {}
func (*UseItemPotionMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{7} }

type SetContactSettingsMessage struct {
	ContactSettings *ContactSettings `protobuf:"bytes,1,opt,name=contact_settings,json=contactSettings" json:"contact_settings,omitempty"`
}

func (m *SetContactSettingsMessage) Reset()                    { *m = SetContactSettingsMessage{} }
func (m *SetContactSettingsMessage) String() string            { return proto.CompactTextString(m) }
func (*SetContactSettingsMessage) ProtoMessage()               {}
func (*SetContactSettingsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{8} }

func (m *SetContactSettingsMessage) GetContactSettings() *ContactSettings {
	if m != nil {
		return m.ContactSettings
	}
	return nil
}

type UseItemXpBoostMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
}

func (m *UseItemXpBoostMessage) Reset()                    { *m = UseItemXpBoostMessage{} }
func (m *UseItemXpBoostMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemXpBoostMessage) ProtoMessage()               {}
func (*UseItemXpBoostMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{9} }

type UseItemCaptureMessage struct {
	ItemId       ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	EncounterId  uint64 `protobuf:"fixed64,2,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointId string `protobuf:"bytes,3,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
}

func (m *UseItemCaptureMessage) Reset()                    { *m = UseItemCaptureMessage{} }
func (m *UseItemCaptureMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemCaptureMessage) ProtoMessage()               {}
func (*UseItemCaptureMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{10} }

type GetPlayerProfileMessage struct {
	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *GetPlayerProfileMessage) Reset()                    { *m = GetPlayerProfileMessage{} }
func (m *GetPlayerProfileMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerProfileMessage) ProtoMessage()               {}
func (*GetPlayerProfileMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{11} }

type GetIncensePokemonMessage struct {
	PlayerLatitude  float64 `protobuf:"fixed64,1,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,2,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *GetIncensePokemonMessage) Reset()                    { *m = GetIncensePokemonMessage{} }
func (m *GetIncensePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*GetIncensePokemonMessage) ProtoMessage()               {}
func (*GetIncensePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{12} }

type MarkTutorialCompleteMessage struct {
	TutorialsCompleted    []TutorialState `protobuf:"varint,1,rep,packed,name=tutorials_completed,json=tutorialsCompleted,enum=POGOProtos.Enums.TutorialState" json:"tutorials_completed,omitempty"`
	SendMarketingEmails   bool            `protobuf:"varint,2,opt,name=send_marketing_emails,json=sendMarketingEmails" json:"send_marketing_emails,omitempty"`
	SendPushNotifications bool            `protobuf:"varint,3,opt,name=send_push_notifications,json=sendPushNotifications" json:"send_push_notifications,omitempty"`
}

func (m *MarkTutorialCompleteMessage) Reset()                    { *m = MarkTutorialCompleteMessage{} }
func (m *MarkTutorialCompleteMessage) String() string            { return proto.CompactTextString(m) }
func (*MarkTutorialCompleteMessage) ProtoMessage()               {}
func (*MarkTutorialCompleteMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{13} }

type AddFortModifierMessage struct {
	ModifierType    ItemId  `protobuf:"varint,1,opt,name=modifier_type,json=modifierType,enum=POGOProtos.Inventory.Item.ItemId" json:"modifier_type,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *AddFortModifierMessage) Reset()                    { *m = AddFortModifierMessage{} }
func (m *AddFortModifierMessage) String() string            { return proto.CompactTextString(m) }
func (*AddFortModifierMessage) ProtoMessage()               {}
func (*AddFortModifierMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{14} }

type PlayerUpdateMessage struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *PlayerUpdateMessage) Reset()                    { *m = PlayerUpdateMessage{} }
func (m *PlayerUpdateMessage) String() string            { return proto.CompactTextString(m) }
func (*PlayerUpdateMessage) ProtoMessage()               {}
func (*PlayerUpdateMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{15} }

type FortSearchMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
	FortLatitude    float64 `protobuf:"fixed64,4,opt,name=fort_latitude,json=fortLatitude" json:"fort_latitude,omitempty"`
	FortLongitude   float64 `protobuf:"fixed64,5,opt,name=fort_longitude,json=fortLongitude" json:"fort_longitude,omitempty"`
}

func (m *FortSearchMessage) Reset()                    { *m = FortSearchMessage{} }
func (m *FortSearchMessage) String() string            { return proto.CompactTextString(m) }
func (*FortSearchMessage) ProtoMessage()               {}
func (*FortSearchMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{16} }

type EncounterMessage struct {
	EncounterId     uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	SpawnPointId    string  `protobuf:"bytes,2,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *EncounterMessage) Reset()                    { *m = EncounterMessage{} }
func (m *EncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*EncounterMessage) ProtoMessage()               {}
func (*EncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{17} }

type SfidaActionLogMessage struct {
}

func (m *SfidaActionLogMessage) Reset()                    { *m = SfidaActionLogMessage{} }
func (m *SfidaActionLogMessage) String() string            { return proto.CompactTextString(m) }
func (*SfidaActionLogMessage) ProtoMessage()               {}
func (*SfidaActionLogMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{18} }

type EquipBadgeMessage struct {
	BadgeType BadgeType `protobuf:"varint,1,opt,name=badge_type,json=badgeType,enum=POGOProtos.Enums.BadgeType" json:"badge_type,omitempty"`
}

func (m *EquipBadgeMessage) Reset()                    { *m = EquipBadgeMessage{} }
func (m *EquipBadgeMessage) String() string            { return proto.CompactTextString(m) }
func (*EquipBadgeMessage) ProtoMessage()               {}
func (*EquipBadgeMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{19} }

type FortDeployPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *FortDeployPokemonMessage) Reset()                    { *m = FortDeployPokemonMessage{} }
func (m *FortDeployPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDeployPokemonMessage) ProtoMessage()               {}
func (*FortDeployPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{20} }

type UseItemReviveMessage struct {
	ItemId    ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	PokemonId uint64 `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UseItemReviveMessage) Reset()                    { *m = UseItemReviveMessage{} }
func (m *UseItemReviveMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemReviveMessage) ProtoMessage()               {}
func (*UseItemReviveMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{21} }

type DownloadRemoteConfigVersionMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=POGOProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer,json=deviceManufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
}

func (m *DownloadRemoteConfigVersionMessage) Reset()         { *m = DownloadRemoteConfigVersionMessage{} }
func (m *DownloadRemoteConfigVersionMessage) String() string { return proto.CompactTextString(m) }
func (*DownloadRemoteConfigVersionMessage) ProtoMessage()    {}
func (*DownloadRemoteConfigVersionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor11, []int{22}
}

type StartGymBattleMessage struct {
	GymId               string   `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	AttackingPokemonIds []uint64 `protobuf:"fixed64,2,rep,packed,name=attacking_pokemon_ids,json=attackingPokemonIds" json:"attacking_pokemon_ids,omitempty"`
	DefendingPokemonId  uint64   `protobuf:"fixed64,3,opt,name=defending_pokemon_id,json=defendingPokemonId" json:"defending_pokemon_id,omitempty"`
	PlayerLatitude      float64  `protobuf:"fixed64,4,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude     float64  `protobuf:"fixed64,5,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *StartGymBattleMessage) Reset()                    { *m = StartGymBattleMessage{} }
func (m *StartGymBattleMessage) String() string            { return proto.CompactTextString(m) }
func (*StartGymBattleMessage) ProtoMessage()               {}
func (*StartGymBattleMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{23} }

type IncenseEncounterMessage struct {
	EncounterId       uint64 `protobuf:"varint,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	EncounterLocation string `protobuf:"bytes,2,opt,name=encounter_location,json=encounterLocation" json:"encounter_location,omitempty"`
}

func (m *IncenseEncounterMessage) Reset()                    { *m = IncenseEncounterMessage{} }
func (m *IncenseEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*IncenseEncounterMessage) ProtoMessage()               {}
func (*IncenseEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{24} }

type CheckAwardedBadgesMessage struct {
}

func (m *CheckAwardedBadgesMessage) Reset()                    { *m = CheckAwardedBadgesMessage{} }
func (m *CheckAwardedBadgesMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckAwardedBadgesMessage) ProtoMessage()               {}
func (*CheckAwardedBadgesMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{25} }

type UseIncenseMessage struct {
	IncenseType ItemId `protobuf:"varint,1,opt,name=incense_type,json=incenseType,enum=POGOProtos.Inventory.Item.ItemId" json:"incense_type,omitempty"`
}

func (m *UseIncenseMessage) Reset()                    { *m = UseIncenseMessage{} }
func (m *UseIncenseMessage) String() string            { return proto.CompactTextString(m) }
func (*UseIncenseMessage) ProtoMessage()               {}
func (*UseIncenseMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{26} }

type DownloadItemTemplatesMessage struct {
}

func (m *DownloadItemTemplatesMessage) Reset()                    { *m = DownloadItemTemplatesMessage{} }
func (m *DownloadItemTemplatesMessage) String() string            { return proto.CompactTextString(m) }
func (*DownloadItemTemplatesMessage) ProtoMessage()               {}
func (*DownloadItemTemplatesMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{27} }

type SetPlayerTeamMessage struct {
	Team TeamColor `protobuf:"varint,1,opt,name=team,enum=POGOProtos.Enums.TeamColor" json:"team,omitempty"`
}

func (m *SetPlayerTeamMessage) Reset()                    { *m = SetPlayerTeamMessage{} }
func (m *SetPlayerTeamMessage) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerTeamMessage) ProtoMessage()               {}
func (*SetPlayerTeamMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{28} }

type CatchPokemonMessage struct {
	EncounterId           uint64  `protobuf:"fixed64,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	Pokeball              ItemId  `protobuf:"varint,2,opt,name=pokeball,enum=POGOProtos.Inventory.Item.ItemId" json:"pokeball,omitempty"`
	NormalizedReticleSize float64 `protobuf:"fixed64,3,opt,name=normalized_reticle_size,json=normalizedReticleSize" json:"normalized_reticle_size,omitempty"`
	SpawnPointId          string  `protobuf:"bytes,4,opt,name=spawn_point_id,json=spawnPointId" json:"spawn_point_id,omitempty"`
	HitPokemon            bool    `protobuf:"varint,5,opt,name=hit_pokemon,json=hitPokemon" json:"hit_pokemon,omitempty"`
	SpinModifier          float64 `protobuf:"fixed64,6,opt,name=spin_modifier,json=spinModifier" json:"spin_modifier,omitempty"`
	NormalizedHitPosition float64 `protobuf:"fixed64,7,opt,name=normalized_hit_position,json=normalizedHitPosition" json:"normalized_hit_position,omitempty"`
}

func (m *CatchPokemonMessage) Reset()                    { *m = CatchPokemonMessage{} }
func (m *CatchPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*CatchPokemonMessage) ProtoMessage()               {}
func (*CatchPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{29} }

type NicknamePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *NicknamePokemonMessage) Reset()                    { *m = NicknamePokemonMessage{} }
func (m *NicknamePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*NicknamePokemonMessage) ProtoMessage()               {}
func (*NicknamePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{30} }

type CheckCodenameAvailableMessage struct {
	Codename string `protobuf:"bytes,1,opt,name=codename" json:"codename,omitempty"`
}

func (m *CheckCodenameAvailableMessage) Reset()                    { *m = CheckCodenameAvailableMessage{} }
func (m *CheckCodenameAvailableMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckCodenameAvailableMessage) ProtoMessage()               {}
func (*CheckCodenameAvailableMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{31} }

type GetHatchedEggsMessage struct {
}

func (m *GetHatchedEggsMessage) Reset()                    { *m = GetHatchedEggsMessage{} }
func (m *GetHatchedEggsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetHatchedEggsMessage) ProtoMessage()               {}
func (*GetHatchedEggsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{32} }

type CollectDailyDefenderBonusMessage struct {
}

func (m *CollectDailyDefenderBonusMessage) Reset()         { *m = CollectDailyDefenderBonusMessage{} }
func (m *CollectDailyDefenderBonusMessage) String() string { return proto.CompactTextString(m) }
func (*CollectDailyDefenderBonusMessage) ProtoMessage()    {}
func (*CollectDailyDefenderBonusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor11, []int{33}
}

type EncounterTutorialCompleteMessage struct {
	PokemonId PokemonId `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId,enum=POGOProtos.Enums.PokemonId" json:"pokemon_id,omitempty"`
}

func (m *EncounterTutorialCompleteMessage) Reset()         { *m = EncounterTutorialCompleteMessage{} }
func (m *EncounterTutorialCompleteMessage) String() string { return proto.CompactTextString(m) }
func (*EncounterTutorialCompleteMessage) ProtoMessage()    {}
func (*EncounterTutorialCompleteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor11, []int{34}
}

type UpgradePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *UpgradePokemonMessage) Reset()                    { *m = UpgradePokemonMessage{} }
func (m *UpgradePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*UpgradePokemonMessage) ProtoMessage()               {}
func (*UpgradePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{35} }

type GetSuggestedCodenamesMessage struct {
}

func (m *GetSuggestedCodenamesMessage) Reset()                    { *m = GetSuggestedCodenamesMessage{} }
func (m *GetSuggestedCodenamesMessage) String() string            { return proto.CompactTextString(m) }
func (*GetSuggestedCodenamesMessage) ProtoMessage()               {}
func (*GetSuggestedCodenamesMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{36} }

type DiskEncounterMessage struct {
	EncounterId     uint64  `protobuf:"varint,1,opt,name=encounter_id,json=encounterId" json:"encounter_id,omitempty"`
	FortId          string  `protobuf:"bytes,2,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *DiskEncounterMessage) Reset()                    { *m = DiskEncounterMessage{} }
func (m *DiskEncounterMessage) String() string            { return proto.CompactTextString(m) }
func (*DiskEncounterMessage) ProtoMessage()               {}
func (*DiskEncounterMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{37} }

type FortDetailsMessage struct {
	FortId    string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *FortDetailsMessage) Reset()                    { *m = FortDetailsMessage{} }
func (m *FortDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*FortDetailsMessage) ProtoMessage()               {}
func (*FortDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{38} }

type RecycleInventoryItemMessage struct {
	ItemId ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *RecycleInventoryItemMessage) Reset()                    { *m = RecycleInventoryItemMessage{} }
func (m *RecycleInventoryItemMessage) String() string            { return proto.CompactTextString(m) }
func (*RecycleInventoryItemMessage) ProtoMessage()               {}
func (*RecycleInventoryItemMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{39} }

type GetInventoryMessage struct {
	LastTimestampMs int64 `protobuf:"varint,1,opt,name=last_timestamp_ms,json=lastTimestampMs" json:"last_timestamp_ms,omitempty"`
	ItemBeenSeen    int32 `protobuf:"varint,2,opt,name=item_been_seen,json=itemBeenSeen" json:"item_been_seen,omitempty"`
}

func (m *GetInventoryMessage) Reset()                    { *m = GetInventoryMessage{} }
func (m *GetInventoryMessage) String() string            { return proto.CompactTextString(m) }
func (*GetInventoryMessage) ProtoMessage()               {}
func (*GetInventoryMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{40} }

type FortRecallPokemonMessage struct {
	FortId          string  `protobuf:"bytes,1,opt,name=fort_id,json=fortId" json:"fort_id,omitempty"`
	PokemonId       uint64  `protobuf:"fixed64,2,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *FortRecallPokemonMessage) Reset()                    { *m = FortRecallPokemonMessage{} }
func (m *FortRecallPokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*FortRecallPokemonMessage) ProtoMessage()               {}
func (*FortRecallPokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{41} }

type ReleasePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *ReleasePokemonMessage) Reset()                    { *m = ReleasePokemonMessage{} }
func (m *ReleasePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*ReleasePokemonMessage) ProtoMessage()               {}
func (*ReleasePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{42} }

type GetMapObjectsMessage struct {
	CellId           []uint64 `protobuf:"varint,1,rep,packed,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	SinceTimestampMs []int64  `protobuf:"varint,2,rep,packed,name=since_timestamp_ms,json=sinceTimestampMs" json:"since_timestamp_ms,omitempty"`
	Latitude         float64  `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        float64  `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *GetMapObjectsMessage) Reset()                    { *m = GetMapObjectsMessage{} }
func (m *GetMapObjectsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetMapObjectsMessage) ProtoMessage()               {}
func (*GetMapObjectsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{43} }

type GetGymDetailsMessage struct {
	GymId           string  `protobuf:"bytes,1,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,2,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,3,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
	GymLatitude     float64 `protobuf:"fixed64,4,opt,name=gym_latitude,json=gymLatitude" json:"gym_latitude,omitempty"`
	GymLongitude    float64 `protobuf:"fixed64,5,opt,name=gym_longitude,json=gymLongitude" json:"gym_longitude,omitempty"`
	ClientVersion   string  `protobuf:"bytes,6,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
}

func (m *GetGymDetailsMessage) Reset()                    { *m = GetGymDetailsMessage{} }
func (m *GetGymDetailsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetGymDetailsMessage) ProtoMessage()               {}
func (*GetGymDetailsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{44} }

type GetPlayerMessage struct {
}

func (m *GetPlayerMessage) Reset()                    { *m = GetPlayerMessage{} }
func (m *GetPlayerMessage) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerMessage) ProtoMessage()               {}
func (*GetPlayerMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{45} }

type CollectDailyBonusMessage struct {
}

func (m *CollectDailyBonusMessage) Reset()                    { *m = CollectDailyBonusMessage{} }
func (m *CollectDailyBonusMessage) String() string            { return proto.CompactTextString(m) }
func (*CollectDailyBonusMessage) ProtoMessage()               {}
func (*CollectDailyBonusMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{46} }

type GetDownloadUrlsMessage struct {
	AssetId []string `protobuf:"bytes,1,rep,name=asset_id,json=assetId" json:"asset_id,omitempty"`
}

func (m *GetDownloadUrlsMessage) Reset()                    { *m = GetDownloadUrlsMessage{} }
func (m *GetDownloadUrlsMessage) String() string            { return proto.CompactTextString(m) }
func (*GetDownloadUrlsMessage) ProtoMessage()               {}
func (*GetDownloadUrlsMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{47} }

type SetFavoritePokemonMessage struct {
	PokemonId  int64 `protobuf:"varint,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	IsFavorite bool  `protobuf:"varint,2,opt,name=is_favorite,json=isFavorite" json:"is_favorite,omitempty"`
}

func (m *SetFavoritePokemonMessage) Reset()                    { *m = SetFavoritePokemonMessage{} }
func (m *SetFavoritePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*SetFavoritePokemonMessage) ProtoMessage()               {}
func (*SetFavoritePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{48} }

type UseItemGymMessage struct {
	ItemId          ItemId  `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	GymId           string  `protobuf:"bytes,2,opt,name=gym_id,json=gymId" json:"gym_id,omitempty"`
	PlayerLatitude  float64 `protobuf:"fixed64,3,opt,name=player_latitude,json=playerLatitude" json:"player_latitude,omitempty"`
	PlayerLongitude float64 `protobuf:"fixed64,4,opt,name=player_longitude,json=playerLongitude" json:"player_longitude,omitempty"`
}

func (m *UseItemGymMessage) Reset()                    { *m = UseItemGymMessage{} }
func (m *UseItemGymMessage) String() string            { return proto.CompactTextString(m) }
func (*UseItemGymMessage) ProtoMessage()               {}
func (*UseItemGymMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{49} }

type GetAssetDigestMessage struct {
	Platform           Platform `protobuf:"varint,1,opt,name=platform,enum=POGOProtos.Enums.Platform" json:"platform,omitempty"`
	DeviceManufacturer string   `protobuf:"bytes,2,opt,name=device_manufacturer,json=deviceManufacturer" json:"device_manufacturer,omitempty"`
	DeviceModel        string   `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty"`
	Locale             string   `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	AppVersion         uint32   `protobuf:"varint,5,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
}

func (m *GetAssetDigestMessage) Reset()                    { *m = GetAssetDigestMessage{} }
func (m *GetAssetDigestMessage) String() string            { return proto.CompactTextString(m) }
func (*GetAssetDigestMessage) ProtoMessage()               {}
func (*GetAssetDigestMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{50} }

type EvolvePokemonMessage struct {
	PokemonId uint64 `protobuf:"fixed64,1,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
}

func (m *EvolvePokemonMessage) Reset()                    { *m = EvolvePokemonMessage{} }
func (m *EvolvePokemonMessage) String() string            { return proto.CompactTextString(m) }
func (*EvolvePokemonMessage) ProtoMessage()               {}
func (*EvolvePokemonMessage) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{51} }

func init() {
	proto.RegisterType((*DownloadSettingsMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadSettingsMessage")
	proto.RegisterType((*UseItemEggIncubatorMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemEggIncubatorMessage")
	proto.RegisterType((*AttackGymMessage)(nil), "POGOProtos.Networking.Requests.Messages.AttackGymMessage")
	proto.RegisterType((*SetAvatarMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetAvatarMessage")
	proto.RegisterType((*LevelUpRewardsMessage)(nil), "POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessage")
	proto.RegisterType((*EchoMessage)(nil), "POGOProtos.Networking.Requests.Messages.EchoMessage")
	proto.RegisterType((*ClaimCodenameMessage)(nil), "POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage")
	proto.RegisterType((*UseItemPotionMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemPotionMessage")
	proto.RegisterType((*SetContactSettingsMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage")
	proto.RegisterType((*UseItemXpBoostMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemXpBoostMessage")
	proto.RegisterType((*UseItemCaptureMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemCaptureMessage")
	proto.RegisterType((*GetPlayerProfileMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerProfileMessage")
	proto.RegisterType((*GetIncensePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetIncensePokemonMessage")
	proto.RegisterType((*MarkTutorialCompleteMessage)(nil), "POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessage")
	proto.RegisterType((*AddFortModifierMessage)(nil), "POGOProtos.Networking.Requests.Messages.AddFortModifierMessage")
	proto.RegisterType((*PlayerUpdateMessage)(nil), "POGOProtos.Networking.Requests.Messages.PlayerUpdateMessage")
	proto.RegisterType((*FortSearchMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortSearchMessage")
	proto.RegisterType((*EncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.EncounterMessage")
	proto.RegisterType((*SfidaActionLogMessage)(nil), "POGOProtos.Networking.Requests.Messages.SfidaActionLogMessage")
	proto.RegisterType((*EquipBadgeMessage)(nil), "POGOProtos.Networking.Requests.Messages.EquipBadgeMessage")
	proto.RegisterType((*FortDeployPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortDeployPokemonMessage")
	proto.RegisterType((*UseItemReviveMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemReviveMessage")
	proto.RegisterType((*DownloadRemoteConfigVersionMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadRemoteConfigVersionMessage")
	proto.RegisterType((*StartGymBattleMessage)(nil), "POGOProtos.Networking.Requests.Messages.StartGymBattleMessage")
	proto.RegisterType((*IncenseEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.IncenseEncounterMessage")
	proto.RegisterType((*CheckAwardedBadgesMessage)(nil), "POGOProtos.Networking.Requests.Messages.CheckAwardedBadgesMessage")
	proto.RegisterType((*UseIncenseMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseIncenseMessage")
	proto.RegisterType((*DownloadItemTemplatesMessage)(nil), "POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessage")
	proto.RegisterType((*SetPlayerTeamMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage")
	proto.RegisterType((*CatchPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.CatchPokemonMessage")
	proto.RegisterType((*NicknamePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.NicknamePokemonMessage")
	proto.RegisterType((*CheckCodenameAvailableMessage)(nil), "POGOProtos.Networking.Requests.Messages.CheckCodenameAvailableMessage")
	proto.RegisterType((*GetHatchedEggsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetHatchedEggsMessage")
	proto.RegisterType((*CollectDailyDefenderBonusMessage)(nil), "POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage")
	proto.RegisterType((*EncounterTutorialCompleteMessage)(nil), "POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage")
	proto.RegisterType((*UpgradePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.UpgradePokemonMessage")
	proto.RegisterType((*GetSuggestedCodenamesMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetSuggestedCodenamesMessage")
	proto.RegisterType((*DiskEncounterMessage)(nil), "POGOProtos.Networking.Requests.Messages.DiskEncounterMessage")
	proto.RegisterType((*FortDetailsMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortDetailsMessage")
	proto.RegisterType((*RecycleInventoryItemMessage)(nil), "POGOProtos.Networking.Requests.Messages.RecycleInventoryItemMessage")
	proto.RegisterType((*GetInventoryMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetInventoryMessage")
	proto.RegisterType((*FortRecallPokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.FortRecallPokemonMessage")
	proto.RegisterType((*ReleasePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.ReleasePokemonMessage")
	proto.RegisterType((*GetMapObjectsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage")
	proto.RegisterType((*GetGymDetailsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetGymDetailsMessage")
	proto.RegisterType((*GetPlayerMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetPlayerMessage")
	proto.RegisterType((*CollectDailyBonusMessage)(nil), "POGOProtos.Networking.Requests.Messages.CollectDailyBonusMessage")
	proto.RegisterType((*GetDownloadUrlsMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetDownloadUrlsMessage")
	proto.RegisterType((*SetFavoritePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.SetFavoritePokemonMessage")
	proto.RegisterType((*UseItemGymMessage)(nil), "POGOProtos.Networking.Requests.Messages.UseItemGymMessage")
	proto.RegisterType((*GetAssetDigestMessage)(nil), "POGOProtos.Networking.Requests.Messages.GetAssetDigestMessage")
	proto.RegisterType((*EvolvePokemonMessage)(nil), "POGOProtos.Networking.Requests.Messages.EvolvePokemonMessage")
}

func init() { proto.RegisterFile("networking_requests_messages.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 1908 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xdc, 0x58, 0x4f, 0x53, 0x1b, 0xc9,
	0x15, 0xcf, 0x48, 0x42, 0x86, 0x27, 0x60, 0x61, 0x90, 0x0c, 0x86, 0xdd, 0x18, 0xcf, 0xee, 0x96,
	0x49, 0xaa, 0xcc, 0x6e, 0xb1, 0x15, 0x1f, 0x9c, 0xca, 0x01, 0x04, 0xd6, 0xaa, 0x62, 0x8c, 0x6a,
	0x04, 0xa9, 0x64, 0x53, 0xc9, 0x54, 0x33, 0xf3, 0x24, 0x75, 0x98, 0x99, 0x1e, 0xcf, 0xb4, 0xe4,
	0x92, 0x3f, 0x4b, 0xaa, 0x72, 0xdb, 0x6b, 0xee, 0xb9, 0xe6, 0x9a, 0x9c, 0x72, 0x4c, 0x3e, 0x40,
	0x72, 0xcb, 0x47, 0x48, 0xf5, 0xbf, 0xd1, 0x20, 0x0b, 0x90, 0xb3, 0xf6, 0x56, 0x2a, 0x17, 0x50,
	0xbf, 0x7f, 0xdd, 0xfd, 0xde, 0xef, 0xfd, 0xe9, 0x01, 0x27, 0x46, 0xfe, 0x9a, 0xa5, 0x57, 0x34,
	0xee, 0x7b, 0x29, 0xbe, 0x1a, 0x62, 0xc6, 0x33, 0x2f, 0xc2, 0x2c, 0x23, 0x7d, 0xcc, 0xf6, 0x93,
	0x94, 0x71, 0x66, 0x3f, 0xee, 0x9c, 0xb5, 0xce, 0x3a, 0xe2, 0x67, 0xb6, 0xff, 0x32, 0x17, 0xdf,
	0x77, 0xb5, 0xf8, 0xfe, 0xa9, 0x16, 0xdf, 0x5e, 0x0f, 0x08, 0x27, 0xde, 0x25, 0xe1, 0x3c, 0x44,
	0xa5, 0xab, 0x49, 0x49, 0x48, 0xc6, 0x98, 0x6a, 0x52, 0x9d, 0xc6, 0x23, 0x8c, 0x39, 0x4b, 0xc7,
	0x1e, 0xe5, 0x18, 0x69, 0x6a, 0x0d, 0xe3, 0x61, 0xa4, 0x77, 0x74, 0x9e, 0xc0, 0xe6, 0x31, 0x7b,
	0x1d, 0x87, 0x8c, 0x04, 0x5d, 0xe4, 0x9c, 0xc6, 0xfd, 0x4c, 0x6f, 0x62, 0xdb, 0x50, 0x19, 0x90,
	0x6c, 0xb0, 0x65, 0xed, 0x5a, 0x7b, 0x4b, 0xae, 0xfc, 0xed, 0x9c, 0xc3, 0xf6, 0x45, 0x86, 0x6d,
	0x8e, 0xd1, 0x49, 0xbf, 0xdf, 0x8e, 0xfd, 0xe1, 0x25, 0xe1, 0x2c, 0x35, 0x1a, 0x9b, 0x70, 0x4f,
	0xec, 0xe3, 0xd1, 0x40, 0x2b, 0x55, 0xc5, 0xb2, 0x1d, 0xd8, 0x9f, 0x00, 0x24, 0xec, 0x0a, 0x23,
	0x16, 0x0b, 0x5e, 0x69, 0xd7, 0xda, 0xab, 0xb8, 0x4b, 0x9a, 0xd2, 0x0e, 0x9c, 0x3f, 0x97, 0x60,
	0xed, 0x90, 0x73, 0xe2, 0x5f, 0xb5, 0xc6, 0x91, 0x31, 0xd6, 0x80, 0x6a, 0x7f, 0x5c, 0xb0, 0xb5,
	0xd0, 0x1f, 0x0b, 0x53, 0x3b, 0xb0, 0xa4, 0xae, 0x6d, 0x2c, 0x2d, 0xb9, 0x8b, 0x8a, 0xd0, 0x0e,
	0xec, 0x9f, 0xc3, 0x2a, 0x91, 0x76, 0x3c, 0xe2, 0x73, 0xca, 0xe2, 0x6c, 0xab, 0xbc, 0x5b, 0xde,
	0xab, 0x1d, 0x7c, 0xb6, 0x5f, 0x70, 0xec, 0x31, 0xe1, 0x64, 0xff, 0x48, 0xb9, 0x4e, 0xfd, 0x3b,
	0x94, 0xc2, 0xee, 0x8a, 0xd2, 0x55, 0xab, 0xcc, 0xfe, 0x06, 0xee, 0x87, 0x24, 0xe3, 0x5e, 0x8a,
	0x3c, 0xa5, 0x38, 0xc2, 0x20, 0x37, 0x5a, 0xd9, 0xb5, 0xe6, 0x36, 0x5a, 0x17, 0x36, 0x5c, 0x63,
	0xc2, 0xd8, 0x7e, 0x0c, 0x1f, 0xa9, 0x48, 0x79, 0x21, 0xe1, 0x94, 0x0f, 0x03, 0xdc, 0x5a, 0xd8,
	0xb5, 0xf6, 0x2c, 0x77, 0x55, 0x91, 0x5f, 0x68, 0xaa, 0xfd, 0x23, 0x58, 0x33, 0x82, 0x2c, 0xee,
	0x2b, 0xc9, 0xaa, 0x94, 0xd4, 0x06, 0x5e, 0x18, 0xb2, 0xf3, 0x1b, 0x58, 0xeb, 0x22, 0x3f, 0x1c,
	0x11, 0x4e, 0xf2, 0x88, 0xb4, 0x61, 0x45, 0xab, 0x13, 0x49, 0x97, 0x1e, 0x9b, 0x75, 0xf4, 0x8e,
	0xc2, 0x8d, 0xfa, 0xa7, 0x6c, 0xb8, 0xcb, 0x49, 0x61, 0xe5, 0x3c, 0x81, 0xc6, 0x0b, 0x1c, 0x61,
	0x78, 0x91, 0xb8, 0xf8, 0x9a, 0xa4, 0x41, 0x8e, 0x93, 0x3a, 0x2c, 0x84, 0x82, 0x21, 0xe3, 0xb4,
	0xe0, 0xaa, 0x85, 0xb3, 0x02, 0xb5, 0x13, 0x7f, 0xc0, 0xb4, 0x90, 0x73, 0x00, 0xf5, 0x66, 0x48,
	0x68, 0xd4, 0x64, 0x01, 0xc6, 0x24, 0x42, 0xa3, 0xbc, 0x0d, 0x8b, 0xbe, 0x26, 0xe9, 0x38, 0xe7,
	0x6b, 0xe7, 0x15, 0xd4, 0x35, 0xd8, 0x3a, 0x4c, 0xb8, 0xcd, 0xe8, 0x3c, 0xbb, 0x0e, 0xb3, 0xd5,
	0x83, 0x47, 0xc5, 0xeb, 0xb4, 0x0d, 0xe6, 0xf7, 0x85, 0xa6, 0xfc, 0xd3, 0x0e, 0x6e, 0x41, 0x62,
	0xb5, 0x88, 0x44, 0x06, 0x0f, 0xba, 0xc8, 0x9b, 0x2c, 0xe6, 0xc4, 0xe7, 0xd3, 0x09, 0xe1, 0xc2,
	0x9a, 0xaf, 0x38, 0x5e, 0xa6, 0x59, 0xf2, 0x00, 0xb5, 0x83, 0xc7, 0x37, 0xf9, 0x73, 0xca, 0x92,
	0xfb, 0x91, 0x7f, 0x9d, 0xe0, 0x74, 0xa1, 0xa1, 0xef, 0xf8, 0xcb, 0xe4, 0x88, 0xb1, 0x8c, 0xbf,
	0x87, 0x4b, 0x3a, 0xbf, 0xb7, 0x72, 0xab, 0x4d, 0x92, 0xf0, 0x61, 0x8a, 0xef, 0xc3, 0x75, 0x8f,
	0x60, 0x19, 0x63, 0x9f, 0x0d, 0x63, 0x8e, 0xe9, 0xc4, 0x79, 0xb5, 0x9c, 0xd6, 0x0e, 0xec, 0xcf,
	0x60, 0x35, 0x4b, 0xc8, 0xeb, 0xd8, 0x4b, 0x18, 0x8d, 0xb9, 0x10, 0x2a, 0xcb, 0x98, 0x2e, 0x4b,
	0x6a, 0x47, 0x10, 0xdb, 0x81, 0xf3, 0x0c, 0x36, 0x5b, 0xc8, 0x95, 0x87, 0x3a, 0x29, 0xeb, 0xd1,
	0x30, 0x3f, 0xdf, 0x43, 0xa8, 0x69, 0xbc, 0x16, 0x10, 0x01, 0x8a, 0xf4, 0x52, 0x60, 0x22, 0x86,
	0xad, 0x16, 0xf2, 0x76, 0xec, 0x63, 0x9c, 0x61, 0x47, 0xc5, 0xcd, 0x28, 0xcf, 0x48, 0x2a, 0x6b,
	0xee, 0xa4, 0x2a, 0xcd, 0x4e, 0xaa, 0xbf, 0x5b, 0xb0, 0x73, 0x4a, 0xd2, 0xab, 0xf3, 0x21, 0x67,
	0x29, 0x25, 0x61, 0x93, 0x45, 0x49, 0x88, 0x3c, 0x3f, 0x70, 0x07, 0x36, 0xb8, 0x66, 0x65, 0x9e,
	0xaf, 0x99, 0xc2, 0xb9, 0xe5, 0xbd, 0xd5, 0x83, 0x87, 0x45, 0xe7, 0x9e, 0xc8, 0xaa, 0x6b, 0xec,
	0x74, 0x39, 0xe1, 0xe8, 0xda, 0xb9, 0xae, 0xb1, 0x1b, 0xd8, 0x07, 0xd0, 0xc8, 0x30, 0x0e, 0xbc,
	0x88, 0xa4, 0x57, 0x28, 0x40, 0xe2, 0x61, 0x44, 0x68, 0x98, 0xc9, 0x13, 0x2e, 0xba, 0x1b, 0x82,
	0x79, 0x6a, 0x78, 0x27, 0x92, 0x65, 0x3f, 0x85, 0x4d, 0xa9, 0x93, 0x0c, 0xb3, 0x81, 0x17, 0x33,
	0x4e, 0x7b, 0xd4, 0x27, 0xa6, 0x00, 0x0a, 0x2d, 0x69, 0xb2, 0x33, 0xcc, 0x06, 0x2f, 0x8b, 0x4c,
	0xe7, 0xaf, 0x16, 0xdc, 0x3f, 0x0c, 0x82, 0xe7, 0x2c, 0xe5, 0xa7, 0x2c, 0xa0, 0x3d, 0x8a, 0x79,
	0xe5, 0x78, 0x0e, 0x2b, 0x91, 0x26, 0x79, 0x7c, 0x9c, 0xe0, 0xfc, 0x78, 0x59, 0x36, 0x7a, 0xe7,
	0xe3, 0x44, 0xf6, 0x84, 0x1e, 0x4b, 0xf9, 0xa4, 0x5a, 0x57, 0xc5, 0xb2, 0x1d, 0xcc, 0x8a, 0x56,
	0x79, 0xee, 0x68, 0x55, 0x66, 0x47, 0xeb, 0x0c, 0x36, 0x14, 0xac, 0x2e, 0x92, 0x80, 0xf0, 0x62,
	0x91, 0x99, 0x42, 0x44, 0xbe, 0xb6, 0x3f, 0x86, 0xa5, 0x69, 0x10, 0x4c, 0x08, 0xce, 0x5f, 0x2c,
	0x58, 0x17, 0xde, 0xe9, 0x22, 0x49, 0xfd, 0x41, 0xa1, 0xcf, 0x99, 0x3b, 0x59, 0x77, 0xdd, 0xa9,
	0x34, 0xf7, 0x9d, 0xca, 0x33, 0xef, 0x64, 0x7f, 0x0a, 0x2b, 0x72, 0xb3, 0xdc, 0xa2, 0xba, 0xfb,
	0xb2, 0x20, 0xe6, 0xf6, 0x3e, 0x87, 0x55, 0x25, 0x94, 0x5b, 0x53, 0xed, 0x44, 0xaa, 0x4e, 0xfc,
	0xf3, 0x47, 0x0b, 0xd6, 0x4e, 0x4c, 0xbe, 0x9a, 0xdb, 0x4c, 0xe7, 0xb5, 0x35, 0x4f, 0x5e, 0x97,
	0xde, 0xce, 0xeb, 0x0f, 0x12, 0xd1, 0x4d, 0x68, 0x74, 0x7b, 0x34, 0x20, 0xaa, 0x71, 0xbe, 0x60,
	0x7d, 0xd3, 0x50, 0xce, 0x60, 0xfd, 0xe4, 0xd5, 0x90, 0x26, 0x47, 0x24, 0xe8, 0x17, 0xca, 0x1b,
	0x5c, 0x8a, 0x75, 0x11, 0xb1, 0x3b, 0x6f, 0x27, 0xa1, 0xd4, 0x11, 0xe8, 0x74, 0x97, 0x2e, 0xcd,
	0x4f, 0xe7, 0x5b, 0x0b, 0xb6, 0x44, 0xa8, 0x8f, 0x31, 0x09, 0xd9, 0x78, 0xaa, 0xb4, 0xdc, 0x18,
	0xf1, 0xdb, 0xfb, 0xc9, 0x07, 0x71, 0xc9, 0xa4, 0x2d, 0xba, 0x38, 0xa2, 0x23, 0xfc, 0x1e, 0xda,
	0xe2, 0xbf, 0x2c, 0x70, 0xcc, 0x98, 0xe8, 0x62, 0xc4, 0x38, 0x36, 0x59, 0xdc, 0xa3, 0xfd, 0x5f,
	0x60, 0x9a, 0x15, 0x1a, 0xf3, 0x53, 0x58, 0x4c, 0x42, 0xc2, 0x7b, 0x2c, 0x8d, 0xf4, 0x11, 0xb6,
	0xdf, 0x76, 0x7e, 0x47, 0x4b, 0xb8, 0xb9, 0xac, 0xfd, 0x05, 0x6c, 0x04, 0x38, 0xa2, 0x3e, 0x7a,
	0x11, 0x89, 0x87, 0x3d, 0xe2, 0x8b, 0x96, 0x95, 0x6a, 0x8c, 0xd9, 0x8a, 0x75, 0x5a, 0xe0, 0x08,
	0xc8, 0x1a, 0x05, 0x16, 0x60, 0xa8, 0xbb, 0x4c, 0x4d, 0x4b, 0x0a, 0x92, 0x7d, 0x1f, 0xaa, 0x21,
	0xf3, 0x49, 0xa8, 0xdc, 0xb8, 0xe4, 0xea, 0x95, 0xe8, 0x30, 0x24, 0x49, 0xbc, 0x91, 0x3a, 0xb9,
	0x4c, 0x93, 0x15, 0x17, 0x48, 0x92, 0xe8, 0xbb, 0x38, 0xff, 0xb4, 0xa0, 0xd1, 0xe5, 0x24, 0xe5,
	0xad, 0x71, 0xa4, 0x26, 0xb9, 0x3b, 0x26, 0xd2, 0x03, 0x68, 0xa8, 0xc1, 0x51, 0xd4, 0xea, 0x89,
	0x17, 0x45, 0xc1, 0x2e, 0xef, 0x55, 0xdd, 0x8d, 0x9c, 0xd9, 0x31, 0xfe, 0xcc, 0xec, 0x2f, 0xa1,
	0x1e, 0x60, 0x0f, 0xe3, 0xe0, 0xba, 0x8e, 0xbc, 0x48, 0x55, 0x5c, 0x59, 0xf3, 0x3a, 0xb7, 0x21,
	0xa9, 0x32, 0x37, 0x92, 0x16, 0x66, 0x23, 0xe9, 0x0a, 0x36, 0x75, 0x27, 0x9d, 0xab, 0x28, 0x54,
	0xae, 0x17, 0x85, 0x27, 0x60, 0x4f, 0x44, 0x84, 0x77, 0x45, 0x86, 0xea, 0xa0, 0xad, 0xe7, 0x9c,
	0x17, 0x9a, 0xe1, 0xec, 0xc0, 0x83, 0xe6, 0x00, 0xfd, 0xab, 0x43, 0x31, 0x3c, 0x62, 0x20, 0x73,
	0xd0, 0x8c, 0x56, 0xce, 0xaf, 0x60, 0x5d, 0x60, 0x5a, 0x1d, 0xc6, 0x9c, 0xe1, 0x18, 0x96, 0xa9,
	0xa2, 0xbc, 0x63, 0x07, 0xaa, 0x69, 0x35, 0x99, 0xd7, 0x3f, 0x84, 0x8f, 0x0d, 0x74, 0x05, 0xfb,
	0x1c, 0x23, 0x81, 0xbb, 0xc9, 0xd6, 0x2d, 0xa8, 0x77, 0xcd, 0x34, 0x72, 0x8e, 0x24, 0x7f, 0x7f,
	0x7c, 0x01, 0x15, 0x8e, 0x24, 0xba, 0xb9, 0x8a, 0x08, 0xe1, 0x26, 0x0b, 0x59, 0xea, 0x4a, 0x41,
	0xe7, 0x6f, 0x25, 0xd8, 0x68, 0x12, 0xee, 0x0f, 0xa6, 0x6a, 0xc7, 0x1c, 0xf5, 0xf5, 0x67, 0xb0,
	0x28, 0x40, 0x70, 0x49, 0xc2, 0x50, 0x3a, 0x70, 0xae, 0x5b, 0xe6, 0x2a, 0xa2, 0xfd, 0xc7, 0x2c,
	0x8d, 0x48, 0x48, 0xdf, 0x60, 0x20, 0xde, 0x2b, 0xd4, 0x0f, 0xd1, 0xcb, 0xe8, 0x1b, 0x53, 0x6d,
	0x1a, 0x13, 0xb6, 0xab, 0xb8, 0x5d, 0xfa, 0x06, 0x67, 0x94, 0xf5, 0xca, 0x8c, 0xb2, 0xfe, 0x10,
	0x6a, 0x03, 0xca, 0x0d, 0x4a, 0x25, 0x96, 0x16, 0x5d, 0x18, 0x50, 0xae, 0xef, 0x29, 0x3a, 0x54,
	0x96, 0xd0, 0xd8, 0x33, 0x7d, 0x5f, 0x3f, 0x50, 0x96, 0x05, 0xd1, 0x8c, 0x15, 0x53, 0x67, 0x54,
	0x06, 0x33, 0x2a, 0x21, 0x73, 0x6f, 0xfa, 0x8c, 0x5f, 0x0b, 0xdb, 0x8a, 0xe9, 0x74, 0xe1, 0xfe,
	0x4b, 0xea, 0x5f, 0x89, 0x71, 0x70, 0xca, 0xaf, 0xd7, 0x6b, 0x96, 0x35, 0x5d, 0x7a, 0xb7, 0x61,
	0x31, 0xd6, 0x8a, 0xe6, 0x9d, 0x68, 0xd6, 0xce, 0x4f, 0xe1, 0x13, 0x89, 0x45, 0xf3, 0x1a, 0x39,
	0x1c, 0x11, 0x1a, 0x92, 0xcb, 0x70, 0xae, 0x67, 0xc9, 0x26, 0x34, 0x5a, 0xc8, 0xbf, 0x16, 0x91,
	0xc6, 0xe0, 0xa4, 0x9f, 0xbf, 0x0f, 0x1c, 0x07, 0x76, 0x9b, 0x2c, 0x0c, 0xd1, 0xe7, 0xc7, 0x84,
	0x86, 0xe3, 0x63, 0x99, 0xc4, 0x98, 0x1e, 0xb1, 0x78, 0x98, 0xcb, 0xfc, 0x16, 0x76, 0xf3, 0x5c,
	0xbb, 0x69, 0xa6, 0x7c, 0xf6, 0xd6, 0xc5, 0x66, 0xe2, 0x2f, 0xaf, 0x0d, 0xc5, 0x4a, 0xfd, 0x14,
	0x1a, 0x17, 0x49, 0x3f, 0x25, 0xc1, 0xbb, 0x79, 0x4b, 0x64, 0x49, 0x0b, 0x79, 0x77, 0xd8, 0xef,
	0x63, 0xc6, 0x31, 0x30, 0x8e, 0xc9, 0xcf, 0xfd, 0xad, 0x05, 0xf5, 0x63, 0x9a, 0x5d, 0xfd, 0x37,
	0x85, 0xe2, 0x7b, 0x1d, 0x01, 0xfb, 0x60, 0xab, 0x2e, 0xce, 0xc5, 0x64, 0x7c, 0x67, 0xff, 0x2e,
	0x8e, 0x86, 0xa5, 0xdb, 0x46, 0xc3, 0xf2, 0xf4, 0x68, 0xc8, 0x60, 0xc7, 0x45, 0x7f, 0xec, 0x87,
	0x98, 0xa7, 0xa7, 0x48, 0xcc, 0xf7, 0xd1, 0x8d, 0xeb, 0xb0, 0x20, 0xbd, 0x27, 0x4f, 0xb4, 0xe0,
	0xaa, 0x85, 0xd3, 0x87, 0x0d, 0xf9, 0xf4, 0xd1, 0x9a, 0x66, 0xa3, 0x1f, 0xc3, 0xba, 0xfc, 0x4c,
	0xc1, 0x69, 0x84, 0x19, 0x27, 0x51, 0xe2, 0x45, 0xea, 0x59, 0x5a, 0x76, 0x3f, 0x12, 0x8c, 0x73,
	0x43, 0x3f, 0xcd, 0x44, 0xc2, 0xcb, 0x43, 0x5d, 0x22, 0xc6, 0x5e, 0x86, 0x18, 0xeb, 0x1d, 0x96,
	0x05, 0xf5, 0x08, 0x31, 0xee, 0x22, 0xc6, 0xf9, 0x24, 0xe4, 0xa2, 0x4f, 0xc2, 0xf0, 0x7f, 0x78,
	0x12, 0x7a, 0x0a, 0x0d, 0x17, 0x43, 0x24, 0xd9, 0x3b, 0x82, 0xfd, 0x0f, 0x16, 0xd4, 0x5b, 0xc8,
	0x4f, 0x49, 0x72, 0x76, 0xf9, 0x3b, 0xf4, 0x79, 0x0e, 0x93, 0x1d, 0xb8, 0xe7, 0x63, 0x18, 0x2a,
	0xa5, 0xf2, 0x5e, 0xe5, 0xa8, 0xb4, 0x66, 0xb9, 0x55, 0x41, 0x6a, 0x07, 0xf6, 0x97, 0x60, 0x67,
	0xa2, 0xb1, 0x5c, 0xf7, 0xb4, 0x68, 0xf2, 0x65, 0x29, 0xb7, 0x26, 0xb9, 0x45, 0x77, 0x17, 0xc1,
	0x55, 0xbe, 0x0d, 0x5c, 0x95, 0x69, 0x70, 0xfd, 0x5b, 0x9d, 0xb0, 0x35, 0x8e, 0xa6, 0x80, 0x7c,
	0xc3, 0x0c, 0xf2, 0x21, 0x1e, 0x1e, 0x8f, 0x60, 0x59, 0x6c, 0x35, 0x35, 0x6e, 0xd4, 0xfa, 0xe3,
	0x28, 0xb7, 0xf6, 0x29, 0xac, 0x48, 0x91, 0xa9, 0x41, 0x43, 0xe8, 0x4d, 0xec, 0x7c, 0x0e, 0xab,
	0x7e, 0x48, 0x31, 0xe6, 0xf9, 0xd0, 0x55, 0x95, 0x47, 0x5f, 0x51, 0x54, 0x33, 0x77, 0xd9, 0xb0,
	0x96, 0x7f, 0x15, 0x30, 0x55, 0x67, 0x1b, 0xb6, 0x8a, 0x15, 0xf5, 0x5a, 0x25, 0xfd, 0x0a, 0xee,
	0xb7, 0x90, 0x9b, 0xd6, 0x7e, 0x91, 0x4e, 0x7c, 0xf4, 0x00, 0x16, 0x49, 0x96, 0x21, 0x37, 0x61,
	0x5c, 0x72, 0xef, 0xc9, 0x75, 0x3b, 0x70, 0x7e, 0x2d, 0xbf, 0xef, 0x3c, 0x27, 0x23, 0x96, 0x52,
	0x7e, 0x37, 0x6a, 0xca, 0x45, 0x04, 0x3f, 0x84, 0x1a, 0xcd, 0xbc, 0x9e, 0xd6, 0xd5, 0xcf, 0x71,
	0xa0, 0x99, 0xb1, 0xe6, 0xfc, 0xc9, 0x52, 0x53, 0x0c, 0xc7, 0xa8, 0xf0, 0x1d, 0xf3, 0xbb, 0x14,
	0x82, 0x49, 0xb4, 0x4b, 0x77, 0x44, 0xfb, 0x3b, 0xe7, 0xd2, 0x3f, 0x2c, 0xd9, 0xd6, 0x0e, 0x85,
	0xa3, 0x8e, 0xa9, 0xe8, 0x02, 0xff, 0x57, 0x53, 0xfd, 0x4f, 0xa0, 0x7e, 0x32, 0x62, 0xe1, 0xe8,
	0xdd, 0x2a, 0xc5, 0xd1, 0xe2, 0x37, 0x55, 0xf9, 0x9d, 0x3c, 0xeb, 0xfc, 0xa0, 0x63, 0x75, 0x4a,
	0x9d, 0xf2, 0xa5, 0x5a, 0x7f, 0xf5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x5f, 0xfd, 0x67,
	0xcf, 0x17, 0x00, 0x00,
}
