// Code generated by protoc-gen-go.
// source: networking_platform.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type PlatformRequestType int32

const (
	PlatformRequestType_METHOD_UNSET             PlatformRequestType = 0
	PlatformRequestType_BUY_ITEM_POKECOINS       PlatformRequestType = 2
	PlatformRequestType_BUY_ITEM_ANDROID         PlatformRequestType = 3
	PlatformRequestType_BUY_ITEM_IOS             PlatformRequestType = 4
	PlatformRequestType_GET_STORE_ITEMS          PlatformRequestType = 5
	PlatformRequestType_SEND_ENCRYPTED_SIGNATURE PlatformRequestType = 6
)

var PlatformRequestType_name = map[int32]string{
	0: "METHOD_UNSET",
	2: "BUY_ITEM_POKECOINS",
	3: "BUY_ITEM_ANDROID",
	4: "BUY_ITEM_IOS",
	5: "GET_STORE_ITEMS",
	6: "SEND_ENCRYPTED_SIGNATURE",
}
var PlatformRequestType_value = map[string]int32{
	"METHOD_UNSET":             0,
	"BUY_ITEM_POKECOINS":       2,
	"BUY_ITEM_ANDROID":         3,
	"BUY_ITEM_IOS":             4,
	"GET_STORE_ITEMS":          5,
	"SEND_ENCRYPTED_SIGNATURE": 6,
}

func (x PlatformRequestType) String() string {
	return proto.EnumName(PlatformRequestType_name, int32(x))
}

func init() {
	proto.RegisterEnum("POGOProtos.Networking.Platform.PlatformRequestType", PlatformRequestType_name, PlatformRequestType_value)
}
