// Code generated by protoc-gen-go.
// source: data_battle/data_battle.proto
// DO NOT EDIT!

/*
Package data_battle is a generated protocol buffer package.

It is generated from these files:
	data_battle/data_battle.proto

It has these top-level messages:
	BattleAction
	BattleLog
	BattleParticipant
	BattlePokemonInfo
	BattleResults
*/
package data_battle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import POGOProtos_Data_Player "github.com/pkmngo-odi/pogo-protos/data_player"
import POGOProtos_Data "github.com/pkmngo-odi/pogo-protos/data"
import POGOProtos_Data_Gym "github.com/pkmngo-odi/pogo-protos/data_gym"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ContactSettings from public import data_player/data_player.proto
type ContactSettings POGOProtos_Data_Player.ContactSettings

func (m *ContactSettings) Reset() { (*POGOProtos_Data_Player.ContactSettings)(m).Reset() }
func (m *ContactSettings) String() string {
	return (*POGOProtos_Data_Player.ContactSettings)(m).String()
}
func (*ContactSettings) ProtoMessage() {}

// Currency from public import data_player/data_player.proto
type Currency POGOProtos_Data_Player.Currency

func (m *Currency) Reset()         { (*POGOProtos_Data_Player.Currency)(m).Reset() }
func (m *Currency) String() string { return (*POGOProtos_Data_Player.Currency)(m).String() }
func (*Currency) ProtoMessage()    {}

// DailyBonus from public import data_player/data_player.proto
type DailyBonus POGOProtos_Data_Player.DailyBonus

func (m *DailyBonus) Reset()         { (*POGOProtos_Data_Player.DailyBonus)(m).Reset() }
func (m *DailyBonus) String() string { return (*POGOProtos_Data_Player.DailyBonus)(m).String() }
func (*DailyBonus) ProtoMessage()    {}

// EquippedBadge from public import data_player/data_player.proto
type EquippedBadge POGOProtos_Data_Player.EquippedBadge

func (m *EquippedBadge) Reset()         { (*POGOProtos_Data_Player.EquippedBadge)(m).Reset() }
func (m *EquippedBadge) String() string { return (*POGOProtos_Data_Player.EquippedBadge)(m).String() }
func (*EquippedBadge) ProtoMessage()    {}

// PlayerAvatar from public import data_player/data_player.proto
type PlayerAvatar POGOProtos_Data_Player.PlayerAvatar

func (m *PlayerAvatar) Reset()         { (*POGOProtos_Data_Player.PlayerAvatar)(m).Reset() }
func (m *PlayerAvatar) String() string { return (*POGOProtos_Data_Player.PlayerAvatar)(m).String() }
func (*PlayerAvatar) ProtoMessage()    {}

// PlayerCamera from public import data_player/data_player.proto
type PlayerCamera POGOProtos_Data_Player.PlayerCamera

func (m *PlayerCamera) Reset()         { (*POGOProtos_Data_Player.PlayerCamera)(m).Reset() }
func (m *PlayerCamera) String() string { return (*POGOProtos_Data_Player.PlayerCamera)(m).String() }
func (*PlayerCamera) ProtoMessage()    {}

// PlayerCurrency from public import data_player/data_player.proto
type PlayerCurrency POGOProtos_Data_Player.PlayerCurrency

func (m *PlayerCurrency) Reset()         { (*POGOProtos_Data_Player.PlayerCurrency)(m).Reset() }
func (m *PlayerCurrency) String() string { return (*POGOProtos_Data_Player.PlayerCurrency)(m).String() }
func (*PlayerCurrency) ProtoMessage()    {}

// PlayerPublicProfile from public import data_player/data_player.proto
type PlayerPublicProfile POGOProtos_Data_Player.PlayerPublicProfile

func (m *PlayerPublicProfile) Reset() { (*POGOProtos_Data_Player.PlayerPublicProfile)(m).Reset() }
func (m *PlayerPublicProfile) String() string {
	return (*POGOProtos_Data_Player.PlayerPublicProfile)(m).String()
}
func (*PlayerPublicProfile) ProtoMessage() {}
func (m *PlayerPublicProfile) GetAvatar() *PlayerAvatar {
	return (*PlayerAvatar)((*POGOProtos_Data_Player.PlayerPublicProfile)(m).GetAvatar())
}

// PlayerStats from public import data_player/data_player.proto
type PlayerStats POGOProtos_Data_Player.PlayerStats

func (m *PlayerStats) Reset()         { (*POGOProtos_Data_Player.PlayerStats)(m).Reset() }
func (m *PlayerStats) String() string { return (*POGOProtos_Data_Player.PlayerStats)(m).String() }
func (*PlayerStats) ProtoMessage()    {}

// AssetDigestEntry from public import data/data.proto
type AssetDigestEntry POGOProtos_Data.AssetDigestEntry

func (m *AssetDigestEntry) Reset()         { (*POGOProtos_Data.AssetDigestEntry)(m).Reset() }
func (m *AssetDigestEntry) String() string { return (*POGOProtos_Data.AssetDigestEntry)(m).String() }
func (*AssetDigestEntry) ProtoMessage()    {}

// DownloadUrlEntry from public import data/data.proto
type DownloadUrlEntry POGOProtos_Data.DownloadUrlEntry

func (m *DownloadUrlEntry) Reset()         { (*POGOProtos_Data.DownloadUrlEntry)(m).Reset() }
func (m *DownloadUrlEntry) String() string { return (*POGOProtos_Data.DownloadUrlEntry)(m).String() }
func (*DownloadUrlEntry) ProtoMessage()    {}

// PlayerBadge from public import data/data.proto
type PlayerBadge POGOProtos_Data.PlayerBadge

func (m *PlayerBadge) Reset()         { (*POGOProtos_Data.PlayerBadge)(m).Reset() }
func (m *PlayerBadge) String() string { return (*POGOProtos_Data.PlayerBadge)(m).String() }
func (*PlayerBadge) ProtoMessage()    {}

// PlayerData from public import data/data.proto
type PlayerData POGOProtos_Data.PlayerData

func (m *PlayerData) Reset()         { (*POGOProtos_Data.PlayerData)(m).Reset() }
func (m *PlayerData) String() string { return (*POGOProtos_Data.PlayerData)(m).String() }
func (*PlayerData) ProtoMessage()    {}

// PokedexEntry from public import data/data.proto
type PokedexEntry POGOProtos_Data.PokedexEntry

func (m *PokedexEntry) Reset()         { (*POGOProtos_Data.PokedexEntry)(m).Reset() }
func (m *PokedexEntry) String() string { return (*POGOProtos_Data.PokedexEntry)(m).String() }
func (*PokedexEntry) ProtoMessage()    {}

// PokemonData from public import data/data.proto
type PokemonData POGOProtos_Data.PokemonData

func (m *PokemonData) Reset()         { (*POGOProtos_Data.PokemonData)(m).Reset() }
func (m *PokemonData) String() string { return (*POGOProtos_Data.PokemonData)(m).String() }
func (*PokemonData) ProtoMessage()    {}

// GymMembership from public import data_gym/data_gym.proto
type GymMembership POGOProtos_Data_Gym.GymMembership

func (m *GymMembership) Reset()         { (*POGOProtos_Data_Gym.GymMembership)(m).Reset() }
func (m *GymMembership) String() string { return (*POGOProtos_Data_Gym.GymMembership)(m).String() }
func (*GymMembership) ProtoMessage()    {}

// GymState from public import data_gym/data_gym.proto
type GymState POGOProtos_Data_Gym.GymState

func (m *GymState) Reset()         { (*POGOProtos_Data_Gym.GymState)(m).Reset() }
func (m *GymState) String() string { return (*POGOProtos_Data_Gym.GymState)(m).String() }
func (*GymState) ProtoMessage()    {}
func (m *GymState) GetMemberships() []*GymMembership {
	o := (*POGOProtos_Data_Gym.GymState)(m).GetMemberships()
	if o == nil {
		return nil
	}
	s := make([]*GymMembership, len(o))
	for i, x := range o {
		s[i] = (*GymMembership)(x)
	}
	return s
}

type BattleActionType int32

const (
	BattleActionType_ACTION_UNSET          BattleActionType = 0
	BattleActionType_ACTION_ATTACK         BattleActionType = 1
	BattleActionType_ACTION_DODGE          BattleActionType = 2
	BattleActionType_ACTION_SPECIAL_ATTACK BattleActionType = 3
	BattleActionType_ACTION_SWAP_POKEMON   BattleActionType = 4
	BattleActionType_ACTION_FAINT          BattleActionType = 5
	BattleActionType_ACTION_PLAYER_JOIN    BattleActionType = 6
	BattleActionType_ACTION_PLAYER_QUIT    BattleActionType = 7
	BattleActionType_ACTION_VICTORY        BattleActionType = 8
	BattleActionType_ACTION_DEFEAT         BattleActionType = 9
	BattleActionType_ACTION_TIMED_OUT      BattleActionType = 10
)

var BattleActionType_name = map[int32]string{
	0:  "ACTION_UNSET",
	1:  "ACTION_ATTACK",
	2:  "ACTION_DODGE",
	3:  "ACTION_SPECIAL_ATTACK",
	4:  "ACTION_SWAP_POKEMON",
	5:  "ACTION_FAINT",
	6:  "ACTION_PLAYER_JOIN",
	7:  "ACTION_PLAYER_QUIT",
	8:  "ACTION_VICTORY",
	9:  "ACTION_DEFEAT",
	10: "ACTION_TIMED_OUT",
}
var BattleActionType_value = map[string]int32{
	"ACTION_UNSET":          0,
	"ACTION_ATTACK":         1,
	"ACTION_DODGE":          2,
	"ACTION_SPECIAL_ATTACK": 3,
	"ACTION_SWAP_POKEMON":   4,
	"ACTION_FAINT":          5,
	"ACTION_PLAYER_JOIN":    6,
	"ACTION_PLAYER_QUIT":    7,
	"ACTION_VICTORY":        8,
	"ACTION_DEFEAT":         9,
	"ACTION_TIMED_OUT":      10,
}

func (x BattleActionType) String() string {
	return proto.EnumName(BattleActionType_name, int32(x))
}
func (BattleActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BattleState int32

const (
	BattleState_STATE_UNSET BattleState = 0
	BattleState_ACTIVE      BattleState = 1
	BattleState_VICTORY     BattleState = 2
	BattleState_DEFEATED    BattleState = 3
	BattleState_TIMED_OUT   BattleState = 4
)

var BattleState_name = map[int32]string{
	0: "STATE_UNSET",
	1: "ACTIVE",
	2: "VICTORY",
	3: "DEFEATED",
	4: "TIMED_OUT",
}
var BattleState_value = map[string]int32{
	"STATE_UNSET": 0,
	"ACTIVE":      1,
	"VICTORY":     2,
	"DEFEATED":    3,
	"TIMED_OUT":   4,
}

func (x BattleState) String() string {
	return proto.EnumName(BattleState_name, int32(x))
}
func (BattleState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BattleType int32

const (
	BattleType_BATTLE_TYPE_UNSET BattleType = 0
	BattleType_NORMAL            BattleType = 1
	BattleType_TRAINING          BattleType = 2
)

var BattleType_name = map[int32]string{
	0: "BATTLE_TYPE_UNSET",
	1: "NORMAL",
	2: "TRAINING",
}
var BattleType_value = map[string]int32{
	"BATTLE_TYPE_UNSET": 0,
	"NORMAL":            1,
	"TRAINING":          2,
}

func (x BattleType) String() string {
	return proto.EnumName(BattleType_name, int32(x))
}
func (BattleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BattleAction struct {
	Type                           BattleActionType   `protobuf:"varint,1,opt,name=Type,json=type,enum=POGOProtos.Data.Battle.BattleActionType" json:"Type,omitempty"`
	ActionStartMs                  int64              `protobuf:"varint,2,opt,name=action_start_ms,json=actionStartMs" json:"action_start_ms,omitempty"`
	DurationMs                     int32              `protobuf:"varint,3,opt,name=duration_ms,json=durationMs" json:"duration_ms,omitempty"`
	EnergyDelta                    int32              `protobuf:"varint,5,opt,name=energy_delta,json=energyDelta" json:"energy_delta,omitempty"`
	AttackerIndex                  int32              `protobuf:"varint,6,opt,name=attacker_index,json=attackerIndex" json:"attacker_index,omitempty"`
	TargetIndex                    int32              `protobuf:"varint,7,opt,name=target_index,json=targetIndex" json:"target_index,omitempty"`
	ActivePokemonId                uint64             `protobuf:"varint,8,opt,name=active_pokemon_id,json=activePokemonId" json:"active_pokemon_id,omitempty"`
	PlayerJoined                   *BattleParticipant `protobuf:"bytes,9,opt,name=player_joined,json=playerJoined" json:"player_joined,omitempty"`
	BattleResults                  *BattleResults     `protobuf:"bytes,10,opt,name=battle_results,json=battleResults" json:"battle_results,omitempty"`
	DamageWindowsStartTimestampMss int64              `protobuf:"varint,11,opt,name=damage_windows_start_timestamp_mss,json=damageWindowsStartTimestampMss" json:"damage_windows_start_timestamp_mss,omitempty"`
	DamageWindowsEndTimestampMss   int64              `protobuf:"varint,12,opt,name=damage_windows_end_timestamp_mss,json=damageWindowsEndTimestampMss" json:"damage_windows_end_timestamp_mss,omitempty"`
	PlayerLeft                     *BattleParticipant `protobuf:"bytes,13,opt,name=player_left,json=playerLeft" json:"player_left,omitempty"`
	TargetPokemonId                uint64             `protobuf:"varint,14,opt,name=target_pokemon_id,json=targetPokemonId" json:"target_pokemon_id,omitempty"`
}

func (m *BattleAction) Reset()                    { *m = BattleAction{} }
func (m *BattleAction) String() string            { return proto.CompactTextString(m) }
func (*BattleAction) ProtoMessage()               {}
func (*BattleAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BattleAction) GetPlayerJoined() *BattleParticipant {
	if m != nil {
		return m.PlayerJoined
	}
	return nil
}

func (m *BattleAction) GetBattleResults() *BattleResults {
	if m != nil {
		return m.BattleResults
	}
	return nil
}

func (m *BattleAction) GetPlayerLeft() *BattleParticipant {
	if m != nil {
		return m.PlayerLeft
	}
	return nil
}

type BattleLog struct {
	State                  BattleState     `protobuf:"varint,1,opt,name=state,enum=POGOProtos.Data.Battle.BattleState" json:"state,omitempty"`
	BattleType             BattleType      `protobuf:"varint,2,opt,name=battle_type,json=battleType,enum=POGOProtos.Data.Battle.BattleType" json:"battle_type,omitempty"`
	ServerMs               int64           `protobuf:"varint,3,opt,name=server_ms,json=serverMs" json:"server_ms,omitempty"`
	BattleActions          []*BattleAction `protobuf:"bytes,4,rep,name=battle_actions,json=battleActions" json:"battle_actions,omitempty"`
	BattleStartTimestampMs int64           `protobuf:"varint,5,opt,name=battle_start_timestamp_ms,json=battleStartTimestampMs" json:"battle_start_timestamp_ms,omitempty"`
	BattleEndTimestampMs   int64           `protobuf:"varint,6,opt,name=battle_end_timestamp_ms,json=battleEndTimestampMs" json:"battle_end_timestamp_ms,omitempty"`
}

func (m *BattleLog) Reset()                    { *m = BattleLog{} }
func (m *BattleLog) String() string            { return proto.CompactTextString(m) }
func (*BattleLog) ProtoMessage()               {}
func (*BattleLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BattleLog) GetBattleActions() []*BattleAction {
	if m != nil {
		return m.BattleActions
	}
	return nil
}

type BattleParticipant struct {
	ActivePokemon        *BattlePokemonInfo                          `protobuf:"bytes,1,opt,name=active_pokemon,json=activePokemon" json:"active_pokemon,omitempty"`
	TrainerPublicProfile *POGOProtos_Data_Player.PlayerPublicProfile `protobuf:"bytes,2,opt,name=trainer_public_profile,json=trainerPublicProfile" json:"trainer_public_profile,omitempty"`
	ReversePokemon       []*BattlePokemonInfo                        `protobuf:"bytes,3,rep,name=reverse_pokemon,json=reversePokemon" json:"reverse_pokemon,omitempty"`
	DefeatedPokemon      []*BattlePokemonInfo                        `protobuf:"bytes,4,rep,name=defeated_pokemon,json=defeatedPokemon" json:"defeated_pokemon,omitempty"`
}

func (m *BattleParticipant) Reset()                    { *m = BattleParticipant{} }
func (m *BattleParticipant) String() string            { return proto.CompactTextString(m) }
func (*BattleParticipant) ProtoMessage()               {}
func (*BattleParticipant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BattleParticipant) GetActivePokemon() *BattlePokemonInfo {
	if m != nil {
		return m.ActivePokemon
	}
	return nil
}

func (m *BattleParticipant) GetTrainerPublicProfile() *POGOProtos_Data_Player.PlayerPublicProfile {
	if m != nil {
		return m.TrainerPublicProfile
	}
	return nil
}

func (m *BattleParticipant) GetReversePokemon() []*BattlePokemonInfo {
	if m != nil {
		return m.ReversePokemon
	}
	return nil
}

func (m *BattleParticipant) GetDefeatedPokemon() []*BattlePokemonInfo {
	if m != nil {
		return m.DefeatedPokemon
	}
	return nil
}

type BattlePokemonInfo struct {
	PokemonData   *POGOProtos_Data.PokemonData `protobuf:"bytes,1,opt,name=pokemon_data,json=pokemonData" json:"pokemon_data,omitempty"`
	CurrentHealth int32                        `protobuf:"varint,2,opt,name=current_health,json=currentHealth" json:"current_health,omitempty"`
	CurrentEnergy int32                        `protobuf:"varint,3,opt,name=current_energy,json=currentEnergy" json:"current_energy,omitempty"`
}

func (m *BattlePokemonInfo) Reset()                    { *m = BattlePokemonInfo{} }
func (m *BattlePokemonInfo) String() string            { return proto.CompactTextString(m) }
func (*BattlePokemonInfo) ProtoMessage()               {}
func (*BattlePokemonInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BattlePokemonInfo) GetPokemonData() *POGOProtos_Data.PokemonData {
	if m != nil {
		return m.PokemonData
	}
	return nil
}

type BattleResults struct {
	GymState                *POGOProtos_Data_Gym.GymState `protobuf:"bytes,1,opt,name=gym_state,json=gymState" json:"gym_state,omitempty"`
	Attackers               []*BattleParticipant          `protobuf:"bytes,2,rep,name=attackers" json:"attackers,omitempty"`
	PlayerExperienceAwarded []int32                       `protobuf:"varint,3,rep,name=player_experience_awarded,json=playerExperienceAwarded" json:"player_experience_awarded,omitempty"`
	NextDefenderPokemonId   int64                         `protobuf:"varint,4,opt,name=next_defender_pokemon_id,json=nextDefenderPokemonId" json:"next_defender_pokemon_id,omitempty"`
	GymPointsDelta          int32                         `protobuf:"varint,5,opt,name=gym_points_delta,json=gymPointsDelta" json:"gym_points_delta,omitempty"`
}

func (m *BattleResults) Reset()                    { *m = BattleResults{} }
func (m *BattleResults) String() string            { return proto.CompactTextString(m) }
func (*BattleResults) ProtoMessage()               {}
func (*BattleResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BattleResults) GetGymState() *POGOProtos_Data_Gym.GymState {
	if m != nil {
		return m.GymState
	}
	return nil
}

func (m *BattleResults) GetAttackers() []*BattleParticipant {
	if m != nil {
		return m.Attackers
	}
	return nil
}

func init() {
	proto.RegisterType((*BattleAction)(nil), "POGOProtos.Data.Battle.BattleAction")
	proto.RegisterType((*BattleLog)(nil), "POGOProtos.Data.Battle.BattleLog")
	proto.RegisterType((*BattleParticipant)(nil), "POGOProtos.Data.Battle.BattleParticipant")
	proto.RegisterType((*BattlePokemonInfo)(nil), "POGOProtos.Data.Battle.BattlePokemonInfo")
	proto.RegisterType((*BattleResults)(nil), "POGOProtos.Data.Battle.BattleResults")
	proto.RegisterEnum("POGOProtos.Data.Battle.BattleActionType", BattleActionType_name, BattleActionType_value)
	proto.RegisterEnum("POGOProtos.Data.Battle.BattleState", BattleState_name, BattleState_value)
	proto.RegisterEnum("POGOProtos.Data.Battle.BattleType", BattleType_name, BattleType_value)
}

func init() { proto.RegisterFile("data_battle/data_battle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1087 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xde, 0xfc, 0x75, 0x9b, 0xe3, 0xfc, 0xb8, 0x43, 0x7f, 0xdc, 0x65, 0x17, 0x4a, 0x60, 0x51,
	0x29, 0x52, 0x2b, 0x15, 0x21, 0x04, 0x02, 0x21, 0x6f, 0xe3, 0x96, 0xb4, 0x69, 0x62, 0x1c, 0x77,
	0x57, 0xe5, 0xc6, 0x72, 0xe2, 0x69, 0x36, 0x6c, 0xe2, 0x58, 0xf6, 0x74, 0xdb, 0xbe, 0x0e, 0xaf,
	0xc0, 0xcb, 0xf0, 0x06, 0xdc, 0x73, 0xcd, 0x05, 0x67, 0x7e, 0x9c, 0x38, 0x0d, 0x2a, 0xf4, 0x62,
	0xb7, 0x93, 0x6f, 0xbe, 0xf3, 0xe5, 0xcc, 0xf9, 0xe6, 0x9c, 0x09, 0xbc, 0x08, 0x7c, 0xe6, 0x7b,
	0x7d, 0x9f, 0xb1, 0x31, 0x3d, 0xc8, 0xac, 0xf7, 0xa3, 0x78, 0xca, 0xa6, 0x64, 0xd3, 0xee, 0x9e,
	0x74, 0x6d, 0xbe, 0x4c, 0xf6, 0x9b, 0xb8, 0xbb, 0xff, 0x4a, 0xec, 0x3e, 0x93, 0x61, 0xd1, 0xd8,
	0xbf, 0xa3, 0xf1, 0x41, 0x66, 0x2d, 0xc3, 0x9e, 0xd5, 0x39, 0x24, 0x70, 0x05, 0x6c, 0x09, 0xce,
	0xf0, 0x6e, 0x72, 0x90, 0x2e, 0xe4, 0x46, 0xe3, 0x8f, 0x12, 0x54, 0xa4, 0xa6, 0x39, 0x60, 0xa3,
	0x69, 0x48, 0xbe, 0x87, 0xa2, 0x7b, 0x17, 0x51, 0x23, 0xb7, 0x93, 0xdb, 0xad, 0x1d, 0xee, 0xee,
	0xff, 0x7b, 0x02, 0xfb, 0xd9, 0x18, 0xce, 0x77, 0x8a, 0x0c, 0xff, 0x27, 0x9f, 0x43, 0xdd, 0x17,
	0x98, 0x97, 0x30, 0x3f, 0x66, 0xde, 0x24, 0x31, 0xf2, 0x28, 0x54, 0x70, 0xaa, 0x12, 0xee, 0x71,
	0xf4, 0x3c, 0x21, 0x1f, 0x83, 0x16, 0x5c, 0xc7, 0xbe, 0x60, 0x22, 0xa7, 0x80, 0x9c, 0x92, 0x03,
	0x29, 0x84, 0x84, 0x4f, 0xa0, 0x42, 0x43, 0x1a, 0x0f, 0xef, 0xbc, 0x80, 0x8e, 0x99, 0x6f, 0x94,
	0x04, 0x43, 0x93, 0x58, 0x93, 0x43, 0xe4, 0x25, 0xd4, 0x30, 0x09, 0x7f, 0xf0, 0x8e, 0xc6, 0xde,
	0x28, 0x0c, 0xe8, 0xad, 0xb1, 0x22, 0x48, 0xd5, 0x14, 0x6d, 0x71, 0x90, 0x2b, 0xe1, 0x97, 0x0e,
	0x29, 0x53, 0xa4, 0xa7, 0x52, 0x49, 0x62, 0x92, 0xb2, 0x07, 0x6b, 0x3c, 0xbd, 0xf7, 0xd4, 0x8b,
	0xa6, 0xef, 0xe8, 0x04, 0x73, 0x1a, 0x05, 0xc6, 0x2a, 0xf2, 0x8a, 0x4e, 0x5d, 0x6e, 0xd8, 0x12,
	0x6f, 0x05, 0xa4, 0x03, 0x55, 0x59, 0x6a, 0xef, 0xd7, 0xe9, 0x28, 0xa4, 0x81, 0x51, 0x46, 0x9e,
	0x76, 0xf8, 0xc5, 0xc3, 0x85, 0xb2, 0xf1, 0xd8, 0xa3, 0xc1, 0x28, 0xf2, 0x43, 0xe6, 0x54, 0x64,
	0xfc, 0xa9, 0x08, 0x27, 0x6d, 0xa8, 0x49, 0xc7, 0xbd, 0x98, 0x26, 0xd7, 0x63, 0x96, 0x18, 0x20,
	0x04, 0x5f, 0x3e, 0x2c, 0xe8, 0x48, 0xb2, 0x53, 0xed, 0x67, 0x3f, 0x92, 0x53, 0x68, 0x04, 0xfe,
	0xc4, 0x1f, 0x52, 0xef, 0x06, 0x4f, 0x3b, 0xbd, 0x49, 0x94, 0x0f, 0x6c, 0x34, 0xa1, 0xb8, 0x9a,
	0x44, 0x58, 0xed, 0xc4, 0xd0, 0x84, 0x25, 0x1f, 0x49, 0xe6, 0x1b, 0x49, 0x14, 0xce, 0xb8, 0x29,
	0xed, 0x3c, 0x49, 0xc8, 0x31, 0xec, 0xdc, 0xd3, 0xa2, 0x61, 0x70, 0x4f, 0xa9, 0x22, 0x94, 0x9e,
	0x2f, 0x28, 0x59, 0x61, 0xb0, 0xa0, 0x73, 0x0a, 0x9a, 0xaa, 0xd8, 0x98, 0x5e, 0x31, 0xa3, 0xfa,
	0xd8, 0x7a, 0x81, 0x8c, 0x6e, 0x63, 0x30, 0x77, 0x4a, 0x99, 0x99, 0x71, 0xaa, 0x26, 0x9d, 0x92,
	0x1b, 0x33, 0xa7, 0x1a, 0x7f, 0xe6, 0xa1, 0x2c, 0xd5, 0xda, 0xd3, 0x21, 0xf9, 0x16, 0x4a, 0x98,
	0x11, 0x4b, 0x2f, 0xf6, 0xa7, 0x0f, 0x7f, 0x7f, 0x8f, 0x53, 0x1d, 0x19, 0x41, 0x8e, 0x40, 0x53,
	0x16, 0xf1, 0x3b, 0x2e, 0x2e, 0x74, 0xed, 0xb0, 0xf1, 0xb0, 0x80, 0xe8, 0x09, 0xe8, 0xcf, 0xd6,
	0xe4, 0x43, 0x28, 0x27, 0x34, 0x7e, 0x8f, 0x55, 0x50, 0xf7, 0xbd, 0xe0, 0xac, 0x4a, 0x00, 0x6f,
	0xfb, 0xd9, 0xec, 0x12, 0xc8, 0x36, 0x49, 0x8c, 0xe2, 0x4e, 0x01, 0xab, 0xf4, 0xd9, 0xff, 0x69,
	0xbf, 0xf4, 0x0e, 0xc8, 0x4f, 0x09, 0x9e, 0x74, 0x5b, 0x89, 0x2d, 0x7b, 0x2f, 0xfa, 0xa8, 0xe0,
	0x6c, 0xf6, 0xd3, 0x53, 0x2e, 0x78, 0x4e, 0xbe, 0x86, 0x2d, 0x15, 0x7a, 0xdf, 0x6a, 0xd1, 0x5b,
	0x05, 0x67, 0x5d, 0x6e, 0x2f, 0x5a, 0xdc, 0xf8, 0x2b, 0x0f, 0x6b, 0x4b, 0xbe, 0x11, 0x1b, 0xfb,
	0x73, 0xa1, 0xab, 0x44, 0xe9, 0xff, 0xdb, 0x7a, 0x65, 0x60, 0x78, 0x35, 0x95, 0x53, 0x63, 0xd6,
	0x7d, 0xc4, 0x87, 0x4d, 0x16, 0xfb, 0xd8, 0x36, 0xb1, 0x17, 0x5d, 0xf7, 0xc7, 0xa3, 0x81, 0x87,
	0x43, 0xec, 0x6a, 0x34, 0x96, 0x9e, 0x68, 0x87, 0x5f, 0x2e, 0x29, 0xdb, 0x72, 0x2a, 0xca, 0x3f,
	0xb6, 0x88, 0xb1, 0x65, 0x88, 0xb3, 0xae, 0xa4, 0x16, 0x50, 0xe2, 0x40, 0x3d, 0xa6, 0x68, 0x4a,
	0x32, 0xcf, 0xba, 0x20, 0xac, 0x78, 0x44, 0xd6, 0x35, 0xa5, 0x90, 0xa6, 0xed, 0x82, 0x1e, 0xd0,
	0x2b, 0x8a, 0x57, 0x29, 0x98, 0x89, 0x16, 0x1f, 0x2b, 0x5a, 0x4f, 0x25, 0x14, 0xd8, 0xf8, 0x2d,
	0x37, 0x2b, 0xfa, 0x9c, 0x46, 0x7e, 0x84, 0x4a, 0xda, 0x19, 0x7c, 0xd2, 0xab, 0x92, 0x3f, 0x5f,
	0x2e, 0x8c, 0x24, 0xf1, 0xb5, 0xa3, 0x45, 0xf3, 0x0f, 0x7c, 0xaa, 0x0e, 0xae, 0xe3, 0x98, 0x86,
	0xcc, 0x7b, 0x4b, 0xfd, 0x31, 0x7b, 0x2b, 0x6a, 0x8b, 0x53, 0x55, 0xa1, 0x3f, 0x09, 0x30, 0x4b,
	0x93, 0x33, 0x59, 0xcd, 0xf0, 0x94, 0x66, 0x09, 0xb0, 0xf1, 0x7b, 0x1e, 0xaa, 0x0b, 0x03, 0x8b,
	0x7c, 0x07, 0x65, 0x7c, 0x7d, 0xbc, 0x79, 0x2f, 0x6a, 0x87, 0x2f, 0x96, 0xb2, 0x3b, 0xc1, 0xf7,
	0x09, 0xff, 0xc9, 0x2e, 0x5c, 0x1d, 0xaa, 0x15, 0x39, 0x81, 0x72, 0x3a, 0xdb, 0xf9, 0xbb, 0x52,
	0x78, 0xdc, 0x1c, 0x99, 0xc7, 0x62, 0x12, 0xdb, 0x6a, 0x24, 0xd1, 0xdb, 0x88, 0xc6, 0x23, 0x1a,
	0x0e, 0xb0, 0xf5, 0x6e, 0xfc, 0x38, 0xc0, 0x81, 0xce, 0xfd, 0x2e, 0x39, 0x5b, 0x92, 0x60, 0xcd,
	0xf6, 0x4d, 0xb9, 0x4d, 0xbe, 0x01, 0x23, 0xa4, 0xb7, 0xcc, 0xe3, 0x7e, 0xe0, 0xeb, 0x11, 0x67,
	0x27, 0x51, 0x51, 0x34, 0xc9, 0x06, 0xdf, 0x6f, 0xaa, 0xed, 0xf9, 0xcb, 0xb1, 0x0b, 0x3a, 0x3f,
	0x79, 0x84, 0x73, 0x9f, 0x25, 0x0b, 0xcf, 0x5a, 0x0d, 0x71, 0x5b, 0xc0, 0xe2, 0x65, 0xdb, 0xfb,
	0x3b, 0x07, 0xfa, 0xfd, 0x07, 0x96, 0xe8, 0x50, 0x31, 0x8f, 0xdc, 0x56, 0xb7, 0xe3, 0x5d, 0x74,
	0x7a, 0x96, 0xab, 0x3f, 0x21, 0x6b, 0x50, 0x55, 0x88, 0xe9, 0xba, 0xe6, 0xd1, 0x99, 0x9e, 0xcb,
	0x90, 0x9a, 0xdd, 0xe6, 0x89, 0xa5, 0xe7, 0xc9, 0x36, 0x6c, 0x28, 0xa4, 0x67, 0x5b, 0x47, 0x2d,
	0xb3, 0x9d, 0x92, 0x0b, 0x64, 0x0b, 0x3e, 0x48, 0xb7, 0xde, 0x98, 0xb6, 0x67, 0x77, 0xcf, 0xac,
	0xf3, 0x6e, 0x47, 0x2f, 0x66, 0x54, 0x8e, 0xcd, 0x56, 0xc7, 0xd5, 0x4b, 0x64, 0x13, 0x88, 0x42,
	0xec, 0xb6, 0x79, 0x69, 0x39, 0xde, 0x69, 0xb7, 0xd5, 0xd1, 0x57, 0x96, 0xf1, 0x9f, 0x2f, 0x5a,
	0xae, 0xfe, 0x94, 0x10, 0xa8, 0x29, 0xfc, 0x75, 0xeb, 0xc8, 0xed, 0x3a, 0x97, 0xfa, 0x6a, 0x26,
	0xdd, 0xa6, 0x75, 0x6c, 0x99, 0xae, 0x5e, 0x26, 0xeb, 0xa0, 0x2b, 0xc8, 0x6d, 0x9d, 0x5b, 0x4d,
	0xaf, 0x7b, 0xe1, 0xea, 0xb0, 0xe7, 0x82, 0x96, 0x99, 0xc2, 0xa4, 0x0e, 0x5a, 0xcf, 0x35, 0x5d,
	0x6b, 0x76, 0x6e, 0x80, 0x15, 0x1e, 0xf5, 0xda, 0xc2, 0x03, 0x6b, 0xf0, 0x34, 0xfd, 0x86, 0x3c,
	0xa9, 0xc0, 0xaa, 0x94, 0xb6, 0x9a, 0x78, 0xbc, 0x2a, 0x94, 0xe7, 0xaa, 0xc5, 0xbd, 0x1f, 0x00,
	0xe6, 0xa3, 0x99, 0x6c, 0x60, 0xf3, 0x60, 0x21, 0xda, 0x96, 0xe7, 0x5e, 0xda, 0x0b, 0xd2, 0x9d,
	0xae, 0x73, 0x6e, 0xb6, 0x51, 0x1a, 0xd5, 0x5c, 0x07, 0xcf, 0xdf, 0xea, 0x9c, 0xe8, 0xf9, 0x57,
	0xd5, 0x5f, 0xb4, 0xcc, 0xcf, 0x33, 0xfb, 0x89, 0x9d, 0xb3, 0xf3, 0xfd, 0x15, 0xf1, 0x23, 0xea,
	0xab, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x30, 0x1d, 0x93, 0xc6, 0x09, 0x00, 0x00,
}
