// Code generated by protoc-gen-go.
// source: inventory/inventory.proto
// DO NOT EDIT!

/*
Package inventory is a generated protocol buffer package.

It is generated from these files:
	inventory/inventory.proto

It has these top-level messages:
	AppliedItem
	AppliedItems
	EggIncubator
	EggIncubators
	InventoryDelta
	InventoryItem
	InventoryItemData
	InventoryUpgrade
	InventoryUpgrades
	PokemonFamily
*/
package inventory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import POGOProtos_Inventory_Item "github.com/zeeraw/pogo-protos/inventory_item"
import POGOProtos_Data "github.com/zeeraw/pogo-protos/data"
import POGOProtos_Data_Player "github.com/zeeraw/pogo-protos/data_player"
import POGOProtos_Enums "github.com/zeeraw/pogo-protos/enums"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ItemAward from public import inventory_item/inventory_item.proto
type ItemAward POGOProtos_Inventory_Item.ItemAward

func (m *ItemAward) Reset()         { (*POGOProtos_Inventory_Item.ItemAward)(m).Reset() }
func (m *ItemAward) String() string { return (*POGOProtos_Inventory_Item.ItemAward)(m).String() }
func (*ItemAward) ProtoMessage()    {}

// ItemData from public import inventory_item/inventory_item.proto
type ItemData POGOProtos_Inventory_Item.ItemData

func (m *ItemData) Reset()         { (*POGOProtos_Inventory_Item.ItemData)(m).Reset() }
func (m *ItemData) String() string { return (*POGOProtos_Inventory_Item.ItemData)(m).String() }
func (*ItemData) ProtoMessage()    {}

// ItemId from public import inventory_item/inventory_item.proto
type ItemId POGOProtos_Inventory_Item.ItemId

var ItemId_name = POGOProtos_Inventory_Item.ItemId_name
var ItemId_value = POGOProtos_Inventory_Item.ItemId_value

func (x ItemId) String() string { return (POGOProtos_Inventory_Item.ItemId)(x).String() }

const ItemId_ITEM_UNKNOWN = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_UNKNOWN)
const ItemId_ITEM_POKE_BALL = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_POKE_BALL)
const ItemId_ITEM_GREAT_BALL = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_GREAT_BALL)
const ItemId_ITEM_ULTRA_BALL = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_ULTRA_BALL)
const ItemId_ITEM_MASTER_BALL = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_MASTER_BALL)
const ItemId_ITEM_POTION = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_POTION)
const ItemId_ITEM_SUPER_POTION = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_SUPER_POTION)
const ItemId_ITEM_HYPER_POTION = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_HYPER_POTION)
const ItemId_ITEM_MAX_POTION = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_MAX_POTION)
const ItemId_ITEM_REVIVE = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_REVIVE)
const ItemId_ITEM_MAX_REVIVE = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_MAX_REVIVE)
const ItemId_ITEM_LUCKY_EGG = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_LUCKY_EGG)
const ItemId_ITEM_INCENSE_ORDINARY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_INCENSE_ORDINARY)
const ItemId_ITEM_INCENSE_SPICY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_INCENSE_SPICY)
const ItemId_ITEM_INCENSE_COOL = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_INCENSE_COOL)
const ItemId_ITEM_INCENSE_FLORAL = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_INCENSE_FLORAL)
const ItemId_ITEM_TROY_DISK = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_TROY_DISK)
const ItemId_ITEM_X_ATTACK = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_X_ATTACK)
const ItemId_ITEM_X_DEFENSE = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_X_DEFENSE)
const ItemId_ITEM_X_MIRACLE = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_X_MIRACLE)
const ItemId_ITEM_RAZZ_BERRY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_RAZZ_BERRY)
const ItemId_ITEM_BLUK_BERRY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_BLUK_BERRY)
const ItemId_ITEM_NANAB_BERRY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_NANAB_BERRY)
const ItemId_ITEM_WEPAR_BERRY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_WEPAR_BERRY)
const ItemId_ITEM_PINAP_BERRY = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_PINAP_BERRY)
const ItemId_ITEM_SPECIAL_CAMERA = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_SPECIAL_CAMERA)
const ItemId_ITEM_INCUBATOR_BASIC_UNLIMITED = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_INCUBATOR_BASIC_UNLIMITED)
const ItemId_ITEM_INCUBATOR_BASIC = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_INCUBATOR_BASIC)
const ItemId_ITEM_POKEMON_STORAGE_UPGRADE = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_POKEMON_STORAGE_UPGRADE)
const ItemId_ITEM_ITEM_STORAGE_UPGRADE = ItemId(POGOProtos_Inventory_Item.ItemId_ITEM_ITEM_STORAGE_UPGRADE)

// ItemType from public import inventory_item/inventory_item.proto
type ItemType POGOProtos_Inventory_Item.ItemType

var ItemType_name = POGOProtos_Inventory_Item.ItemType_name
var ItemType_value = POGOProtos_Inventory_Item.ItemType_value

func (x ItemType) String() string { return (POGOProtos_Inventory_Item.ItemType)(x).String() }

const ItemType_ITEM_TYPE_NONE = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_NONE)
const ItemType_ITEM_TYPE_POKEBALL = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_POKEBALL)
const ItemType_ITEM_TYPE_POTION = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_POTION)
const ItemType_ITEM_TYPE_REVIVE = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_REVIVE)
const ItemType_ITEM_TYPE_MAP = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_MAP)
const ItemType_ITEM_TYPE_BATTLE = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_BATTLE)
const ItemType_ITEM_TYPE_FOOD = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_FOOD)
const ItemType_ITEM_TYPE_CAMERA = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_CAMERA)
const ItemType_ITEM_TYPE_DISK = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_DISK)
const ItemType_ITEM_TYPE_INCUBATOR = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_INCUBATOR)
const ItemType_ITEM_TYPE_INCENSE = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_INCENSE)
const ItemType_ITEM_TYPE_XP_BOOST = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_XP_BOOST)
const ItemType_ITEM_TYPE_INVENTORY_UPGRADE = ItemType(POGOProtos_Inventory_Item.ItemType_ITEM_TYPE_INVENTORY_UPGRADE)

// AssetDigestEntry from public import data/data.proto
type AssetDigestEntry POGOProtos_Data.AssetDigestEntry

func (m *AssetDigestEntry) Reset()         { (*POGOProtos_Data.AssetDigestEntry)(m).Reset() }
func (m *AssetDigestEntry) String() string { return (*POGOProtos_Data.AssetDigestEntry)(m).String() }
func (*AssetDigestEntry) ProtoMessage()    {}

// DownloadUrlEntry from public import data/data.proto
type DownloadUrlEntry POGOProtos_Data.DownloadUrlEntry

func (m *DownloadUrlEntry) Reset()         { (*POGOProtos_Data.DownloadUrlEntry)(m).Reset() }
func (m *DownloadUrlEntry) String() string { return (*POGOProtos_Data.DownloadUrlEntry)(m).String() }
func (*DownloadUrlEntry) ProtoMessage()    {}

// PlayerBadge from public import data/data.proto
type PlayerBadge POGOProtos_Data.PlayerBadge

func (m *PlayerBadge) Reset()         { (*POGOProtos_Data.PlayerBadge)(m).Reset() }
func (m *PlayerBadge) String() string { return (*POGOProtos_Data.PlayerBadge)(m).String() }
func (*PlayerBadge) ProtoMessage()    {}

// PlayerData from public import data/data.proto
type PlayerData POGOProtos_Data.PlayerData

func (m *PlayerData) Reset()         { (*POGOProtos_Data.PlayerData)(m).Reset() }
func (m *PlayerData) String() string { return (*POGOProtos_Data.PlayerData)(m).String() }
func (*PlayerData) ProtoMessage()    {}

// PokedexEntry from public import data/data.proto
type PokedexEntry POGOProtos_Data.PokedexEntry

func (m *PokedexEntry) Reset()         { (*POGOProtos_Data.PokedexEntry)(m).Reset() }
func (m *PokedexEntry) String() string { return (*POGOProtos_Data.PokedexEntry)(m).String() }
func (*PokedexEntry) ProtoMessage()    {}

// PokemonData from public import data/data.proto
type PokemonData POGOProtos_Data.PokemonData

func (m *PokemonData) Reset()         { (*POGOProtos_Data.PokemonData)(m).Reset() }
func (m *PokemonData) String() string { return (*POGOProtos_Data.PokemonData)(m).String() }
func (*PokemonData) ProtoMessage()    {}

// ContactSettings from public import data_player/data_player.proto
type ContactSettings POGOProtos_Data_Player.ContactSettings

func (m *ContactSettings) Reset() { (*POGOProtos_Data_Player.ContactSettings)(m).Reset() }
func (m *ContactSettings) String() string {
	return (*POGOProtos_Data_Player.ContactSettings)(m).String()
}
func (*ContactSettings) ProtoMessage() {}

// Currency from public import data_player/data_player.proto
type Currency POGOProtos_Data_Player.Currency

func (m *Currency) Reset()         { (*POGOProtos_Data_Player.Currency)(m).Reset() }
func (m *Currency) String() string { return (*POGOProtos_Data_Player.Currency)(m).String() }
func (*Currency) ProtoMessage()    {}

// DailyBonus from public import data_player/data_player.proto
type DailyBonus POGOProtos_Data_Player.DailyBonus

func (m *DailyBonus) Reset()         { (*POGOProtos_Data_Player.DailyBonus)(m).Reset() }
func (m *DailyBonus) String() string { return (*POGOProtos_Data_Player.DailyBonus)(m).String() }
func (*DailyBonus) ProtoMessage()    {}

// EquippedBadge from public import data_player/data_player.proto
type EquippedBadge POGOProtos_Data_Player.EquippedBadge

func (m *EquippedBadge) Reset()         { (*POGOProtos_Data_Player.EquippedBadge)(m).Reset() }
func (m *EquippedBadge) String() string { return (*POGOProtos_Data_Player.EquippedBadge)(m).String() }
func (*EquippedBadge) ProtoMessage()    {}

// PlayerAvatar from public import data_player/data_player.proto
type PlayerAvatar POGOProtos_Data_Player.PlayerAvatar

func (m *PlayerAvatar) Reset()         { (*POGOProtos_Data_Player.PlayerAvatar)(m).Reset() }
func (m *PlayerAvatar) String() string { return (*POGOProtos_Data_Player.PlayerAvatar)(m).String() }
func (*PlayerAvatar) ProtoMessage()    {}

// PlayerCamera from public import data_player/data_player.proto
type PlayerCamera POGOProtos_Data_Player.PlayerCamera

func (m *PlayerCamera) Reset()         { (*POGOProtos_Data_Player.PlayerCamera)(m).Reset() }
func (m *PlayerCamera) String() string { return (*POGOProtos_Data_Player.PlayerCamera)(m).String() }
func (*PlayerCamera) ProtoMessage()    {}

// PlayerCurrency from public import data_player/data_player.proto
type PlayerCurrency POGOProtos_Data_Player.PlayerCurrency

func (m *PlayerCurrency) Reset()         { (*POGOProtos_Data_Player.PlayerCurrency)(m).Reset() }
func (m *PlayerCurrency) String() string { return (*POGOProtos_Data_Player.PlayerCurrency)(m).String() }
func (*PlayerCurrency) ProtoMessage()    {}

// PlayerPublicProfile from public import data_player/data_player.proto
type PlayerPublicProfile POGOProtos_Data_Player.PlayerPublicProfile

func (m *PlayerPublicProfile) Reset() { (*POGOProtos_Data_Player.PlayerPublicProfile)(m).Reset() }
func (m *PlayerPublicProfile) String() string {
	return (*POGOProtos_Data_Player.PlayerPublicProfile)(m).String()
}
func (*PlayerPublicProfile) ProtoMessage() {}
func (m *PlayerPublicProfile) GetAvatar() *PlayerAvatar {
	return (*PlayerAvatar)((*POGOProtos_Data_Player.PlayerPublicProfile)(m).GetAvatar())
}

// PlayerStats from public import data_player/data_player.proto
type PlayerStats POGOProtos_Data_Player.PlayerStats

func (m *PlayerStats) Reset()         { (*POGOProtos_Data_Player.PlayerStats)(m).Reset() }
func (m *PlayerStats) String() string { return (*POGOProtos_Data_Player.PlayerStats)(m).String() }
func (*PlayerStats) ProtoMessage()    {}

// ActivityType from public import enums/enums.proto
type ActivityType POGOProtos_Enums.ActivityType

var ActivityType_name = POGOProtos_Enums.ActivityType_name
var ActivityType_value = POGOProtos_Enums.ActivityType_value

func (x ActivityType) String() string { return (POGOProtos_Enums.ActivityType)(x).String() }

const ActivityType_ACTIVITY_UNKNOWN = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_UNKNOWN)
const ActivityType_ACTIVITY_CATCH_POKEMON = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_POKEMON)
const ActivityType_ACTIVITY_CATCH_LEGEND_POKEMON = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_LEGEND_POKEMON)
const ActivityType_ACTIVITY_FLEE_POKEMON = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_FLEE_POKEMON)
const ActivityType_ACTIVITY_DEFEAT_FORT = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_DEFEAT_FORT)
const ActivityType_ACTIVITY_EVOLVE_POKEMON = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_EVOLVE_POKEMON)
const ActivityType_ACTIVITY_HATCH_EGG = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_HATCH_EGG)
const ActivityType_ACTIVITY_WALK_KM = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_WALK_KM)
const ActivityType_ACTIVITY_POKEDEX_ENTRY_NEW = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_POKEDEX_ENTRY_NEW)
const ActivityType_ACTIVITY_CATCH_FIRST_THROW = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_FIRST_THROW)
const ActivityType_ACTIVITY_CATCH_NICE_THROW = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_NICE_THROW)
const ActivityType_ACTIVITY_CATCH_GREAT_THROW = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_GREAT_THROW)
const ActivityType_ACTIVITY_CATCH_EXCELLENT_THROW = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_EXCELLENT_THROW)
const ActivityType_ACTIVITY_CATCH_CURVEBALL = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_CURVEBALL)
const ActivityType_ACTIVITY_CATCH_FIRST_CATCH_OF_DAY = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_FIRST_CATCH_OF_DAY)
const ActivityType_ACTIVITY_CATCH_MILESTONE = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_CATCH_MILESTONE)
const ActivityType_ACTIVITY_TRAIN_POKEMON = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_TRAIN_POKEMON)
const ActivityType_ACTIVITY_SEARCH_FORT = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_SEARCH_FORT)
const ActivityType_ACTIVITY_RELEASE_POKEMON = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_RELEASE_POKEMON)
const ActivityType_ACTIVITY_HATCH_EGG_SMALL_BONUS = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_HATCH_EGG_SMALL_BONUS)
const ActivityType_ACTIVITY_HATCH_EGG_MEDIUM_BONUS = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_HATCH_EGG_MEDIUM_BONUS)
const ActivityType_ACTIVITY_HATCH_EGG_LARGE_BONUS = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_HATCH_EGG_LARGE_BONUS)
const ActivityType_ACTIVITY_DEFEAT_GYM_DEFENDER = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_DEFEAT_GYM_DEFENDER)
const ActivityType_ACTIVITY_DEFEAT_GYM_LEADER = ActivityType(POGOProtos_Enums.ActivityType_ACTIVITY_DEFEAT_GYM_LEADER)

// BadgeType from public import enums/enums.proto
type BadgeType POGOProtos_Enums.BadgeType

var BadgeType_name = POGOProtos_Enums.BadgeType_name
var BadgeType_value = POGOProtos_Enums.BadgeType_value

func (x BadgeType) String() string { return (POGOProtos_Enums.BadgeType)(x).String() }

const BadgeType_BADGE_UNSET = BadgeType(POGOProtos_Enums.BadgeType_BADGE_UNSET)
const BadgeType_BADGE_TRAVEL_KM = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TRAVEL_KM)
const BadgeType_BADGE_POKEDEX_ENTRIES = BadgeType(POGOProtos_Enums.BadgeType_BADGE_POKEDEX_ENTRIES)
const BadgeType_BADGE_CAPTURE_TOTAL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_CAPTURE_TOTAL)
const BadgeType_BADGE_DEFEATED_FORT = BadgeType(POGOProtos_Enums.BadgeType_BADGE_DEFEATED_FORT)
const BadgeType_BADGE_EVOLVED_TOTAL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_EVOLVED_TOTAL)
const BadgeType_BADGE_HATCHED_TOTAL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_HATCHED_TOTAL)
const BadgeType_BADGE_ENCOUNTERED_TOTAL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_ENCOUNTERED_TOTAL)
const BadgeType_BADGE_POKESTOPS_VISITED = BadgeType(POGOProtos_Enums.BadgeType_BADGE_POKESTOPS_VISITED)
const BadgeType_BADGE_UNIQUE_POKESTOPS = BadgeType(POGOProtos_Enums.BadgeType_BADGE_UNIQUE_POKESTOPS)
const BadgeType_BADGE_POKEBALL_THROWN = BadgeType(POGOProtos_Enums.BadgeType_BADGE_POKEBALL_THROWN)
const BadgeType_BADGE_BIG_MAGIKARP = BadgeType(POGOProtos_Enums.BadgeType_BADGE_BIG_MAGIKARP)
const BadgeType_BADGE_DEPLOYED_TOTAL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_DEPLOYED_TOTAL)
const BadgeType_BADGE_BATTLE_ATTACK_WON = BadgeType(POGOProtos_Enums.BadgeType_BADGE_BATTLE_ATTACK_WON)
const BadgeType_BADGE_BATTLE_TRAINING_WON = BadgeType(POGOProtos_Enums.BadgeType_BADGE_BATTLE_TRAINING_WON)
const BadgeType_BADGE_BATTLE_DEFEND_WON = BadgeType(POGOProtos_Enums.BadgeType_BADGE_BATTLE_DEFEND_WON)
const BadgeType_BADGE_PRESTIGE_RAISED = BadgeType(POGOProtos_Enums.BadgeType_BADGE_PRESTIGE_RAISED)
const BadgeType_BADGE_PRESTIGE_DROPPED = BadgeType(POGOProtos_Enums.BadgeType_BADGE_PRESTIGE_DROPPED)
const BadgeType_BADGE_TYPE_NORMAL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_NORMAL)
const BadgeType_BADGE_TYPE_FIGHTING = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_FIGHTING)
const BadgeType_BADGE_TYPE_FLYING = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_FLYING)
const BadgeType_BADGE_TYPE_POISON = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_POISON)
const BadgeType_BADGE_TYPE_GROUND = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_GROUND)
const BadgeType_BADGE_TYPE_ROCK = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_ROCK)
const BadgeType_BADGE_TYPE_BUG = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_BUG)
const BadgeType_BADGE_TYPE_GHOST = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_GHOST)
const BadgeType_BADGE_TYPE_STEEL = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_STEEL)
const BadgeType_BADGE_TYPE_FIRE = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_FIRE)
const BadgeType_BADGE_TYPE_WATER = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_WATER)
const BadgeType_BADGE_TYPE_GRASS = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_GRASS)
const BadgeType_BADGE_TYPE_ELECTRIC = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_ELECTRIC)
const BadgeType_BADGE_TYPE_PSYCHIC = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_PSYCHIC)
const BadgeType_BADGE_TYPE_ICE = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_ICE)
const BadgeType_BADGE_TYPE_DRAGON = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_DRAGON)
const BadgeType_BADGE_TYPE_DARK = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_DARK)
const BadgeType_BADGE_TYPE_FAIRY = BadgeType(POGOProtos_Enums.BadgeType_BADGE_TYPE_FAIRY)
const BadgeType_BADGE_SMALL_RATTATA = BadgeType(POGOProtos_Enums.BadgeType_BADGE_SMALL_RATTATA)
const BadgeType_BADGE_PIKACHU = BadgeType(POGOProtos_Enums.BadgeType_BADGE_PIKACHU)

// CameraInterpolation from public import enums/enums.proto
type CameraInterpolation POGOProtos_Enums.CameraInterpolation

var CameraInterpolation_name = POGOProtos_Enums.CameraInterpolation_name
var CameraInterpolation_value = POGOProtos_Enums.CameraInterpolation_value

func (x CameraInterpolation) String() string {
	return (POGOProtos_Enums.CameraInterpolation)(x).String()
}

const CameraInterpolation_CAM_INTERP_CUT = CameraInterpolation(POGOProtos_Enums.CameraInterpolation_CAM_INTERP_CUT)
const CameraInterpolation_CAM_INTERP_LINEAR = CameraInterpolation(POGOProtos_Enums.CameraInterpolation_CAM_INTERP_LINEAR)
const CameraInterpolation_CAM_INTERP_SMOOTH = CameraInterpolation(POGOProtos_Enums.CameraInterpolation_CAM_INTERP_SMOOTH)
const CameraInterpolation_CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = CameraInterpolation(POGOProtos_Enums.CameraInterpolation_CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE)
const CameraInterpolation_CAM_INTERP_DEPENDS = CameraInterpolation(POGOProtos_Enums.CameraInterpolation_CAM_INTERP_DEPENDS)

// CameraTarget from public import enums/enums.proto
type CameraTarget POGOProtos_Enums.CameraTarget

var CameraTarget_name = POGOProtos_Enums.CameraTarget_name
var CameraTarget_value = POGOProtos_Enums.CameraTarget_value

func (x CameraTarget) String() string { return (POGOProtos_Enums.CameraTarget)(x).String() }

const CameraTarget_CAM_TARGET_ATTACKER = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER)
const CameraTarget_CAM_TARGET_ATTACKER_EDGE = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER_EDGE)
const CameraTarget_CAM_TARGET_ATTACKER_GROUND = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER_GROUND)
const CameraTarget_CAM_TARGET_DEFENDER = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_DEFENDER)
const CameraTarget_CAM_TARGET_DEFENDER_EDGE = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_DEFENDER_EDGE)
const CameraTarget_CAM_TARGET_DEFENDER_GROUND = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_DEFENDER_GROUND)
const CameraTarget_CAM_TARGET_ATTACKER_DEFENDER = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER_DEFENDER)
const CameraTarget_CAM_TARGET_ATTACKER_DEFENDER_EDGE = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER_DEFENDER_EDGE)
const CameraTarget_CAM_TARGET_DEFENDER_ATTACKER = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_DEFENDER_ATTACKER)
const CameraTarget_CAM_TARGET_DEFENDER_ATTACKER_EDGE = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_DEFENDER_ATTACKER_EDGE)
const CameraTarget_CAM_TARGET_ATTACKER_DEFENDER_MIRROR = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER_DEFENDER_MIRROR)
const CameraTarget_CAM_TARGET_SHOULDER_ATTACKER_DEFENDER = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_SHOULDER_ATTACKER_DEFENDER)
const CameraTarget_CAM_TARGET_SHOULDER_ATTACKER_DEFENDER_MIRROR = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_SHOULDER_ATTACKER_DEFENDER_MIRROR)
const CameraTarget_CAM_TARGET_ATTACKER_DEFENDER_WORLD = CameraTarget(POGOProtos_Enums.CameraTarget_CAM_TARGET_ATTACKER_DEFENDER_WORLD)

// Gender from public import enums/enums.proto
type Gender POGOProtos_Enums.Gender

var Gender_name = POGOProtos_Enums.Gender_name
var Gender_value = POGOProtos_Enums.Gender_value

func (x Gender) String() string { return (POGOProtos_Enums.Gender)(x).String() }

const Gender_MALE = Gender(POGOProtos_Enums.Gender_MALE)
const Gender_FEMALE = Gender(POGOProtos_Enums.Gender_FEMALE)

// HoloIapItemCategory from public import enums/enums.proto
type HoloIapItemCategory POGOProtos_Enums.HoloIapItemCategory

var HoloIapItemCategory_name = POGOProtos_Enums.HoloIapItemCategory_name
var HoloIapItemCategory_value = POGOProtos_Enums.HoloIapItemCategory_value

func (x HoloIapItemCategory) String() string {
	return (POGOProtos_Enums.HoloIapItemCategory)(x).String()
}

const HoloIapItemCategory_IAP_CATEGORY_NONE = HoloIapItemCategory(POGOProtos_Enums.HoloIapItemCategory_IAP_CATEGORY_NONE)
const HoloIapItemCategory_IAP_CATEGORY_BUNDLE = HoloIapItemCategory(POGOProtos_Enums.HoloIapItemCategory_IAP_CATEGORY_BUNDLE)
const HoloIapItemCategory_IAP_CATEGORY_ITEMS = HoloIapItemCategory(POGOProtos_Enums.HoloIapItemCategory_IAP_CATEGORY_ITEMS)
const HoloIapItemCategory_IAP_CATEGORY_UPGRADES = HoloIapItemCategory(POGOProtos_Enums.HoloIapItemCategory_IAP_CATEGORY_UPGRADES)
const HoloIapItemCategory_IAP_CATEGORY_POKECOINS = HoloIapItemCategory(POGOProtos_Enums.HoloIapItemCategory_IAP_CATEGORY_POKECOINS)

// ItemCategory from public import enums/enums.proto
type ItemCategory POGOProtos_Enums.ItemCategory

var ItemCategory_name = POGOProtos_Enums.ItemCategory_name
var ItemCategory_value = POGOProtos_Enums.ItemCategory_value

func (x ItemCategory) String() string { return (POGOProtos_Enums.ItemCategory)(x).String() }

const ItemCategory_ITEM_CATEGORY_NONE = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_NONE)
const ItemCategory_ITEM_CATEGORY_POKEBALL = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_POKEBALL)
const ItemCategory_ITEM_CATEGORY_FOOD = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_FOOD)
const ItemCategory_ITEM_CATEGORY_MEDICINE = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_MEDICINE)
const ItemCategory_ITEM_CATEGORY_BOOST = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_BOOST)
const ItemCategory_ITEM_CATEGORY_UTILITES = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_UTILITES)
const ItemCategory_ITEM_CATEGORY_CAMERA = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_CAMERA)
const ItemCategory_ITEM_CATEGORY_DISK = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_DISK)
const ItemCategory_ITEM_CATEGORY_INCUBATOR = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_INCUBATOR)
const ItemCategory_ITEM_CATEGORY_INCENSE = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_INCENSE)
const ItemCategory_ITEM_CATEGORY_XP_BOOST = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_XP_BOOST)
const ItemCategory_ITEM_CATEGORY_INVENTORY_UPGRADE = ItemCategory(POGOProtos_Enums.ItemCategory_ITEM_CATEGORY_INVENTORY_UPGRADE)

// ItemEffect from public import enums/enums.proto
type ItemEffect POGOProtos_Enums.ItemEffect

var ItemEffect_name = POGOProtos_Enums.ItemEffect_name
var ItemEffect_value = POGOProtos_Enums.ItemEffect_value

func (x ItemEffect) String() string { return (POGOProtos_Enums.ItemEffect)(x).String() }

const ItemEffect_ITEM_EFFECT_NONE = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_NONE)
const ItemEffect_ITEM_EFFECT_CAP_NO_FLEE = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_NO_FLEE)
const ItemEffect_ITEM_EFFECT_CAP_NO_MOVEMENT = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_NO_MOVEMENT)
const ItemEffect_ITEM_EFFECT_CAP_NO_THREAT = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_NO_THREAT)
const ItemEffect_ITEM_EFFECT_CAP_TARGET_MAX = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_TARGET_MAX)
const ItemEffect_ITEM_EFFECT_CAP_TARGET_SLOW = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_TARGET_SLOW)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_NIGHT = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_NIGHT)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_TRAINER = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_TRAINER)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_FIRST_THROW = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_FIRST_THROW)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_LEGEND = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_LEGEND)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_HEAVY = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_HEAVY)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_REPEAT = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_REPEAT)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_MULTI_THROW = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_MULTI_THROW)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_ALWAYS = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_ALWAYS)
const ItemEffect_ITEM_EFFECT_CAP_CHANCE_SINGLE_THROW = ItemEffect(POGOProtos_Enums.ItemEffect_ITEM_EFFECT_CAP_CHANCE_SINGLE_THROW)

// Platform from public import enums/enums.proto
type Platform POGOProtos_Enums.Platform

var Platform_name = POGOProtos_Enums.Platform_name
var Platform_value = POGOProtos_Enums.Platform_value

func (x Platform) String() string { return (POGOProtos_Enums.Platform)(x).String() }

const Platform_UNSET = Platform(POGOProtos_Enums.Platform_UNSET)
const Platform_IOS = Platform(POGOProtos_Enums.Platform_IOS)
const Platform_ANDROID = Platform(POGOProtos_Enums.Platform_ANDROID)
const Platform_OSX = Platform(POGOProtos_Enums.Platform_OSX)
const Platform_WINDOWS = Platform(POGOProtos_Enums.Platform_WINDOWS)

// PokemonFamilyId from public import enums/enums.proto
type PokemonFamilyId POGOProtos_Enums.PokemonFamilyId

var PokemonFamilyId_name = POGOProtos_Enums.PokemonFamilyId_name
var PokemonFamilyId_value = POGOProtos_Enums.PokemonFamilyId_value

func (x PokemonFamilyId) String() string { return (POGOProtos_Enums.PokemonFamilyId)(x).String() }

const PokemonFamilyId_FAMILY_UNSET = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_UNSET)
const PokemonFamilyId_FAMILY_BULBASAUR = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_BULBASAUR)
const PokemonFamilyId_FAMILY_CHARMANDER = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_CHARMANDER)
const PokemonFamilyId_FAMILY_SQUIRTLE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SQUIRTLE)
const PokemonFamilyId_FAMILY_CATERPIE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_CATERPIE)
const PokemonFamilyId_FAMILY_WEEDLE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_WEEDLE)
const PokemonFamilyId_FAMILY_PIDGEY = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PIDGEY)
const PokemonFamilyId_FAMILY_RATTATA = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_RATTATA)
const PokemonFamilyId_FAMILY_SPEAROW = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SPEAROW)
const PokemonFamilyId_FAMILY_EKANS = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_EKANS)
const PokemonFamilyId_FAMILY_PIKACHU = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PIKACHU)
const PokemonFamilyId_FAMILY_SANDSHREW = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SANDSHREW)
const PokemonFamilyId_FAMILY_NIDORAN_FEMALE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_NIDORAN_FEMALE)
const PokemonFamilyId_FAMILY_NIDORAN_MALE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_NIDORAN_MALE)
const PokemonFamilyId_FAMILY_CLEFAIRY = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_CLEFAIRY)
const PokemonFamilyId_FAMILY_VULPIX = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_VULPIX)
const PokemonFamilyId_FAMILY_JIGGLYPUFF = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_JIGGLYPUFF)
const PokemonFamilyId_FAMILY_ZUBAT = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ZUBAT)
const PokemonFamilyId_FAMILY_ODDISH = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ODDISH)
const PokemonFamilyId_FAMILY_PARAS = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PARAS)
const PokemonFamilyId_FAMILY_VENONAT = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_VENONAT)
const PokemonFamilyId_FAMILY_DIGLETT = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_DIGLETT)
const PokemonFamilyId_FAMILY_MEOWTH = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MEOWTH)
const PokemonFamilyId_FAMILY_PSYDUCK = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PSYDUCK)
const PokemonFamilyId_FAMILY_MANKEY = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MANKEY)
const PokemonFamilyId_FAMILY_GROWLITHE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_GROWLITHE)
const PokemonFamilyId_FAMILY_POLIWAG = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_POLIWAG)
const PokemonFamilyId_FAMILY_ABRA = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ABRA)
const PokemonFamilyId_FAMILY_MACHOP = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MACHOP)
const PokemonFamilyId_FAMILY_BELLSPROUT = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_BELLSPROUT)
const PokemonFamilyId_FAMILY_TENTACOOL = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_TENTACOOL)
const PokemonFamilyId_FAMILY_GEODUDE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_GEODUDE)
const PokemonFamilyId_FAMILY_PONYTA = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PONYTA)
const PokemonFamilyId_FAMILY_SLOWPOKE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SLOWPOKE)
const PokemonFamilyId_FAMILY_MAGNEMITE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MAGNEMITE)
const PokemonFamilyId_FAMILY_FARFETCHD = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_FARFETCHD)
const PokemonFamilyId_FAMILY_DODUO = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_DODUO)
const PokemonFamilyId_FAMILY_SEEL = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SEEL)
const PokemonFamilyId_FAMILY_GRIMER = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_GRIMER)
const PokemonFamilyId_FAMILY_SHELLDER = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SHELLDER)
const PokemonFamilyId_FAMILY_GASTLY = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_GASTLY)
const PokemonFamilyId_FAMILY_ONIX = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ONIX)
const PokemonFamilyId_FAMILY_DROWZEE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_DROWZEE)
const PokemonFamilyId_FAMILY_HYPNO = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_HYPNO)
const PokemonFamilyId_FAMILY_KRABBY = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_KRABBY)
const PokemonFamilyId_FAMILY_VOLTORB = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_VOLTORB)
const PokemonFamilyId_FAMILY_EXEGGCUTE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_EXEGGCUTE)
const PokemonFamilyId_FAMILY_CUBONE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_CUBONE)
const PokemonFamilyId_FAMILY_HITMONLEE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_HITMONLEE)
const PokemonFamilyId_FAMILY_HITMONCHAN = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_HITMONCHAN)
const PokemonFamilyId_FAMILY_LICKITUNG = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_LICKITUNG)
const PokemonFamilyId_FAMILY_KOFFING = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_KOFFING)
const PokemonFamilyId_FAMILY_RHYHORN = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_RHYHORN)
const PokemonFamilyId_FAMILY_CHANSEY = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_CHANSEY)
const PokemonFamilyId_FAMILY_TANGELA = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_TANGELA)
const PokemonFamilyId_FAMILY_KANGASKHAN = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_KANGASKHAN)
const PokemonFamilyId_FAMILY_HORSEA = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_HORSEA)
const PokemonFamilyId_FAMILY_GOLDEEN = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_GOLDEEN)
const PokemonFamilyId_FAMILY_STARYU = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_STARYU)
const PokemonFamilyId_FAMILY_MR_MIME = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MR_MIME)
const PokemonFamilyId_FAMILY_SCYTHER = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SCYTHER)
const PokemonFamilyId_FAMILY_JYNX = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_JYNX)
const PokemonFamilyId_FAMILY_ELECTABUZZ = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ELECTABUZZ)
const PokemonFamilyId_FAMILY_MAGMAR = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MAGMAR)
const PokemonFamilyId_FAMILY_PINSIR = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PINSIR)
const PokemonFamilyId_FAMILY_TAUROS = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_TAUROS)
const PokemonFamilyId_FAMILY_MAGIKARP = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MAGIKARP)
const PokemonFamilyId_FAMILY_LAPRAS = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_LAPRAS)
const PokemonFamilyId_FAMILY_DITTO = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_DITTO)
const PokemonFamilyId_FAMILY_EEVEE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_EEVEE)
const PokemonFamilyId_FAMILY_PORYGON = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_PORYGON)
const PokemonFamilyId_FAMILY_OMANYTE = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_OMANYTE)
const PokemonFamilyId_FAMILY_KABUTO = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_KABUTO)
const PokemonFamilyId_FAMILY_AERODACTYL = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_AERODACTYL)
const PokemonFamilyId_FAMILY_SNORLAX = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_SNORLAX)
const PokemonFamilyId_FAMILY_ARTICUNO = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ARTICUNO)
const PokemonFamilyId_FAMILY_ZAPDOS = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_ZAPDOS)
const PokemonFamilyId_FAMILY_MOLTRES = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MOLTRES)
const PokemonFamilyId_FAMILY_DRATINI = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_DRATINI)
const PokemonFamilyId_FAMILY_MEWTWO = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MEWTWO)
const PokemonFamilyId_FAMILY_MEW = PokemonFamilyId(POGOProtos_Enums.PokemonFamilyId_FAMILY_MEW)

// PokemonId from public import enums/enums.proto
type PokemonId POGOProtos_Enums.PokemonId

var PokemonId_name = POGOProtos_Enums.PokemonId_name
var PokemonId_value = POGOProtos_Enums.PokemonId_value

func (x PokemonId) String() string { return (POGOProtos_Enums.PokemonId)(x).String() }

const PokemonId_MISSINGNO = PokemonId(POGOProtos_Enums.PokemonId_MISSINGNO)
const PokemonId_BULBASAUR = PokemonId(POGOProtos_Enums.PokemonId_BULBASAUR)
const PokemonId_IVYSAUR = PokemonId(POGOProtos_Enums.PokemonId_IVYSAUR)
const PokemonId_VENUSAUR = PokemonId(POGOProtos_Enums.PokemonId_VENUSAUR)
const PokemonId_CHARMANDER = PokemonId(POGOProtos_Enums.PokemonId_CHARMANDER)
const PokemonId_CHARMELEON = PokemonId(POGOProtos_Enums.PokemonId_CHARMELEON)
const PokemonId_CHARIZARD = PokemonId(POGOProtos_Enums.PokemonId_CHARIZARD)
const PokemonId_SQUIRTLE = PokemonId(POGOProtos_Enums.PokemonId_SQUIRTLE)
const PokemonId_WARTORTLE = PokemonId(POGOProtos_Enums.PokemonId_WARTORTLE)
const PokemonId_BLASTOISE = PokemonId(POGOProtos_Enums.PokemonId_BLASTOISE)
const PokemonId_CATERPIE = PokemonId(POGOProtos_Enums.PokemonId_CATERPIE)
const PokemonId_METAPOD = PokemonId(POGOProtos_Enums.PokemonId_METAPOD)
const PokemonId_BUTTERFREE = PokemonId(POGOProtos_Enums.PokemonId_BUTTERFREE)
const PokemonId_WEEDLE = PokemonId(POGOProtos_Enums.PokemonId_WEEDLE)
const PokemonId_KAKUNA = PokemonId(POGOProtos_Enums.PokemonId_KAKUNA)
const PokemonId_BEEDRILL = PokemonId(POGOProtos_Enums.PokemonId_BEEDRILL)
const PokemonId_PIDGEY = PokemonId(POGOProtos_Enums.PokemonId_PIDGEY)
const PokemonId_PIDGEOTTO = PokemonId(POGOProtos_Enums.PokemonId_PIDGEOTTO)
const PokemonId_PIDGEOT = PokemonId(POGOProtos_Enums.PokemonId_PIDGEOT)
const PokemonId_RATTATA = PokemonId(POGOProtos_Enums.PokemonId_RATTATA)
const PokemonId_RATICATE = PokemonId(POGOProtos_Enums.PokemonId_RATICATE)
const PokemonId_SPEAROW = PokemonId(POGOProtos_Enums.PokemonId_SPEAROW)
const PokemonId_FEAROW = PokemonId(POGOProtos_Enums.PokemonId_FEAROW)
const PokemonId_EKANS = PokemonId(POGOProtos_Enums.PokemonId_EKANS)
const PokemonId_ARBOK = PokemonId(POGOProtos_Enums.PokemonId_ARBOK)
const PokemonId_PIKACHU = PokemonId(POGOProtos_Enums.PokemonId_PIKACHU)
const PokemonId_RAICHU = PokemonId(POGOProtos_Enums.PokemonId_RAICHU)
const PokemonId_SANDSHREW = PokemonId(POGOProtos_Enums.PokemonId_SANDSHREW)
const PokemonId_SANDSLASH = PokemonId(POGOProtos_Enums.PokemonId_SANDSLASH)
const PokemonId_NIDORAN_FEMALE = PokemonId(POGOProtos_Enums.PokemonId_NIDORAN_FEMALE)
const PokemonId_NIDORINA = PokemonId(POGOProtos_Enums.PokemonId_NIDORINA)
const PokemonId_NIDOQUEEN = PokemonId(POGOProtos_Enums.PokemonId_NIDOQUEEN)
const PokemonId_NIDORAN_MALE = PokemonId(POGOProtos_Enums.PokemonId_NIDORAN_MALE)
const PokemonId_NIDORINO = PokemonId(POGOProtos_Enums.PokemonId_NIDORINO)
const PokemonId_NIDOKING = PokemonId(POGOProtos_Enums.PokemonId_NIDOKING)
const PokemonId_CLEFAIRY = PokemonId(POGOProtos_Enums.PokemonId_CLEFAIRY)
const PokemonId_CLEFABLE = PokemonId(POGOProtos_Enums.PokemonId_CLEFABLE)
const PokemonId_VULPIX = PokemonId(POGOProtos_Enums.PokemonId_VULPIX)
const PokemonId_NINETALES = PokemonId(POGOProtos_Enums.PokemonId_NINETALES)
const PokemonId_JIGGLYPUFF = PokemonId(POGOProtos_Enums.PokemonId_JIGGLYPUFF)
const PokemonId_WIGGLYTUFF = PokemonId(POGOProtos_Enums.PokemonId_WIGGLYTUFF)
const PokemonId_ZUBAT = PokemonId(POGOProtos_Enums.PokemonId_ZUBAT)
const PokemonId_GOLBAT = PokemonId(POGOProtos_Enums.PokemonId_GOLBAT)
const PokemonId_ODDISH = PokemonId(POGOProtos_Enums.PokemonId_ODDISH)
const PokemonId_GLOOM = PokemonId(POGOProtos_Enums.PokemonId_GLOOM)
const PokemonId_VILEPLUME = PokemonId(POGOProtos_Enums.PokemonId_VILEPLUME)
const PokemonId_PARAS = PokemonId(POGOProtos_Enums.PokemonId_PARAS)
const PokemonId_PARASECT = PokemonId(POGOProtos_Enums.PokemonId_PARASECT)
const PokemonId_VENONAT = PokemonId(POGOProtos_Enums.PokemonId_VENONAT)
const PokemonId_VENOMOTH = PokemonId(POGOProtos_Enums.PokemonId_VENOMOTH)
const PokemonId_DIGLETT = PokemonId(POGOProtos_Enums.PokemonId_DIGLETT)
const PokemonId_DUGTRIO = PokemonId(POGOProtos_Enums.PokemonId_DUGTRIO)
const PokemonId_MEOWTH = PokemonId(POGOProtos_Enums.PokemonId_MEOWTH)
const PokemonId_PERSIAN = PokemonId(POGOProtos_Enums.PokemonId_PERSIAN)
const PokemonId_PSYDUCK = PokemonId(POGOProtos_Enums.PokemonId_PSYDUCK)
const PokemonId_GOLDUCK = PokemonId(POGOProtos_Enums.PokemonId_GOLDUCK)
const PokemonId_MANKEY = PokemonId(POGOProtos_Enums.PokemonId_MANKEY)
const PokemonId_PRIMEAPE = PokemonId(POGOProtos_Enums.PokemonId_PRIMEAPE)
const PokemonId_GROWLITHE = PokemonId(POGOProtos_Enums.PokemonId_GROWLITHE)
const PokemonId_ARCANINE = PokemonId(POGOProtos_Enums.PokemonId_ARCANINE)
const PokemonId_POLIWAG = PokemonId(POGOProtos_Enums.PokemonId_POLIWAG)
const PokemonId_POLIWHIRL = PokemonId(POGOProtos_Enums.PokemonId_POLIWHIRL)
const PokemonId_POLIWRATH = PokemonId(POGOProtos_Enums.PokemonId_POLIWRATH)
const PokemonId_ABRA = PokemonId(POGOProtos_Enums.PokemonId_ABRA)
const PokemonId_KADABRA = PokemonId(POGOProtos_Enums.PokemonId_KADABRA)
const PokemonId_ALAKAZAM = PokemonId(POGOProtos_Enums.PokemonId_ALAKAZAM)
const PokemonId_MACHOP = PokemonId(POGOProtos_Enums.PokemonId_MACHOP)
const PokemonId_MACHOKE = PokemonId(POGOProtos_Enums.PokemonId_MACHOKE)
const PokemonId_MACHAMP = PokemonId(POGOProtos_Enums.PokemonId_MACHAMP)
const PokemonId_BELLSPROUT = PokemonId(POGOProtos_Enums.PokemonId_BELLSPROUT)
const PokemonId_WEEPINBELL = PokemonId(POGOProtos_Enums.PokemonId_WEEPINBELL)
const PokemonId_VICTREEBEL = PokemonId(POGOProtos_Enums.PokemonId_VICTREEBEL)
const PokemonId_TENTACOOL = PokemonId(POGOProtos_Enums.PokemonId_TENTACOOL)
const PokemonId_TENTACRUEL = PokemonId(POGOProtos_Enums.PokemonId_TENTACRUEL)
const PokemonId_GEODUDE = PokemonId(POGOProtos_Enums.PokemonId_GEODUDE)
const PokemonId_GRAVELER = PokemonId(POGOProtos_Enums.PokemonId_GRAVELER)
const PokemonId_GOLEM = PokemonId(POGOProtos_Enums.PokemonId_GOLEM)
const PokemonId_PONYTA = PokemonId(POGOProtos_Enums.PokemonId_PONYTA)
const PokemonId_RAPIDASH = PokemonId(POGOProtos_Enums.PokemonId_RAPIDASH)
const PokemonId_SLOWPOKE = PokemonId(POGOProtos_Enums.PokemonId_SLOWPOKE)
const PokemonId_SLOWBRO = PokemonId(POGOProtos_Enums.PokemonId_SLOWBRO)
const PokemonId_MAGNEMITE = PokemonId(POGOProtos_Enums.PokemonId_MAGNEMITE)
const PokemonId_MAGNETON = PokemonId(POGOProtos_Enums.PokemonId_MAGNETON)
const PokemonId_FARFETCHD = PokemonId(POGOProtos_Enums.PokemonId_FARFETCHD)
const PokemonId_DODUO = PokemonId(POGOProtos_Enums.PokemonId_DODUO)
const PokemonId_DODRIO = PokemonId(POGOProtos_Enums.PokemonId_DODRIO)
const PokemonId_SEEL = PokemonId(POGOProtos_Enums.PokemonId_SEEL)
const PokemonId_DEWGONG = PokemonId(POGOProtos_Enums.PokemonId_DEWGONG)
const PokemonId_GRIMER = PokemonId(POGOProtos_Enums.PokemonId_GRIMER)
const PokemonId_MUK = PokemonId(POGOProtos_Enums.PokemonId_MUK)
const PokemonId_SHELLDER = PokemonId(POGOProtos_Enums.PokemonId_SHELLDER)
const PokemonId_CLOYSTER = PokemonId(POGOProtos_Enums.PokemonId_CLOYSTER)
const PokemonId_GASTLY = PokemonId(POGOProtos_Enums.PokemonId_GASTLY)
const PokemonId_HAUNTER = PokemonId(POGOProtos_Enums.PokemonId_HAUNTER)
const PokemonId_GENGAR = PokemonId(POGOProtos_Enums.PokemonId_GENGAR)
const PokemonId_ONIX = PokemonId(POGOProtos_Enums.PokemonId_ONIX)
const PokemonId_DROWZEE = PokemonId(POGOProtos_Enums.PokemonId_DROWZEE)
const PokemonId_HYPNO = PokemonId(POGOProtos_Enums.PokemonId_HYPNO)
const PokemonId_KRABBY = PokemonId(POGOProtos_Enums.PokemonId_KRABBY)
const PokemonId_KINGLER = PokemonId(POGOProtos_Enums.PokemonId_KINGLER)
const PokemonId_VOLTORB = PokemonId(POGOProtos_Enums.PokemonId_VOLTORB)
const PokemonId_ELECTRODE = PokemonId(POGOProtos_Enums.PokemonId_ELECTRODE)
const PokemonId_EXEGGCUTE = PokemonId(POGOProtos_Enums.PokemonId_EXEGGCUTE)
const PokemonId_EXEGGUTOR = PokemonId(POGOProtos_Enums.PokemonId_EXEGGUTOR)
const PokemonId_CUBONE = PokemonId(POGOProtos_Enums.PokemonId_CUBONE)
const PokemonId_MAROWAK = PokemonId(POGOProtos_Enums.PokemonId_MAROWAK)
const PokemonId_HITMONLEE = PokemonId(POGOProtos_Enums.PokemonId_HITMONLEE)
const PokemonId_HITMONCHAN = PokemonId(POGOProtos_Enums.PokemonId_HITMONCHAN)
const PokemonId_LICKITUNG = PokemonId(POGOProtos_Enums.PokemonId_LICKITUNG)
const PokemonId_KOFFING = PokemonId(POGOProtos_Enums.PokemonId_KOFFING)
const PokemonId_WEEZING = PokemonId(POGOProtos_Enums.PokemonId_WEEZING)
const PokemonId_RHYHORN = PokemonId(POGOProtos_Enums.PokemonId_RHYHORN)
const PokemonId_RHYDON = PokemonId(POGOProtos_Enums.PokemonId_RHYDON)
const PokemonId_CHANSEY = PokemonId(POGOProtos_Enums.PokemonId_CHANSEY)
const PokemonId_TANGELA = PokemonId(POGOProtos_Enums.PokemonId_TANGELA)
const PokemonId_KANGASKHAN = PokemonId(POGOProtos_Enums.PokemonId_KANGASKHAN)
const PokemonId_HORSEA = PokemonId(POGOProtos_Enums.PokemonId_HORSEA)
const PokemonId_SEADRA = PokemonId(POGOProtos_Enums.PokemonId_SEADRA)
const PokemonId_GOLDEEN = PokemonId(POGOProtos_Enums.PokemonId_GOLDEEN)
const PokemonId_SEAKING = PokemonId(POGOProtos_Enums.PokemonId_SEAKING)
const PokemonId_STARYU = PokemonId(POGOProtos_Enums.PokemonId_STARYU)
const PokemonId_STARMIE = PokemonId(POGOProtos_Enums.PokemonId_STARMIE)
const PokemonId_MR_MIME = PokemonId(POGOProtos_Enums.PokemonId_MR_MIME)
const PokemonId_SCYTHER = PokemonId(POGOProtos_Enums.PokemonId_SCYTHER)
const PokemonId_JYNX = PokemonId(POGOProtos_Enums.PokemonId_JYNX)
const PokemonId_ELECTABUZZ = PokemonId(POGOProtos_Enums.PokemonId_ELECTABUZZ)
const PokemonId_MAGMAR = PokemonId(POGOProtos_Enums.PokemonId_MAGMAR)
const PokemonId_PINSIR = PokemonId(POGOProtos_Enums.PokemonId_PINSIR)
const PokemonId_TAUROS = PokemonId(POGOProtos_Enums.PokemonId_TAUROS)
const PokemonId_MAGIKARP = PokemonId(POGOProtos_Enums.PokemonId_MAGIKARP)
const PokemonId_GYARADOS = PokemonId(POGOProtos_Enums.PokemonId_GYARADOS)
const PokemonId_LAPRAS = PokemonId(POGOProtos_Enums.PokemonId_LAPRAS)
const PokemonId_DITTO = PokemonId(POGOProtos_Enums.PokemonId_DITTO)
const PokemonId_EEVEE = PokemonId(POGOProtos_Enums.PokemonId_EEVEE)
const PokemonId_VAPOREON = PokemonId(POGOProtos_Enums.PokemonId_VAPOREON)
const PokemonId_JOLTEON = PokemonId(POGOProtos_Enums.PokemonId_JOLTEON)
const PokemonId_FLAREON = PokemonId(POGOProtos_Enums.PokemonId_FLAREON)
const PokemonId_PORYGON = PokemonId(POGOProtos_Enums.PokemonId_PORYGON)
const PokemonId_OMANYTE = PokemonId(POGOProtos_Enums.PokemonId_OMANYTE)
const PokemonId_OMASTAR = PokemonId(POGOProtos_Enums.PokemonId_OMASTAR)
const PokemonId_KABUTO = PokemonId(POGOProtos_Enums.PokemonId_KABUTO)
const PokemonId_KABUTOPS = PokemonId(POGOProtos_Enums.PokemonId_KABUTOPS)
const PokemonId_AERODACTYL = PokemonId(POGOProtos_Enums.PokemonId_AERODACTYL)
const PokemonId_SNORLAX = PokemonId(POGOProtos_Enums.PokemonId_SNORLAX)
const PokemonId_ARTICUNO = PokemonId(POGOProtos_Enums.PokemonId_ARTICUNO)
const PokemonId_ZAPDOS = PokemonId(POGOProtos_Enums.PokemonId_ZAPDOS)
const PokemonId_MOLTRES = PokemonId(POGOProtos_Enums.PokemonId_MOLTRES)
const PokemonId_DRATINI = PokemonId(POGOProtos_Enums.PokemonId_DRATINI)
const PokemonId_DRAGONAIR = PokemonId(POGOProtos_Enums.PokemonId_DRAGONAIR)
const PokemonId_DRAGONITE = PokemonId(POGOProtos_Enums.PokemonId_DRAGONITE)
const PokemonId_MEWTWO = PokemonId(POGOProtos_Enums.PokemonId_MEWTWO)
const PokemonId_MEW = PokemonId(POGOProtos_Enums.PokemonId_MEW)

// PokemonMove from public import enums/enums.proto
type PokemonMove POGOProtos_Enums.PokemonMove

var PokemonMove_name = POGOProtos_Enums.PokemonMove_name
var PokemonMove_value = POGOProtos_Enums.PokemonMove_value

func (x PokemonMove) String() string { return (POGOProtos_Enums.PokemonMove)(x).String() }

const PokemonMove_MOVE_UNSET = PokemonMove(POGOProtos_Enums.PokemonMove_MOVE_UNSET)
const PokemonMove_THUNDER_SHOCK = PokemonMove(POGOProtos_Enums.PokemonMove_THUNDER_SHOCK)
const PokemonMove_QUICK_ATTACK = PokemonMove(POGOProtos_Enums.PokemonMove_QUICK_ATTACK)
const PokemonMove_SCRATCH = PokemonMove(POGOProtos_Enums.PokemonMove_SCRATCH)
const PokemonMove_EMBER = PokemonMove(POGOProtos_Enums.PokemonMove_EMBER)
const PokemonMove_VINE_WHIP = PokemonMove(POGOProtos_Enums.PokemonMove_VINE_WHIP)
const PokemonMove_TACKLE = PokemonMove(POGOProtos_Enums.PokemonMove_TACKLE)
const PokemonMove_RAZOR_LEAF = PokemonMove(POGOProtos_Enums.PokemonMove_RAZOR_LEAF)
const PokemonMove_TAKE_DOWN = PokemonMove(POGOProtos_Enums.PokemonMove_TAKE_DOWN)
const PokemonMove_WATER_GUN = PokemonMove(POGOProtos_Enums.PokemonMove_WATER_GUN)
const PokemonMove_BITE = PokemonMove(POGOProtos_Enums.PokemonMove_BITE)
const PokemonMove_POUND = PokemonMove(POGOProtos_Enums.PokemonMove_POUND)
const PokemonMove_DOUBLE_SLAP = PokemonMove(POGOProtos_Enums.PokemonMove_DOUBLE_SLAP)
const PokemonMove_WRAP = PokemonMove(POGOProtos_Enums.PokemonMove_WRAP)
const PokemonMove_HYPER_BEAM = PokemonMove(POGOProtos_Enums.PokemonMove_HYPER_BEAM)
const PokemonMove_LICK = PokemonMove(POGOProtos_Enums.PokemonMove_LICK)
const PokemonMove_DARK_PULSE = PokemonMove(POGOProtos_Enums.PokemonMove_DARK_PULSE)
const PokemonMove_SMOG = PokemonMove(POGOProtos_Enums.PokemonMove_SMOG)
const PokemonMove_SLUDGE = PokemonMove(POGOProtos_Enums.PokemonMove_SLUDGE)
const PokemonMove_METAL_CLAW = PokemonMove(POGOProtos_Enums.PokemonMove_METAL_CLAW)
const PokemonMove_VICE_GRIP = PokemonMove(POGOProtos_Enums.PokemonMove_VICE_GRIP)
const PokemonMove_FLAME_WHEEL = PokemonMove(POGOProtos_Enums.PokemonMove_FLAME_WHEEL)
const PokemonMove_MEGAHORN = PokemonMove(POGOProtos_Enums.PokemonMove_MEGAHORN)
const PokemonMove_WING_ATTACK = PokemonMove(POGOProtos_Enums.PokemonMove_WING_ATTACK)
const PokemonMove_FLAMETHROWER = PokemonMove(POGOProtos_Enums.PokemonMove_FLAMETHROWER)
const PokemonMove_SUCKER_PUNCH = PokemonMove(POGOProtos_Enums.PokemonMove_SUCKER_PUNCH)
const PokemonMove_DIG = PokemonMove(POGOProtos_Enums.PokemonMove_DIG)
const PokemonMove_LOW_KICK = PokemonMove(POGOProtos_Enums.PokemonMove_LOW_KICK)
const PokemonMove_CROSS_CHOP = PokemonMove(POGOProtos_Enums.PokemonMove_CROSS_CHOP)
const PokemonMove_PSYCHO_CUT = PokemonMove(POGOProtos_Enums.PokemonMove_PSYCHO_CUT)
const PokemonMove_PSYBEAM = PokemonMove(POGOProtos_Enums.PokemonMove_PSYBEAM)
const PokemonMove_EARTHQUAKE = PokemonMove(POGOProtos_Enums.PokemonMove_EARTHQUAKE)
const PokemonMove_STONE_EDGE = PokemonMove(POGOProtos_Enums.PokemonMove_STONE_EDGE)
const PokemonMove_ICE_PUNCH = PokemonMove(POGOProtos_Enums.PokemonMove_ICE_PUNCH)
const PokemonMove_HEART_STAMP = PokemonMove(POGOProtos_Enums.PokemonMove_HEART_STAMP)
const PokemonMove_DISCHARGE = PokemonMove(POGOProtos_Enums.PokemonMove_DISCHARGE)
const PokemonMove_FLASH_CANNON = PokemonMove(POGOProtos_Enums.PokemonMove_FLASH_CANNON)
const PokemonMove_PECK = PokemonMove(POGOProtos_Enums.PokemonMove_PECK)
const PokemonMove_DRILL_PECK = PokemonMove(POGOProtos_Enums.PokemonMove_DRILL_PECK)
const PokemonMove_ICE_BEAM = PokemonMove(POGOProtos_Enums.PokemonMove_ICE_BEAM)
const PokemonMove_BLIZZARD = PokemonMove(POGOProtos_Enums.PokemonMove_BLIZZARD)
const PokemonMove_AIR_SLASH = PokemonMove(POGOProtos_Enums.PokemonMove_AIR_SLASH)
const PokemonMove_HEAT_WAVE = PokemonMove(POGOProtos_Enums.PokemonMove_HEAT_WAVE)
const PokemonMove_TWINEEDLE = PokemonMove(POGOProtos_Enums.PokemonMove_TWINEEDLE)
const PokemonMove_POISON_JAB = PokemonMove(POGOProtos_Enums.PokemonMove_POISON_JAB)
const PokemonMove_AERIAL_ACE = PokemonMove(POGOProtos_Enums.PokemonMove_AERIAL_ACE)
const PokemonMove_DRILL_RUN = PokemonMove(POGOProtos_Enums.PokemonMove_DRILL_RUN)
const PokemonMove_PETAL_BLIZZARD = PokemonMove(POGOProtos_Enums.PokemonMove_PETAL_BLIZZARD)
const PokemonMove_MEGA_DRAIN = PokemonMove(POGOProtos_Enums.PokemonMove_MEGA_DRAIN)
const PokemonMove_BUG_BUZZ = PokemonMove(POGOProtos_Enums.PokemonMove_BUG_BUZZ)
const PokemonMove_POISON_FANG = PokemonMove(POGOProtos_Enums.PokemonMove_POISON_FANG)
const PokemonMove_NIGHT_SLASH = PokemonMove(POGOProtos_Enums.PokemonMove_NIGHT_SLASH)
const PokemonMove_SLASH = PokemonMove(POGOProtos_Enums.PokemonMove_SLASH)
const PokemonMove_BUBBLE_BEAM = PokemonMove(POGOProtos_Enums.PokemonMove_BUBBLE_BEAM)
const PokemonMove_SUBMISSION = PokemonMove(POGOProtos_Enums.PokemonMove_SUBMISSION)
const PokemonMove_KARATE_CHOP = PokemonMove(POGOProtos_Enums.PokemonMove_KARATE_CHOP)
const PokemonMove_LOW_SWEEP = PokemonMove(POGOProtos_Enums.PokemonMove_LOW_SWEEP)
const PokemonMove_AQUA_JET = PokemonMove(POGOProtos_Enums.PokemonMove_AQUA_JET)
const PokemonMove_AQUA_TAIL = PokemonMove(POGOProtos_Enums.PokemonMove_AQUA_TAIL)
const PokemonMove_SEED_BOMB = PokemonMove(POGOProtos_Enums.PokemonMove_SEED_BOMB)
const PokemonMove_PSYSHOCK = PokemonMove(POGOProtos_Enums.PokemonMove_PSYSHOCK)
const PokemonMove_ROCK_THROW = PokemonMove(POGOProtos_Enums.PokemonMove_ROCK_THROW)
const PokemonMove_ANCIENT_POWER = PokemonMove(POGOProtos_Enums.PokemonMove_ANCIENT_POWER)
const PokemonMove_ROCK_TOMB = PokemonMove(POGOProtos_Enums.PokemonMove_ROCK_TOMB)
const PokemonMove_ROCK_SLIDE = PokemonMove(POGOProtos_Enums.PokemonMove_ROCK_SLIDE)
const PokemonMove_POWER_GEM = PokemonMove(POGOProtos_Enums.PokemonMove_POWER_GEM)
const PokemonMove_SHADOW_SNEAK = PokemonMove(POGOProtos_Enums.PokemonMove_SHADOW_SNEAK)
const PokemonMove_SHADOW_PUNCH = PokemonMove(POGOProtos_Enums.PokemonMove_SHADOW_PUNCH)
const PokemonMove_SHADOW_CLAW = PokemonMove(POGOProtos_Enums.PokemonMove_SHADOW_CLAW)
const PokemonMove_OMINOUS_WIND = PokemonMove(POGOProtos_Enums.PokemonMove_OMINOUS_WIND)
const PokemonMove_SHADOW_BALL = PokemonMove(POGOProtos_Enums.PokemonMove_SHADOW_BALL)
const PokemonMove_BULLET_PUNCH = PokemonMove(POGOProtos_Enums.PokemonMove_BULLET_PUNCH)
const PokemonMove_MAGNET_BOMB = PokemonMove(POGOProtos_Enums.PokemonMove_MAGNET_BOMB)
const PokemonMove_STEEL_WING = PokemonMove(POGOProtos_Enums.PokemonMove_STEEL_WING)
const PokemonMove_IRON_HEAD = PokemonMove(POGOProtos_Enums.PokemonMove_IRON_HEAD)
const PokemonMove_PARABOLIC_CHARGE = PokemonMove(POGOProtos_Enums.PokemonMove_PARABOLIC_CHARGE)
const PokemonMove_SPARK = PokemonMove(POGOProtos_Enums.PokemonMove_SPARK)
const PokemonMove_THUNDER_PUNCH = PokemonMove(POGOProtos_Enums.PokemonMove_THUNDER_PUNCH)
const PokemonMove_THUNDER = PokemonMove(POGOProtos_Enums.PokemonMove_THUNDER)
const PokemonMove_THUNDERBOLT = PokemonMove(POGOProtos_Enums.PokemonMove_THUNDERBOLT)
const PokemonMove_TWISTER = PokemonMove(POGOProtos_Enums.PokemonMove_TWISTER)
const PokemonMove_DRAGON_BREATH = PokemonMove(POGOProtos_Enums.PokemonMove_DRAGON_BREATH)
const PokemonMove_DRAGON_PULSE = PokemonMove(POGOProtos_Enums.PokemonMove_DRAGON_PULSE)
const PokemonMove_DRAGON_CLAW = PokemonMove(POGOProtos_Enums.PokemonMove_DRAGON_CLAW)
const PokemonMove_DISARMING_VOICE = PokemonMove(POGOProtos_Enums.PokemonMove_DISARMING_VOICE)
const PokemonMove_DRAINING_KISS = PokemonMove(POGOProtos_Enums.PokemonMove_DRAINING_KISS)
const PokemonMove_DAZZLING_GLEAM = PokemonMove(POGOProtos_Enums.PokemonMove_DAZZLING_GLEAM)
const PokemonMove_MOONBLAST = PokemonMove(POGOProtos_Enums.PokemonMove_MOONBLAST)
const PokemonMove_PLAY_ROUGH = PokemonMove(POGOProtos_Enums.PokemonMove_PLAY_ROUGH)
const PokemonMove_CROSS_POISON = PokemonMove(POGOProtos_Enums.PokemonMove_CROSS_POISON)
const PokemonMove_SLUDGE_BOMB = PokemonMove(POGOProtos_Enums.PokemonMove_SLUDGE_BOMB)
const PokemonMove_SLUDGE_WAVE = PokemonMove(POGOProtos_Enums.PokemonMove_SLUDGE_WAVE)
const PokemonMove_GUNK_SHOT = PokemonMove(POGOProtos_Enums.PokemonMove_GUNK_SHOT)
const PokemonMove_MUD_SHOT = PokemonMove(POGOProtos_Enums.PokemonMove_MUD_SHOT)
const PokemonMove_BONE_CLUB = PokemonMove(POGOProtos_Enums.PokemonMove_BONE_CLUB)
const PokemonMove_BULLDOZE = PokemonMove(POGOProtos_Enums.PokemonMove_BULLDOZE)
const PokemonMove_MUD_BOMB = PokemonMove(POGOProtos_Enums.PokemonMove_MUD_BOMB)
const PokemonMove_FURY_CUTTER = PokemonMove(POGOProtos_Enums.PokemonMove_FURY_CUTTER)
const PokemonMove_BUG_BITE = PokemonMove(POGOProtos_Enums.PokemonMove_BUG_BITE)
const PokemonMove_SIGNAL_BEAM = PokemonMove(POGOProtos_Enums.PokemonMove_SIGNAL_BEAM)
const PokemonMove_X_SCISSOR = PokemonMove(POGOProtos_Enums.PokemonMove_X_SCISSOR)
const PokemonMove_FLAME_CHARGE = PokemonMove(POGOProtos_Enums.PokemonMove_FLAME_CHARGE)
const PokemonMove_FLAME_BURST = PokemonMove(POGOProtos_Enums.PokemonMove_FLAME_BURST)
const PokemonMove_FIRE_BLAST = PokemonMove(POGOProtos_Enums.PokemonMove_FIRE_BLAST)
const PokemonMove_BRINE = PokemonMove(POGOProtos_Enums.PokemonMove_BRINE)
const PokemonMove_WATER_PULSE = PokemonMove(POGOProtos_Enums.PokemonMove_WATER_PULSE)
const PokemonMove_SCALD = PokemonMove(POGOProtos_Enums.PokemonMove_SCALD)
const PokemonMove_HYDRO_PUMP = PokemonMove(POGOProtos_Enums.PokemonMove_HYDRO_PUMP)
const PokemonMove_PSYCHIC = PokemonMove(POGOProtos_Enums.PokemonMove_PSYCHIC)
const PokemonMove_PSYSTRIKE = PokemonMove(POGOProtos_Enums.PokemonMove_PSYSTRIKE)
const PokemonMove_ICE_SHARD = PokemonMove(POGOProtos_Enums.PokemonMove_ICE_SHARD)
const PokemonMove_ICY_WIND = PokemonMove(POGOProtos_Enums.PokemonMove_ICY_WIND)
const PokemonMove_FROST_BREATH = PokemonMove(POGOProtos_Enums.PokemonMove_FROST_BREATH)
const PokemonMove_ABSORB = PokemonMove(POGOProtos_Enums.PokemonMove_ABSORB)
const PokemonMove_GIGA_DRAIN = PokemonMove(POGOProtos_Enums.PokemonMove_GIGA_DRAIN)
const PokemonMove_FIRE_PUNCH = PokemonMove(POGOProtos_Enums.PokemonMove_FIRE_PUNCH)
const PokemonMove_SOLAR_BEAM = PokemonMove(POGOProtos_Enums.PokemonMove_SOLAR_BEAM)
const PokemonMove_LEAF_BLADE = PokemonMove(POGOProtos_Enums.PokemonMove_LEAF_BLADE)
const PokemonMove_POWER_WHIP = PokemonMove(POGOProtos_Enums.PokemonMove_POWER_WHIP)
const PokemonMove_SPLASH = PokemonMove(POGOProtos_Enums.PokemonMove_SPLASH)
const PokemonMove_ACID = PokemonMove(POGOProtos_Enums.PokemonMove_ACID)
const PokemonMove_AIR_CUTTER = PokemonMove(POGOProtos_Enums.PokemonMove_AIR_CUTTER)
const PokemonMove_HURRICANE = PokemonMove(POGOProtos_Enums.PokemonMove_HURRICANE)
const PokemonMove_BRICK_BREAK = PokemonMove(POGOProtos_Enums.PokemonMove_BRICK_BREAK)
const PokemonMove_CUT = PokemonMove(POGOProtos_Enums.PokemonMove_CUT)
const PokemonMove_SWIFT = PokemonMove(POGOProtos_Enums.PokemonMove_SWIFT)
const PokemonMove_HORN_ATTACK = PokemonMove(POGOProtos_Enums.PokemonMove_HORN_ATTACK)
const PokemonMove_STOMP = PokemonMove(POGOProtos_Enums.PokemonMove_STOMP)
const PokemonMove_HEADBUTT = PokemonMove(POGOProtos_Enums.PokemonMove_HEADBUTT)
const PokemonMove_HYPER_FANG = PokemonMove(POGOProtos_Enums.PokemonMove_HYPER_FANG)
const PokemonMove_SLAM = PokemonMove(POGOProtos_Enums.PokemonMove_SLAM)
const PokemonMove_BODY_SLAM = PokemonMove(POGOProtos_Enums.PokemonMove_BODY_SLAM)
const PokemonMove_REST = PokemonMove(POGOProtos_Enums.PokemonMove_REST)
const PokemonMove_STRUGGLE = PokemonMove(POGOProtos_Enums.PokemonMove_STRUGGLE)
const PokemonMove_SCALD_BLASTOISE = PokemonMove(POGOProtos_Enums.PokemonMove_SCALD_BLASTOISE)
const PokemonMove_HYDRO_PUMP_BLASTOISE = PokemonMove(POGOProtos_Enums.PokemonMove_HYDRO_PUMP_BLASTOISE)
const PokemonMove_WRAP_GREEN = PokemonMove(POGOProtos_Enums.PokemonMove_WRAP_GREEN)
const PokemonMove_WRAP_PINK = PokemonMove(POGOProtos_Enums.PokemonMove_WRAP_PINK)
const PokemonMove_FURY_CUTTER_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_FURY_CUTTER_FAST)
const PokemonMove_BUG_BITE_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_BUG_BITE_FAST)
const PokemonMove_BITE_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_BITE_FAST)
const PokemonMove_SUCKER_PUNCH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_SUCKER_PUNCH_FAST)
const PokemonMove_DRAGON_BREATH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_DRAGON_BREATH_FAST)
const PokemonMove_THUNDER_SHOCK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_THUNDER_SHOCK_FAST)
const PokemonMove_SPARK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_SPARK_FAST)
const PokemonMove_LOW_KICK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_LOW_KICK_FAST)
const PokemonMove_KARATE_CHOP_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_KARATE_CHOP_FAST)
const PokemonMove_EMBER_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_EMBER_FAST)
const PokemonMove_WING_ATTACK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_WING_ATTACK_FAST)
const PokemonMove_PECK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_PECK_FAST)
const PokemonMove_LICK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_LICK_FAST)
const PokemonMove_SHADOW_CLAW_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_SHADOW_CLAW_FAST)
const PokemonMove_VINE_WHIP_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_VINE_WHIP_FAST)
const PokemonMove_RAZOR_LEAF_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_RAZOR_LEAF_FAST)
const PokemonMove_MUD_SHOT_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_MUD_SHOT_FAST)
const PokemonMove_ICE_SHARD_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_ICE_SHARD_FAST)
const PokemonMove_FROST_BREATH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_FROST_BREATH_FAST)
const PokemonMove_QUICK_ATTACK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_QUICK_ATTACK_FAST)
const PokemonMove_SCRATCH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_SCRATCH_FAST)
const PokemonMove_TACKLE_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_TACKLE_FAST)
const PokemonMove_POUND_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_POUND_FAST)
const PokemonMove_CUT_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_CUT_FAST)
const PokemonMove_POISON_JAB_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_POISON_JAB_FAST)
const PokemonMove_ACID_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_ACID_FAST)
const PokemonMove_PSYCHO_CUT_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_PSYCHO_CUT_FAST)
const PokemonMove_ROCK_THROW_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_ROCK_THROW_FAST)
const PokemonMove_METAL_CLAW_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_METAL_CLAW_FAST)
const PokemonMove_BULLET_PUNCH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_BULLET_PUNCH_FAST)
const PokemonMove_WATER_GUN_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_WATER_GUN_FAST)
const PokemonMove_SPLASH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_SPLASH_FAST)
const PokemonMove_WATER_GUN_FAST_BLASTOISE = PokemonMove(POGOProtos_Enums.PokemonMove_WATER_GUN_FAST_BLASTOISE)
const PokemonMove_MUD_SLAP_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_MUD_SLAP_FAST)
const PokemonMove_ZEN_HEADBUTT_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_ZEN_HEADBUTT_FAST)
const PokemonMove_CONFUSION_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_CONFUSION_FAST)
const PokemonMove_POISON_STING_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_POISON_STING_FAST)
const PokemonMove_BUBBLE_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_BUBBLE_FAST)
const PokemonMove_FEINT_ATTACK_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_FEINT_ATTACK_FAST)
const PokemonMove_STEEL_WING_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_STEEL_WING_FAST)
const PokemonMove_FIRE_FANG_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_FIRE_FANG_FAST)
const PokemonMove_ROCK_SMASH_FAST = PokemonMove(POGOProtos_Enums.PokemonMove_ROCK_SMASH_FAST)

// PokemonMovementType from public import enums/enums.proto
type PokemonMovementType POGOProtos_Enums.PokemonMovementType

var PokemonMovementType_name = POGOProtos_Enums.PokemonMovementType_name
var PokemonMovementType_value = POGOProtos_Enums.PokemonMovementType_value

func (x PokemonMovementType) String() string {
	return (POGOProtos_Enums.PokemonMovementType)(x).String()
}

const PokemonMovementType_MOVEMENT_STATIC = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_STATIC)
const PokemonMovementType_MOVEMENT_JUMP = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_JUMP)
const PokemonMovementType_MOVEMENT_VERTICAL = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_VERTICAL)
const PokemonMovementType_MOVEMENT_PSYCHIC = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_PSYCHIC)
const PokemonMovementType_MOVEMENT_ELECTRIC = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_ELECTRIC)
const PokemonMovementType_MOVEMENT_FLYING = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_FLYING)
const PokemonMovementType_MOVEMENT_HOVERING = PokemonMovementType(POGOProtos_Enums.PokemonMovementType_MOVEMENT_HOVERING)

// PokemonRarity from public import enums/enums.proto
type PokemonRarity POGOProtos_Enums.PokemonRarity

var PokemonRarity_name = POGOProtos_Enums.PokemonRarity_name
var PokemonRarity_value = POGOProtos_Enums.PokemonRarity_value

func (x PokemonRarity) String() string { return (POGOProtos_Enums.PokemonRarity)(x).String() }

const PokemonRarity_NORMAL = PokemonRarity(POGOProtos_Enums.PokemonRarity_NORMAL)
const PokemonRarity_LEGENDARY = PokemonRarity(POGOProtos_Enums.PokemonRarity_LEGENDARY)
const PokemonRarity_MYTHIC = PokemonRarity(POGOProtos_Enums.PokemonRarity_MYTHIC)

// PokemonType from public import enums/enums.proto
type PokemonType POGOProtos_Enums.PokemonType

var PokemonType_name = POGOProtos_Enums.PokemonType_name
var PokemonType_value = POGOProtos_Enums.PokemonType_value

func (x PokemonType) String() string { return (POGOProtos_Enums.PokemonType)(x).String() }

const PokemonType_POKEMON_TYPE_NONE = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_NONE)
const PokemonType_POKEMON_TYPE_NORMAL = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_NORMAL)
const PokemonType_POKEMON_TYPE_FIGHTING = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_FIGHTING)
const PokemonType_POKEMON_TYPE_FLYING = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_FLYING)
const PokemonType_POKEMON_TYPE_POISON = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_POISON)
const PokemonType_POKEMON_TYPE_GROUND = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_GROUND)
const PokemonType_POKEMON_TYPE_ROCK = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_ROCK)
const PokemonType_POKEMON_TYPE_BUG = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_BUG)
const PokemonType_POKEMON_TYPE_GHOST = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_GHOST)
const PokemonType_POKEMON_TYPE_STEEL = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_STEEL)
const PokemonType_POKEMON_TYPE_FIRE = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_FIRE)
const PokemonType_POKEMON_TYPE_WATER = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_WATER)
const PokemonType_POKEMON_TYPE_GRASS = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_GRASS)
const PokemonType_POKEMON_TYPE_ELECTRIC = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_ELECTRIC)
const PokemonType_POKEMON_TYPE_PSYCHIC = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_PSYCHIC)
const PokemonType_POKEMON_TYPE_ICE = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_ICE)
const PokemonType_POKEMON_TYPE_DRAGON = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_DRAGON)
const PokemonType_POKEMON_TYPE_DARK = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_DARK)
const PokemonType_POKEMON_TYPE_FAIRY = PokemonType(POGOProtos_Enums.PokemonType_POKEMON_TYPE_FAIRY)

// TeamColor from public import enums/enums.proto
type TeamColor POGOProtos_Enums.TeamColor

var TeamColor_name = POGOProtos_Enums.TeamColor_name
var TeamColor_value = POGOProtos_Enums.TeamColor_value

func (x TeamColor) String() string { return (POGOProtos_Enums.TeamColor)(x).String() }

const TeamColor_NEUTRAL = TeamColor(POGOProtos_Enums.TeamColor_NEUTRAL)
const TeamColor_BLUE = TeamColor(POGOProtos_Enums.TeamColor_BLUE)
const TeamColor_RED = TeamColor(POGOProtos_Enums.TeamColor_RED)
const TeamColor_YELLOW = TeamColor(POGOProtos_Enums.TeamColor_YELLOW)

// TutorialState from public import enums/enums.proto
type TutorialState POGOProtos_Enums.TutorialState

var TutorialState_name = POGOProtos_Enums.TutorialState_name
var TutorialState_value = POGOProtos_Enums.TutorialState_value

func (x TutorialState) String() string { return (POGOProtos_Enums.TutorialState)(x).String() }

const TutorialState_LEGAL_SCREEN = TutorialState(POGOProtos_Enums.TutorialState_LEGAL_SCREEN)
const TutorialState_AVATAR_SELECTION = TutorialState(POGOProtos_Enums.TutorialState_AVATAR_SELECTION)
const TutorialState_ACCOUNT_CREATION = TutorialState(POGOProtos_Enums.TutorialState_ACCOUNT_CREATION)
const TutorialState_POKEMON_CAPTURE = TutorialState(POGOProtos_Enums.TutorialState_POKEMON_CAPTURE)
const TutorialState_NAME_SELECTION = TutorialState(POGOProtos_Enums.TutorialState_NAME_SELECTION)
const TutorialState_POKEMON_BERRY = TutorialState(POGOProtos_Enums.TutorialState_POKEMON_BERRY)
const TutorialState_USE_ITEM = TutorialState(POGOProtos_Enums.TutorialState_USE_ITEM)
const TutorialState_FIRST_TIME_EXPERIENCE_COMPLETE = TutorialState(POGOProtos_Enums.TutorialState_FIRST_TIME_EXPERIENCE_COMPLETE)
const TutorialState_POKESTOP_TUTORIAL = TutorialState(POGOProtos_Enums.TutorialState_POKESTOP_TUTORIAL)
const TutorialState_GYM_TUTORIAL = TutorialState(POGOProtos_Enums.TutorialState_GYM_TUTORIAL)

type EggIncubatorType int32

const (
	EggIncubatorType_INCUBATOR_UNSET    EggIncubatorType = 0
	EggIncubatorType_INCUBATOR_DISTANCE EggIncubatorType = 1
)

var EggIncubatorType_name = map[int32]string{
	0: "INCUBATOR_UNSET",
	1: "INCUBATOR_DISTANCE",
}
var EggIncubatorType_value = map[string]int32{
	"INCUBATOR_UNSET":    0,
	"INCUBATOR_DISTANCE": 1,
}

func (x EggIncubatorType) String() string {
	return proto.EnumName(EggIncubatorType_name, int32(x))
}
func (EggIncubatorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InventoryUpgradeType int32

const (
	InventoryUpgradeType_UPGRADE_UNSET            InventoryUpgradeType = 0
	InventoryUpgradeType_INCREASE_ITEM_STORAGE    InventoryUpgradeType = 1
	InventoryUpgradeType_INCREASE_POKEMON_STORAGE InventoryUpgradeType = 2
)

var InventoryUpgradeType_name = map[int32]string{
	0: "UPGRADE_UNSET",
	1: "INCREASE_ITEM_STORAGE",
	2: "INCREASE_POKEMON_STORAGE",
}
var InventoryUpgradeType_value = map[string]int32{
	"UPGRADE_UNSET":            0,
	"INCREASE_ITEM_STORAGE":    1,
	"INCREASE_POKEMON_STORAGE": 2,
}

func (x InventoryUpgradeType) String() string {
	return proto.EnumName(InventoryUpgradeType_name, int32(x))
}
func (InventoryUpgradeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AppliedItem struct {
	ItemId    POGOProtos_Inventory_Item.ItemId   `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	ItemType  POGOProtos_Inventory_Item.ItemType `protobuf:"varint,2,opt,name=item_type,json=itemType,enum=POGOProtos.Inventory.Item.ItemType" json:"item_type,omitempty"`
	ExpireMs  int64                              `protobuf:"varint,3,opt,name=expire_ms,json=expireMs" json:"expire_ms,omitempty"`
	AppliedMs int64                              `protobuf:"varint,4,opt,name=applied_ms,json=appliedMs" json:"applied_ms,omitempty"`
}

func (m *AppliedItem) Reset()                    { *m = AppliedItem{} }
func (m *AppliedItem) String() string            { return proto.CompactTextString(m) }
func (*AppliedItem) ProtoMessage()               {}
func (*AppliedItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AppliedItems struct {
	Item []*AppliedItem `protobuf:"bytes,4,rep,name=item" json:"item,omitempty"`
}

func (m *AppliedItems) Reset()                    { *m = AppliedItems{} }
func (m *AppliedItems) String() string            { return proto.CompactTextString(m) }
func (*AppliedItems) ProtoMessage()               {}
func (*AppliedItems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppliedItems) GetItem() []*AppliedItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type EggIncubator struct {
	Id             string                           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ItemId         POGOProtos_Inventory_Item.ItemId `protobuf:"varint,2,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	IncubatorType  EggIncubatorType                 `protobuf:"varint,3,opt,name=incubator_type,json=incubatorType,enum=POGOProtos.Inventory.EggIncubatorType" json:"incubator_type,omitempty"`
	UsesRemaining  int32                            `protobuf:"varint,4,opt,name=uses_remaining,json=usesRemaining" json:"uses_remaining,omitempty"`
	PokemonId      uint64                           `protobuf:"varint,5,opt,name=pokemon_id,json=pokemonId" json:"pokemon_id,omitempty"`
	StartKmWalked  float64                          `protobuf:"fixed64,6,opt,name=start_km_walked,json=startKmWalked" json:"start_km_walked,omitempty"`
	TargetKmWalked float64                          `protobuf:"fixed64,7,opt,name=target_km_walked,json=targetKmWalked" json:"target_km_walked,omitempty"`
}

func (m *EggIncubator) Reset()                    { *m = EggIncubator{} }
func (m *EggIncubator) String() string            { return proto.CompactTextString(m) }
func (*EggIncubator) ProtoMessage()               {}
func (*EggIncubator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EggIncubators struct {
	EggIncubator []*EggIncubator `protobuf:"bytes,1,rep,name=egg_incubator,json=eggIncubator" json:"egg_incubator,omitempty"`
}

func (m *EggIncubators) Reset()                    { *m = EggIncubators{} }
func (m *EggIncubators) String() string            { return proto.CompactTextString(m) }
func (*EggIncubators) ProtoMessage()               {}
func (*EggIncubators) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EggIncubators) GetEggIncubator() []*EggIncubator {
	if m != nil {
		return m.EggIncubator
	}
	return nil
}

type InventoryDelta struct {
	OriginalTimestampMs int64            `protobuf:"varint,1,opt,name=original_timestamp_ms,json=originalTimestampMs" json:"original_timestamp_ms,omitempty"`
	NewTimestampMs      int64            `protobuf:"varint,2,opt,name=new_timestamp_ms,json=newTimestampMs" json:"new_timestamp_ms,omitempty"`
	InventoryItems      []*InventoryItem `protobuf:"bytes,3,rep,name=inventory_items,json=inventoryItems" json:"inventory_items,omitempty"`
}

func (m *InventoryDelta) Reset()                    { *m = InventoryDelta{} }
func (m *InventoryDelta) String() string            { return proto.CompactTextString(m) }
func (*InventoryDelta) ProtoMessage()               {}
func (*InventoryDelta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InventoryDelta) GetInventoryItems() []*InventoryItem {
	if m != nil {
		return m.InventoryItems
	}
	return nil
}

type InventoryItem struct {
	ModifiedTimestampMs int64              `protobuf:"varint,1,opt,name=modified_timestamp_ms,json=modifiedTimestampMs" json:"modified_timestamp_ms,omitempty"`
	DeletedItemKey      int64              `protobuf:"varint,2,opt,name=deleted_item_key,json=deletedItemKey" json:"deleted_item_key,omitempty"`
	InventoryItemData   *InventoryItemData `protobuf:"bytes,3,opt,name=inventory_item_data,json=inventoryItemData" json:"inventory_item_data,omitempty"`
}

func (m *InventoryItem) Reset()                    { *m = InventoryItem{} }
func (m *InventoryItem) String() string            { return proto.CompactTextString(m) }
func (*InventoryItem) ProtoMessage()               {}
func (*InventoryItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InventoryItem) GetInventoryItemData() *InventoryItemData {
	if m != nil {
		return m.InventoryItemData
	}
	return nil
}

type InventoryItemData struct {
	PokemonData       *POGOProtos_Data.PokemonData           `protobuf:"bytes,1,opt,name=pokemon_data,json=pokemonData" json:"pokemon_data,omitempty"`
	Item              *POGOProtos_Inventory_Item.ItemData    `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
	PokedexEntry      *POGOProtos_Data.PokedexEntry          `protobuf:"bytes,3,opt,name=pokedex_entry,json=pokedexEntry" json:"pokedex_entry,omitempty"`
	PlayerStats       *POGOProtos_Data_Player.PlayerStats    `protobuf:"bytes,4,opt,name=player_stats,json=playerStats" json:"player_stats,omitempty"`
	PlayerCurrency    *POGOProtos_Data_Player.PlayerCurrency `protobuf:"bytes,5,opt,name=player_currency,json=playerCurrency" json:"player_currency,omitempty"`
	PlayerCamera      *POGOProtos_Data_Player.PlayerCamera   `protobuf:"bytes,6,opt,name=player_camera,json=playerCamera" json:"player_camera,omitempty"`
	InventoryUpgrades *InventoryUpgrades                     `protobuf:"bytes,7,opt,name=inventory_upgrades,json=inventoryUpgrades" json:"inventory_upgrades,omitempty"`
	AppliedItems      *AppliedItems                          `protobuf:"bytes,8,opt,name=applied_items,json=appliedItems" json:"applied_items,omitempty"`
	EggIncubators     *EggIncubators                         `protobuf:"bytes,9,opt,name=egg_incubators,json=eggIncubators" json:"egg_incubators,omitempty"`
	PokemonFamily     *PokemonFamily                         `protobuf:"bytes,10,opt,name=pokemon_family,json=pokemonFamily" json:"pokemon_family,omitempty"`
}

func (m *InventoryItemData) Reset()                    { *m = InventoryItemData{} }
func (m *InventoryItemData) String() string            { return proto.CompactTextString(m) }
func (*InventoryItemData) ProtoMessage()               {}
func (*InventoryItemData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InventoryItemData) GetPokemonData() *POGOProtos_Data.PokemonData {
	if m != nil {
		return m.PokemonData
	}
	return nil
}

func (m *InventoryItemData) GetItem() *POGOProtos_Inventory_Item.ItemData {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *InventoryItemData) GetPokedexEntry() *POGOProtos_Data.PokedexEntry {
	if m != nil {
		return m.PokedexEntry
	}
	return nil
}

func (m *InventoryItemData) GetPlayerStats() *POGOProtos_Data_Player.PlayerStats {
	if m != nil {
		return m.PlayerStats
	}
	return nil
}

func (m *InventoryItemData) GetPlayerCurrency() *POGOProtos_Data_Player.PlayerCurrency {
	if m != nil {
		return m.PlayerCurrency
	}
	return nil
}

func (m *InventoryItemData) GetPlayerCamera() *POGOProtos_Data_Player.PlayerCamera {
	if m != nil {
		return m.PlayerCamera
	}
	return nil
}

func (m *InventoryItemData) GetInventoryUpgrades() *InventoryUpgrades {
	if m != nil {
		return m.InventoryUpgrades
	}
	return nil
}

func (m *InventoryItemData) GetAppliedItems() *AppliedItems {
	if m != nil {
		return m.AppliedItems
	}
	return nil
}

func (m *InventoryItemData) GetEggIncubators() *EggIncubators {
	if m != nil {
		return m.EggIncubators
	}
	return nil
}

func (m *InventoryItemData) GetPokemonFamily() *PokemonFamily {
	if m != nil {
		return m.PokemonFamily
	}
	return nil
}

type InventoryUpgrade struct {
	ItemId            POGOProtos_Inventory_Item.ItemId `protobuf:"varint,1,opt,name=item_id,json=itemId,enum=POGOProtos.Inventory.Item.ItemId" json:"item_id,omitempty"`
	UpgradeType       InventoryUpgradeType             `protobuf:"varint,2,opt,name=upgrade_type,json=upgradeType,enum=POGOProtos.Inventory.InventoryUpgradeType" json:"upgrade_type,omitempty"`
	AdditionalStorage int32                            `protobuf:"varint,3,opt,name=additional_storage,json=additionalStorage" json:"additional_storage,omitempty"`
}

func (m *InventoryUpgrade) Reset()                    { *m = InventoryUpgrade{} }
func (m *InventoryUpgrade) String() string            { return proto.CompactTextString(m) }
func (*InventoryUpgrade) ProtoMessage()               {}
func (*InventoryUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type InventoryUpgrades struct {
	InventoryUpgrades []*InventoryUpgrade `protobuf:"bytes,1,rep,name=inventory_upgrades,json=inventoryUpgrades" json:"inventory_upgrades,omitempty"`
}

func (m *InventoryUpgrades) Reset()                    { *m = InventoryUpgrades{} }
func (m *InventoryUpgrades) String() string            { return proto.CompactTextString(m) }
func (*InventoryUpgrades) ProtoMessage()               {}
func (*InventoryUpgrades) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *InventoryUpgrades) GetInventoryUpgrades() []*InventoryUpgrade {
	if m != nil {
		return m.InventoryUpgrades
	}
	return nil
}

type PokemonFamily struct {
	FamilyId POGOProtos_Enums.PokemonFamilyId `protobuf:"varint,1,opt,name=family_id,json=familyId,enum=POGOProtos.Enums.PokemonFamilyId" json:"family_id,omitempty"`
	Candy    int32                            `protobuf:"varint,2,opt,name=candy" json:"candy,omitempty"`
}

func (m *PokemonFamily) Reset()                    { *m = PokemonFamily{} }
func (m *PokemonFamily) String() string            { return proto.CompactTextString(m) }
func (*PokemonFamily) ProtoMessage()               {}
func (*PokemonFamily) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*AppliedItem)(nil), "POGOProtos.Inventory.AppliedItem")
	proto.RegisterType((*AppliedItems)(nil), "POGOProtos.Inventory.AppliedItems")
	proto.RegisterType((*EggIncubator)(nil), "POGOProtos.Inventory.EggIncubator")
	proto.RegisterType((*EggIncubators)(nil), "POGOProtos.Inventory.EggIncubators")
	proto.RegisterType((*InventoryDelta)(nil), "POGOProtos.Inventory.InventoryDelta")
	proto.RegisterType((*InventoryItem)(nil), "POGOProtos.Inventory.InventoryItem")
	proto.RegisterType((*InventoryItemData)(nil), "POGOProtos.Inventory.InventoryItemData")
	proto.RegisterType((*InventoryUpgrade)(nil), "POGOProtos.Inventory.InventoryUpgrade")
	proto.RegisterType((*InventoryUpgrades)(nil), "POGOProtos.Inventory.InventoryUpgrades")
	proto.RegisterType((*PokemonFamily)(nil), "POGOProtos.Inventory.PokemonFamily")
	proto.RegisterEnum("POGOProtos.Inventory.EggIncubatorType", EggIncubatorType_name, EggIncubatorType_value)
	proto.RegisterEnum("POGOProtos.Inventory.InventoryUpgradeType", InventoryUpgradeType_name, InventoryUpgradeType_value)
}

func init() { proto.RegisterFile("inventory/inventory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0xe2, 0x46,
	0x10, 0x3f, 0xc3, 0x91, 0x0b, 0x03, 0x36, 0xb0, 0xc9, 0x55, 0xdc, 0xf5, 0x22, 0xb5, 0xbe, 0x36,
	0x8d, 0x22, 0x15, 0xa4, 0x54, 0x55, 0xa5, 0x3e, 0xf4, 0x4a, 0x12, 0x5f, 0x44, 0x53, 0x02, 0x5a,
	0xa0, 0x57, 0xf5, 0xc5, 0xda, 0xc4, 0x1b, 0xb4, 0x0d, 0x36, 0x96, 0x6d, 0x7a, 0xc7, 0x77, 0xeb,
	0x4b, 0x5f, 0xda, 0x97, 0x7e, 0x96, 0x7e, 0x86, 0xee, 0x1f, 0x1b, 0xd6, 0x1c, 0x39, 0x52, 0xf5,
	0xc5, 0xec, 0xcc, 0xfc, 0xe6, 0xe7, 0xd9, 0xf1, 0x6f, 0x67, 0x81, 0x67, 0x2c, 0xf8, 0x8d, 0x06,
	0xc9, 0x2c, 0x5a, 0xb4, 0x97, 0xab, 0x56, 0x18, 0xcd, 0x92, 0x19, 0xda, 0x1f, 0xf4, 0x2f, 0xfa,
	0x03, 0xb1, 0x8c, 0x5b, 0xdd, 0x2c, 0xf6, 0xfc, 0xe5, 0x12, 0xe6, 0xb2, 0x84, 0xfa, 0xed, 0xbc,
	0xa9, 0x52, 0x9f, 0xd7, 0x3c, 0x92, 0x90, 0xb6, 0x78, 0xa4, 0x8e, 0x03, 0xb1, 0x76, 0xc3, 0x29,
	0x59, 0xd0, 0xa8, 0xad, 0xad, 0xd3, 0x70, 0x83, 0x06, 0x73, 0x3f, 0x6e, 0xcb, 0xa7, 0x72, 0xd9,
	0x7f, 0x19, 0x50, 0xe9, 0x84, 0xe1, 0x94, 0x51, 0xaf, 0xcb, 0x89, 0xd1, 0xb7, 0xf0, 0x44, 0xbc,
	0xc0, 0x65, 0x5e, 0xd3, 0xf8, 0xc4, 0x38, 0xb2, 0x4e, 0x3e, 0x6d, 0x6d, 0xaa, 0xaf, 0x25, 0xc0,
	0xf2, 0xd1, 0xf5, 0xf0, 0x0e, 0x93, 0xbf, 0xe8, 0x7b, 0x28, 0xcb, 0xdc, 0x64, 0x11, 0xd2, 0x66,
	0x41, 0x66, 0xbf, 0xdc, 0x92, 0x3d, 0xe2, 0x50, 0xbc, 0xcb, 0xd2, 0x15, 0xfa, 0x18, 0xca, 0xf4,
	0x5d, 0xc8, 0x22, 0xea, 0xfa, 0x71, 0xb3, 0xc8, 0x19, 0x8a, 0x78, 0x57, 0x39, 0x7a, 0x31, 0x3a,
	0x00, 0x20, 0xaa, 0x52, 0x11, 0x7d, 0x2c, 0xa3, 0xe5, 0xd4, 0xd3, 0x8b, 0x6d, 0x07, 0xaa, 0xda,
	0x46, 0x62, 0xf4, 0x35, 0x3c, 0x16, 0xbc, 0x1c, 0x58, 0x3c, 0xaa, 0xdc, 0xb7, 0x0d, 0x2d, 0x03,
	0x4b, 0xb8, 0xfd, 0x47, 0x01, 0xaa, 0xce, 0x64, 0xd2, 0x0d, 0x6e, 0xe6, 0xd7, 0x84, 0x63, 0x90,
	0x05, 0x85, 0xb4, 0x19, 0x65, 0xcc, 0x57, 0x7a, 0x87, 0x0a, 0xff, 0xb5, 0x43, 0x3d, 0xb0, 0x58,
	0x46, 0xac, 0xda, 0x54, 0x94, 0x14, 0x87, 0x9b, 0x29, 0xf4, 0x3a, 0x64, 0xa7, 0x4c, 0xa6, 0x9b,
	0xe8, 0x73, 0xb0, 0xe6, 0x31, 0x8d, 0xdd, 0x88, 0xfa, 0x84, 0x05, 0x2c, 0x98, 0xc8, 0xae, 0x94,
	0xb0, 0x29, 0xbc, 0x38, 0x73, 0x8a, 0xc6, 0x85, 0xb3, 0x3b, 0xea, 0xcf, 0x02, 0x51, 0x74, 0x89,
	0x43, 0x1e, 0xe3, 0x72, 0xea, 0xe1, 0x45, 0x1d, 0x42, 0x2d, 0x4e, 0x48, 0x94, 0xb8, 0x77, 0xbe,
	0xfb, 0x96, 0x4c, 0xef, 0xa8, 0xd7, 0xdc, 0xe1, 0x18, 0x03, 0x9b, 0xd2, 0x7d, 0xe9, 0xbf, 0x91,
	0x4e, 0x74, 0x04, 0x75, 0x6e, 0x4f, 0xa8, 0x0e, 0x7c, 0x22, 0x81, 0x96, 0xf2, 0x67, 0x48, 0xfb,
	0x67, 0x30, 0xf5, 0xd2, 0x63, 0x74, 0x01, 0x26, 0x9d, 0x4c, 0xdc, 0x65, 0xf5, 0xbc, 0x9d, 0xe2,
	0xa3, 0xd8, 0xdb, 0xb7, 0x8d, 0xab, 0x54, 0xb3, 0xec, 0xdf, 0x0d, 0xb0, 0x96, 0xc0, 0x73, 0x3a,
	0x4d, 0x08, 0x3a, 0x81, 0xa7, 0xb3, 0x88, 0x4d, 0x58, 0x40, 0xa6, 0x6e, 0xc2, 0x7c, 0xca, 0x8b,
	0xf6, 0x43, 0xa1, 0x10, 0x43, 0x2a, 0x64, 0x2f, 0x0b, 0x8e, 0xb2, 0x18, 0x97, 0x12, 0xdf, 0x4a,
	0x40, 0xdf, 0xe6, 0xe1, 0x05, 0x09, 0xb7, 0xb8, 0x5f, 0x47, 0xfe, 0x08, 0xb5, 0xfc, 0xd1, 0x13,
	0xba, 0x14, 0xb5, 0xdf, 0xa7, 0xec, 0x6c, 0x25, 0x25, 0x65, 0x31, 0xdd, 0x8c, 0xed, 0x3f, 0x0d,
	0x30, 0x73, 0x08, 0x51, 0xbd, 0x3f, 0xf3, 0xd8, 0xad, 0x50, 0xf5, 0xa6, 0xea, 0xb3, 0xe0, 0x5a,
	0xf5, 0x1e, 0x9d, 0xd2, 0x84, 0xa7, 0x48, 0x25, 0xde, 0xd1, 0x45, 0x56, 0x7d, 0xea, 0x17, 0xd4,
	0x97, 0x74, 0x81, 0xde, 0xc0, 0x5e, 0xbe, 0x7a, 0x57, 0x0c, 0x05, 0x29, 0xba, 0xca, 0xc9, 0x17,
	0x0f, 0xd8, 0xc1, 0x39, 0x87, 0xe3, 0x06, 0x5b, 0x77, 0xd9, 0xff, 0x94, 0xa0, 0xf1, 0x1e, 0x10,
	0xbd, 0x82, 0x6a, 0x26, 0x34, 0xf9, 0x1e, 0x43, 0xbe, 0xe7, 0x85, 0xfe, 0x1e, 0x81, 0x6b, 0x0d,
	0x14, 0x48, 0x92, 0x57, 0xc2, 0x95, 0x81, 0xbe, 0x49, 0xcf, 0x6c, 0x41, 0x26, 0x6e, 0x1b, 0x1e,
	0x32, 0x5f, 0x26, 0xa0, 0x53, 0x30, 0x05, 0x8f, 0x47, 0xdf, 0xb9, 0x1c, 0x15, 0x2d, 0xd2, 0x2d,
	0x1e, 0x6c, 0x7c, 0x35, 0x47, 0x39, 0x02, 0x84, 0xab, 0xa1, 0x66, 0xa1, 0xd7, 0xbc, 0x7a, 0x39,
	0x2d, 0x5d, 0xde, 0xe8, 0x44, 0x4d, 0x98, 0xb5, 0x22, 0x14, 0x85, 0x1a, 0xa9, 0xea, 0x67, 0x28,
	0xa0, 0x7c, 0x13, 0x2b, 0x03, 0xf5, 0xa1, 0x96, 0xf2, 0xdc, 0xcc, 0xa3, 0x88, 0x06, 0x37, 0x0b,
	0x79, 0xe6, 0x2a, 0xf9, 0x53, 0xfe, 0x3e, 0xd5, 0x59, 0x8a, 0xc6, 0x56, 0x98, 0xb3, 0x51, 0x97,
	0x6f, 0x2e, 0x25, 0x24, 0x3e, 0x8d, 0x88, 0x3c, 0x9e, 0x95, 0x93, 0xcf, 0xb6, 0xd0, 0x49, 0x2c,
	0x4e, 0xf7, 0xa4, 0x2c, 0xf4, 0x13, 0xa0, 0x95, 0x20, 0xe6, 0xe1, 0x24, 0x22, 0x1e, 0x8d, 0xe5,
	0x29, 0xde, 0xae, 0x87, 0x71, 0x0a, 0xd7, 0xf4, 0x90, 0xb9, 0xc4, 0x01, 0xcf, 0x66, 0xb3, 0x3a,
	0x24, 0xbb, 0x92, 0xd2, 0xde, 0x3a, 0x75, 0x63, 0x5c, 0x25, 0xfa, 0xd4, 0xfe, 0x01, 0xac, 0xdc,
	0xa4, 0x88, 0x9b, 0xe5, 0x0f, 0x69, 0x21, 0x37, 0x66, 0xb0, 0x49, 0x73, 0x53, 0x87, 0x73, 0x65,
	0x72, 0xbc, 0x25, 0x3e, 0x9b, 0x2e, 0x9a, 0xf0, 0x21, 0xae, 0x54, 0x95, 0xaf, 0x25, 0x14, 0x9b,
	0xa1, 0x6e, 0xda, 0x7f, 0x1b, 0x50, 0x5f, 0xef, 0xc4, 0xff, 0xba, 0x2c, 0x7b, 0x50, 0x4d, 0xfb,
	0xaf, 0xdf, 0x97, 0xc7, 0x0f, 0xfb, 0x06, 0xf2, 0x32, 0xa8, 0xcc, 0x57, 0x06, 0xfa, 0x12, 0x10,
	0xf1, 0x3c, 0x96, 0xb0, 0x99, 0x98, 0x83, 0x31, 0xc7, 0x92, 0x89, 0xba, 0x5d, 0x4a, 0xb8, 0xb1,
	0x8a, 0x0c, 0x55, 0xc0, 0xfe, 0x55, 0x3b, 0xbe, 0xcb, 0x8f, 0x38, 0xde, 0x28, 0x0e, 0x35, 0xaa,
	0x0f, 0x1f, 0x56, 0xd8, 0x06, 0x6d, 0xd8, 0x14, 0xcc, 0x5c, 0x6b, 0xd1, 0x77, 0x50, 0x56, 0xdf,
	0xe3, 0x9e, 0xc6, 0x39, 0xf2, 0xff, 0x49, 0x2e, 0x87, 0x37, 0x6e, 0xf7, 0x36, 0x5d, 0xa1, 0x7d,
	0x28, 0xdd, 0x90, 0xc0, 0x53, 0x43, 0xaf, 0x84, 0x95, 0x71, 0xfc, 0x0a, 0xea, 0xeb, 0xf7, 0x25,
	0xda, 0x83, 0x5a, 0xf7, 0xea, 0x6c, 0x7c, 0xda, 0x19, 0xf5, 0xb1, 0x3b, 0xbe, 0x1a, 0x3a, 0xa3,
	0xfa, 0x23, 0xf4, 0x11, 0xa0, 0x95, 0xf3, 0xbc, 0x3b, 0x1c, 0x75, 0xae, 0xce, 0x9c, 0xba, 0x71,
	0x7c, 0x0d, 0xfb, 0x9b, 0xfa, 0x8c, 0x1a, 0x60, 0x8e, 0x07, 0x17, 0xb8, 0x73, 0xee, 0x2c, 0x29,
	0x9e, 0xc1, 0x53, 0x4e, 0x81, 0x9d, 0xce, 0xd0, 0x71, 0xbb, 0x23, 0xa7, 0xe7, 0x0e, 0x39, 0x57,
	0xe7, 0x82, 0xb3, 0xa0, 0x17, 0xd0, 0x5c, 0x86, 0x06, 0xfd, 0x4b, 0xa7, 0xd7, 0xbf, 0x5a, 0x46,
	0x0b, 0xa7, 0x95, 0x5f, 0xca, 0xcb, 0x06, 0x0d, 0x1e, 0x0d, 0x8c, 0x41, 0x61, 0x50, 0xbc, 0xde,
	0x91, 0x7f, 0xc5, 0xbe, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x70, 0x5d, 0x1a, 0x8a, 0x25, 0x0a,
	0x00, 0x00,
}
